CREATE TABLE [dbo].[BC_CLASSIFICATION] (
    [ID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [EDITION]  NVARCHAR (256) NULL,
    [LOCATION] NVARCHAR (256) NULL,
    [NAME]     NVARCHAR (256) NULL,
    [MODEL_ID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FKC233D3A44160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID])
);

