CREATE TABLE [dbo].[BC_CLASSITEM] (
    [ID]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [CODE]              NVARCHAR (256) NULL,
    [NAME]              NVARCHAR (256) NULL,
    [CLASSIFICATION_ID] BIGINT         NULL,
    [MODEL_ID]          BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK40761DED4160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FK40761DEDA7E7EE9E] FOREIGN KEY ([CLASSIFICATION_ID]) REFERENCES [dbo].[BC_CLASSIFICATION] ([ID])
);

