CREATE TABLE [dbo].[BC_ELEMCLASSITEM] (
    [ID]                BIGINT IDENTITY (1, 1) NOT NULL,
    [CLASSIFICATION_ID] BIGINT NULL,
    [ELEMENT_ID]        BIGINT NULL,
    [MODEL_ID]          BIGINT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK50AC9A3E4160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FK50AC9A3E53B05EAE] FOREIGN KEY ([ELEMENT_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID]),
    CONSTRAINT [FK50AC9A3E6D9AB94B] FOREIGN KEY ([CLASSIFICATION_ID]) REFERENCES [dbo].[BC_CLASSITEM] ([ID])
);

