CREATE TABLE [dbo].[BC_ELEMENTINFO] (
    [ID]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [LABEL]      NVARCHAR (256) NULL,
    [MATERIAL]   NVARCHAR (256) NULL,
    [TYPE]       NVARCHAR (256) NULL,
    [ELEMENT_ID] BIGINT         NULL,
    [MODEL_ID]   BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK2AED468C4160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FK2AED468C53B05EAE] FOREIGN KEY ([ELEMENT_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

