CREATE TABLE [dbo].[BC_ELEMPROP] (
    [ID]         BIGINT           IDENTITY (1, 1) NOT NULL,
    [GRPNAME]    NVARCHAR (256)   NULL,
    [NAME]       NVARCHAR (256)   NULL,
    [ISNUM]      BIT              NULL,
    [NUMVAL]     NUMERIC (30, 10) NULL,
    [QTYTYPE]    INT              NULL,
    [TXTVAL]     NVARCHAR (MAX)   NULL,
    [ELEMENT_ID] BIGINT           NULL,
    [MODEL_ID]   BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK85BFA1B04160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FK85BFA1B053B05EAE] FOREIGN KEY ([ELEMENT_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

