CREATE TABLE [dbo].[BC_MATERIAL] (
    [ID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [CODE]     NVARCHAR (256) NULL,
    [NAME]     NVARCHAR (256) NULL,
    [MODEL_ID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK980D37654160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID])
);

