CREATE TABLE [dbo].[BC_SCENE] (
    [ID]    BIGINT                     IDENTITY (1, 1) NOT NULL,
    [SGUID] UNIQUEIDENTIFIER           ROWGUIDCOL NOT NULL,
    [SNAME] NVARCHAR (256)             NULL,
    --[SDATA] VARBINARY (MAX) FILESTREAM NULL,
	[SDATA] VARBINARY (MAX)			   NULL,
    [STYPE] INT                        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([SGUID] ASC)
) --FILESTREAM_ON [BIMCity_Filestream];

