CREATE TABLE [dbo].[BC_SPATIALINFO] (
    [ID]         BIGINT     IDENTITY (1, 1) NOT NULL,
    [MAX_X]      FLOAT (53) NULL,
    [MAX_Y]      FLOAT (53) NULL,
    [MAX_Z]      FLOAT (53) NULL,
    [MIN_X]      FLOAT (53) NULL,
    [MIN_Y]      FLOAT (53) NULL,
    [MIN_Z]      FLOAT (53) NULL,
    [ELEMENT_ID] BIGINT     NULL,
    [MODEL_ID]   BIGINT     NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK63A480944160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FK63A4809453B05EAE] FOREIGN KEY ([ELEMENT_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

