CREATE TABLE [dbo].[BENCHMARKBOQCOLMAP] (
    [ID]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [TEMPLATEID] BIGINT         NULL,
    [FROMBENCH]  NVARCHAR (255) NULL,
    [TOBOQ]      NVARCHAR (255) NULL,
    [AGGREGATE]  NVARCHAR (255) NULL,
    [VIEWNAME]   NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

