CREATE TABLE [dbo].[CURRENCY] (
    [ID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [CNAME]   NVARCHAR (255) NULL,
    [SYMBOL]  NVARCHAR (255) NULL,
    [ISOCODE] NVARCHAR (255) NULL,
    [ISOFLAG] NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_CNAME]
    ON [dbo].[CURRENCY]([CNAME] ASC, [SYMBOL] ASC, [ISOCODE] ASC, [ISOFLAG] ASC);

