CREATE TABLE [dbo].[EXTALIAS] (
    [ALIASID]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [LINENUMBER]         SMALLINT       NULL,
    [FROMALIASCLASSNAME] NVARCHAR (255) NULL,
    [FROMALIAS]          NVARCHAR (255) NULL,
    [TOFIELD]            NVARCHAR (255) NULL,
    [DATAMAPPING]        NVARCHAR (MAX) NULL,
    [ISQUERYCOLUMNID]    BIT            NULL,
    [QUERYID]            BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ALIASID] ASC),
    CONSTRAINT [FKC1E428CF25370FFF] FOREIGN KEY ([QUERYID]) REFERENCES [dbo].[EXTQUERY] ([QUERYID])
);

