CREATE TABLE [dbo].[EXTQUERY] (
    [QUERYID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [TITLE]        NVARCHAR (255) NULL,
    [DSQUERY]      NVARCHAR (MAX) NULL,
    [RESOURCETYPE] NVARCHAR (255) NULL,
    [CREATEUSER]   NVARCHAR (255) NULL,
    [CREATEDATE]   DATETIME2 (7)  NULL,
    [EDITORID]     NVARCHAR (255) NULL,
    [LASTUPDATE]   DATETIME2 (7)  NULL,
    [DATASOURCEID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([QUERYID] ASC),
    CONSTRAINT [FKC2C9AB47F85F6433] FOREIGN KEY ([DATASOURCEID]) REFERENCES [dbo].[EXTDATASOURCE] ([DATASOURCEID])
);

