CREATE TABLE [dbo].[FIELDCUSTOM] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]        NVARCHAR (255) NULL,
    [DISPLAYNAME] NVARCHAR (255) NULL,
    [FORMULA]     NVARCHAR (MAX) NULL,
    [RSRC]        NVARCHAR (255) NULL,
    [EDITABLE]    BIT            NULL,
    [SELLIST]     BIT            NULL,
    [SELVALS]     NVARCHAR (MAX) NULL,
    [DEFSEL]      NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

