CREATE TABLE [dbo].[FILTRO] (
    [FILTROID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [LASTUPDATE]        DATETIME2 (7)  NULL,
    [FILTRONAME]        NVARCHAR (255) NULL,
    [FILTROTYPE]        NVARCHAR (255) NULL,
    [FILTRODESCRIPTION] NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([FILTROID] ASC)
);

