CREATE TABLE [dbo].[FILTROPROPERTY] (
    [FILTROPROPERTYID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [USED]                  BIT            NULL,
    [USETYPE]               NVARCHAR (255) NULL,
    [FIELD]                 NVARCHAR (255) NULL,
    [RESTRICTION]           NVARCHAR (255) NULL,
    [FILTROID]              BIGINT         NULL,
    [FILTROPROPERTIESCOUNT] INT            NULL,
    PRIMARY KEY CLUSTERED ([FILTROPROPERTYID] ASC),
    CONSTRAINT [FKDDE206DDF6543BAE] FOREIGN KEY ([FILTROID]) REFERENCES [dbo].[FILTRO] ([FILTROID])
);

