CREATE TABLE [dbo].[FLDFN] (
    [FLDFNID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]             NVARCHAR (255) NULL,
    [FTYPE]            NVARCHAR (255) NULL,
    [FPATH]            NVARCHAR (255) NULL,
    [RPDFNID]          BIGINT         NULL,
    [RPDFNFILDEFCOUNT] INT            NULL,
    PRIMARY KEY CLUSTERED ([FLDFNID] ASC),
    CONSTRAINT [FK3FE018669939745] FOREIGN KEY ([RPDFNID]) REFERENCES [dbo].[RPDFN] ([RPDFNID])
);

