CREATE TABLE [dbo].[FNCTON_ARGUMENT] (
    [FARGID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]        NVARCHAR (255) NULL,
    [SORDER]      INT            NULL,
    [ARTYPE]      NVARCHAR (255) NULL,
    [EDITABLE]    BIT            NULL,
    [FID]         BIGINT         NULL,
    [DESCRIPTION] NVARCHAR (MAX) NULL,
    [SELLIST]     NVARCHAR (MAX) NULL,
    [TYPE]        NVARCHAR (255) NULL,
    [UNIT]        NVARCHAR (255) NULL,
    [VALSTA]      NVARCHAR (MAX) NULL,
    [DEPSTA]      NVARCHAR (MAX) NULL,
    [DEFVAL]      NVARCHAR (MAX) NULL,
    [GROUPING]    NVARCHAR (255) NULL,
    [VARSCOUNT]   INT            NULL,
    PRIMARY KEY CLUSTERED ([FARGID] ASC),
    CONSTRAINT [FK8C659444F8BAE1EC] FOREIGN KEY ([FID]) REFERENCES [dbo].[FNCTON] ([FUNCTIONID])
);

