CREATE TABLE [dbo].[LOCFACTOR] (
    [LFID]        BIGINT           IDENTITY (1, 1) NOT NULL,
    [PARENTECODE] NVARCHAR (255)   NULL,
    [EDITORID]    NVARCHAR (255)   NULL,
    [ONLN]        BIT              NULL,
    [CODETYPE]    NVARCHAR (255)   NULL,
    [TOCOUNTRY]   NVARCHAR (255)   NULL,
    [TOSTATE]     NVARCHAR (255)   NULL,
    [TOCITY]      NVARCHAR (255)   NULL,
    [TOZIPCODE]   NVARCHAR (255)   NULL,
    [LABFAC]      NUMERIC (30, 10) NULL,
    [MATFAC]      NUMERIC (30, 10) NULL,
    [SUBFAC]      NUMERIC (30, 10) NULL,
    [CONFAC]      NUMERIC (30, 10) NULL,
    [EQUFAC]      NUMERIC (30, 10) NULL,
    [ASSFAC]      NUMERIC (30, 10) NULL,
    [GEOPOLY]     NVARCHAR (MAX)   NULL,
    [FID]         BIGINT           NULL,
    [FACCOUNT]    INT              NULL,
    PRIMARY KEY CLUSTERED ([LFID] ASC),
    CONSTRAINT [FK66363C6F9B8D46AA] FOREIGN KEY ([FID]) REFERENCES [dbo].[LOCPROF] ([FUNCTIONID])
);

