CREATE TABLE [dbo].[LOCPROF] (
    [FUNCTIONID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [FROMCOUNTRY]  NVARCHAR (255) NULL,
    [FROMSTATE]    NVARCHAR (255) NULL,
    [NAME]         NVARCHAR (255) NULL,
    [SUPSTATE]     BIT            NULL,
    [EDITORID]     NVARCHAR (255) NULL,
    [CREATEUSERID] NVARCHAR (255) NULL,
    [CREATEDATE]   DATETIME2 (7)  NULL,
    [LASTUPDATE]   DATETIME2 (7)  NULL,
    PRIMARY KEY CLUSTERED ([FUNCTIONID] ASC)
);

