CREATE TABLE [dbo].[PROJECTUSERTEMPLATE] (
    [TEMPLATEID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]       NVARCHAR (255) NULL,
    [XCHANGE]    BIT            NULL,
    [ESCLTE]     BIT            NULL,
    [PROPS]      BIT            NULL,
    [TAKEOFF]    BIT            NULL,
    [RSRC]       BIT            NULL,
    [ESTIM]      BIT            NULL,
    [ADMN]       BIT            NULL,
    [SQUOTE]     BIT            NULL,
    [RQUOTE]     BIT            NULL,
    [AQUOTE]     BIT            NULL,
    [WBS]        BIT            NULL,
    [ADITMS]     BIT            NULL,
    [RMITMS]     BIT            NULL,
    [EDITMS]     BIT            NULL,
    [VAITMS]     BIT            NULL,
    [VARSUSR]    BIT            NULL,
    [VARSADMIN]  BIT            NULL,
    [VARSVIEWER] BIT            NULL,
    [CREATEUSER] NVARCHAR (255) NULL,
    [CREATEDATE] DATETIME2 (7)  NULL,
    [EDITORID]   NVARCHAR (255) NULL,
    [LASTUPDATE] DATETIME2 (7)  NULL,
    PRIMARY KEY CLUSTERED ([TEMPLATEID] ASC)
);

