CREATE TABLE [dbo].[ROLES] (
    [ROLEID]      VARCHAR (255) NOT NULL,
    [PRINCIPALID] VARCHAR (255) NULL,
    [ROLE]        VARCHAR (255) NULL,
    [ROLEGROUP]   VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ROLEID] ASC)
);

