CREATE TABLE [dbo].[TAKEOFFTRIANGLE] (
    [ID]        BIGINT           IDENTITY (1, 1) NOT NULL,
    [XPOS1]     NUMERIC (30, 10) NULL,
    [YPOS1]     NUMERIC (30, 10) NULL,
    [ZPOS1]     NUMERIC (30, 10) NULL,
    [XPOS2]     NUMERIC (30, 10) NULL,
    [YPOS2]     NUMERIC (30, 10) NULL,
    [ZPOS2]     NUMERIC (30, 10) NULL,
    [XPOS3]     NUMERIC (30, 10) NULL,
    [YPOS3]     NUMERIC (30, 10) NULL,
    [ZPOS3]     NUMERIC (30, 10) NULL,
    [TID]       BIGINT           NULL,
    [TRIACOUNT] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK99DDF570412BA1F3] FOREIGN KEY ([TID]) REFERENCES [dbo].[TAKEOFFAREA] ([ID])
);

