CREATE TABLE [dbo].[USERPROP] (
    [ID]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [USERID] NVARCHAR (255) NULL,
    [PKEY]   NVARCHAR (255) NULL,
    [PVAL]   NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_USERPROPKEY]
    ON [dbo].[USERPROP]([PKEY] ASC);

