CREATE TABLE [dbo].[USERSESSIONS] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [USERNAME]        NVARCHAR (255) NULL,
    [SERIALKEY]       NVARCHAR (255) NULL,
    [LOGGEDIN_DATE]   DATETIME2 (7)  NULL,
    [LASTUPDATE_DATE] DATETIME2 (7)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

