CREATE TABLE [dbo].[WSREVISION] (
    [ID]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [TITLE]        NVARCHAR (255) NULL,
    [CREATEDATE]   DATETIME2 (7)  NULL,
    [LASTUPDATE]   DATETIME2 (7)  NULL,
    [CREATEUSERID] NVARCHAR (255) NULL,
    [EDITORID]     NVARCHAR (255) NULL,
    [DESCRIPTION]  NVARCHAR (MAX) NULL,
    [PBLK]         BIT            NULL,
    [MAPPINGID]    BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK364016B7BCB673A4] FOREIGN KEY ([MAPPINGID]) REFERENCES [dbo].[WSDATAMAPPING] ([ID])
);

