using System;
using System.Collections.Generic;

namespace Model.DB.Project
{
    public partial class Boqitem
    {
        public Boqitem()
        {
            BoqitemAssembly = new HashSet<BoqitemAssembly>();
            BoqitemCondition = new HashSet<BoqitemCondition>();
            BoqitemConsumable = new HashSet<BoqitemConsumable>();
            BoqitemEquipment = new HashSet<BoqitemEquipment>();
            BoqitemLabor = new HashSet<BoqitemLabor>();
            BoqitemMaterial = new HashSet<BoqitemMaterial>();
            BoqitemSubcontractor = new HashSet<BoqitemSubcontractor>();
            ParamitemNavigation = new HashSet<Paramitem>();
            Quoteitem = new HashSet<Quoteitem>();
        }

        public long Boqitemid { get; set; }
        public long? Paramitemid { get; set; }
        public long? Glbparamitemid { get; set; }
        public string Paramcode { get; set; }
        public long? Code { get; set; }
        public string Title { get; set; }
        public string Mqtyform { get; set; }
        public string Eqtyform { get; set; }
        public string Ttlform { get; set; }
        public string Dscform { get; set; }
        public string Wbsform { get; set; }
        public string Wbs2form { get; set; }
        public string Qtyform { get; set; }
        public string Markupform { get; set; }
        public string Durationform { get; set; }
        public string Prodform { get; set; }
        public string Umhform { get; set; }
        public string Aumhform { get; set; }
        public string Totalcostform { get; set; }
        public string Offeredpriceform { get; set; }
        public string Rateform { get; set; }
        public string Offrateform { get; set; }
        public string Offsecrateform { get; set; }
        public string Secrateform { get; set; }
        public string Secqtyform { get; set; }
        public string Qtylossform { get; set; }
        public string Secunitform { get; set; }
        public string Unitsdivform { get; set; }
        public string Asstotalform { get; set; }
        public string Equtotalform { get; set; }
        public string Mattotalform { get; set; }
        public string Subtotalform { get; set; }
        public string Labtotalform { get; set; }
        public string Contotalform { get; set; }
        public bool? Scheduled { get; set; }
        public bool? HasProductivity { get; set; }
        public bool? Actbased { get; set; }
        public bool? HasAssform { get; set; }
        public bool? HasPvform { get; set; }
        public string PvVars { get; set; }
        public string Description { get; set; }
        public decimal? Duration { get; set; }
        public string Groupcode { get; set; }
        public string Gekcode { get; set; }
        public string Notes { get; set; }
        public string Surfacetype { get; set; }
        public string Status { get; set; }
        public int? Flag { get; set; }
        public decimal? Productivity { get; set; }
        public decimal? Adjprod { get; set; }
        public string Prodfacform { get; set; }
        public string Mhfacform { get; set; }
        public string Adjprodform { get; set; }
        public decimal? Prodfactor { get; set; }
        public decimal? Mhoursfactor { get; set; }
        public string Locprof { get; set; }
        public string Locfac { get; set; }
        public string Loccountry { get; set; }
        public string Locstate { get; set; }
        public decimal? Manhours { get; set; }
        public decimal? Equhours { get; set; }
        public decimal? Unitmhours { get; set; }
        public decimal? Aunitmhours { get; set; }
        public string Publisheditemcode { get; set; }
        public decimal? Publishedrate { get; set; }
        public string Publishedrevisioncode { get; set; }
        public string Generationid { get; set; }
        public string Vars { get; set; }
        public string Bimtype { get; set; }
        public string Bimmaterial { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Measquant { get; set; }
        public decimal? Estquant { get; set; }
        public decimal? Quantloss { get; set; }
        public decimal? Secquantity { get; set; }
        public string Accuracy { get; set; }
        public decimal? Markup { get; set; }
        public decimal? Awdmat { get; set; }
        public decimal? Awdins { get; set; }
        public decimal? Awdsub { get; set; }
        public decimal? Awdmhours { get; set; }
        public decimal? Awdind { get; set; }
        public decimal? Awdship { get; set; }
        public decimal? Awdtotal { get; set; }
        public decimal? Escalation { get; set; }
        public decimal? UnitsDiv { get; set; }
        public decimal? Assrate { get; set; }
        public decimal? Labrate { get; set; }
        public decimal? Subrate { get; set; }
        public decimal? Subquoterate { get; set; }
        public decimal? Equrate { get; set; }
        public decimal? Conrate { get; set; }
        public decimal? Matrate { get; set; }
        public decimal? Matquoterate { get; set; }
        public decimal? Fabrate { get; set; }
        public decimal? Shiprate { get; set; }
        public decimal? Asscost { get; set; }
        public decimal? Labcost { get; set; }
        public decimal? Subcost { get; set; }
        public decimal? Equcost { get; set; }
        public decimal? Concost { get; set; }
        public decimal? Matcost { get; set; }
        public decimal? Fabcost { get; set; }
        public decimal? Shipcost { get; set; }
        public decimal? Matrescost { get; set; }
        public decimal? Rate { get; set; }
        public decimal? Totalcost { get; set; }
        public decimal? Fixedcost { get; set; }
        public decimal? Offsecrate { get; set; }
        public decimal? Offprice { get; set; }
        public decimal? Offrate { get; set; }
        public decimal? Secrate { get; set; }
        public decimal? CalculatedRate { get; set; }
        public decimal? CalculatedTotalCost { get; set; }
        public string Unit { get; set; }
        public string SecondUnit { get; set; }
        public string Wrslkp { get; set; }
        public DateTime? PaymentDate { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? LastUpdate { get; set; }
        public string Editorid { get; set; }
        public string Estimator { get; set; }
        public string Createuserid { get; set; }
        public string Extracode1 { get; set; }
        public string Extracode2 { get; set; }
        public string Wbscode { get; set; }
        public string Wbs2code { get; set; }
        public string Rollup { get; set; }
        public string Location { get; set; }
        public string Extracode3 { get; set; }
        public string Extracode4 { get; set; }
        public string Extracode5 { get; set; }
        public string Extracode6 { get; set; }
        public string Extracode7 { get; set; }
        public string Extracode8 { get; set; }
        public string Extracode9 { get; set; }
        public string Extracode10 { get; set; }
        public decimal? Pugrcfactor { get; set; }
        public decimal? Pugekfactor { get; set; }
        public decimal? Puex1factor { get; set; }
        public decimal? Puex2factor { get; set; }
        public decimal? Puex3factor { get; set; }
        public decimal? Puex4factor { get; set; }
        public decimal? Puex5factor { get; set; }
        public decimal? Puex6factor { get; set; }
        public decimal? Puex7factor { get; set; }
        public decimal? Cusrate1 { get; set; }
        public decimal? Cusrate2 { get; set; }
        public decimal? Cusrate3 { get; set; }
        public decimal? Cusrate4 { get; set; }
        public decimal? Cusrate5 { get; set; }
        public decimal? Cusrate6 { get; set; }
        public decimal? Cusrate7 { get; set; }
        public decimal? Cusrate8 { get; set; }
        public decimal? Cusrate9 { get; set; }
        public decimal? Cusrate10 { get; set; }
        public decimal? Cusrate11 { get; set; }
        public decimal? Cusrate12 { get; set; }
        public decimal? Cusrate13 { get; set; }
        public decimal? Cusrate14 { get; set; }
        public decimal? Cusrate15 { get; set; }
        public decimal? Cusrate16 { get; set; }
        public decimal? Cusrate17 { get; set; }
        public decimal? Cusrate18 { get; set; }
        public decimal? Cusrate19 { get; set; }
        public decimal? Cusrate20 { get; set; }
        public decimal? Cuscumrate1 { get; set; }
        public decimal? Cuscumrate2 { get; set; }
        public decimal? Cuscumrate3 { get; set; }
        public decimal? Cuscumrate4 { get; set; }
        public decimal? Cuscumrate5 { get; set; }
        public decimal? Cuscumrate6 { get; set; }
        public decimal? Cuscumrate7 { get; set; }
        public decimal? Cuscumrate8 { get; set; }
        public decimal? Cuscumrate9 { get; set; }
        public decimal? Cuscumrate10 { get; set; }
        public decimal? Cuscumrate11 { get; set; }
        public decimal? Cuscumrate12 { get; set; }
        public decimal? Cuscumrate13 { get; set; }
        public decimal? Cuscumrate14 { get; set; }
        public decimal? Cuscumrate15 { get; set; }
        public decimal? Cuscumrate16 { get; set; }
        public decimal? Cuscumrate17 { get; set; }
        public decimal? Cuscumrate18 { get; set; }
        public decimal? Cuscumrate19 { get; set; }
        public decimal? Cuscumrate20 { get; set; }
        public decimal? Cusper1 { get; set; }
        public decimal? Cusper2 { get; set; }
        public decimal? Cusper3 { get; set; }
        public decimal? Cusper4 { get; set; }
        public decimal? Cusper5 { get; set; }
        public decimal? Cusper6 { get; set; }
        public decimal? Cusper7 { get; set; }
        public decimal? Cusper8 { get; set; }
        public decimal? Cusper9 { get; set; }
        public decimal? Cusper10 { get; set; }
        public decimal? Cusper11 { get; set; }
        public decimal? Cusper12 { get; set; }
        public decimal? Cusper13 { get; set; }
        public decimal? Cusper14 { get; set; }
        public decimal? Cusper15 { get; set; }
        public decimal? Cusper16 { get; set; }
        public decimal? Cusper17 { get; set; }
        public decimal? Cusper18 { get; set; }
        public decimal? Cusper19 { get; set; }
        public decimal? Cusper20 { get; set; }
        public string Custxt1 { get; set; }
        public string Custxt2 { get; set; }
        public string Custxt3 { get; set; }
        public string Custxt4 { get; set; }
        public string Custxt5 { get; set; }
        public string Custxt6 { get; set; }
        public string Custxt7 { get; set; }
        public string Custxt8 { get; set; }
        public string Custxt9 { get; set; }
        public string Custxt10 { get; set; }
        public string Custxt11 { get; set; }
        public string Custxt12 { get; set; }
        public string Custxt13 { get; set; }
        public string Custxt14 { get; set; }
        public string Custxt15 { get; set; }
        public string Custxt16 { get; set; }
        public string Custxt17 { get; set; }
        public string Custxt18 { get; set; }
        public string Custxt19 { get; set; }
        public string Custxt20 { get; set; }
        public string Custxt21 { get; set; }
        public string Custxt22 { get; set; }
        public string Custxt23 { get; set; }
        public string Custxt24 { get; set; }
        public string Custxt25 { get; set; }
        public string Cusrate1form { get; set; }
        public string Cusrate2form { get; set; }
        public string Cusrate3form { get; set; }
        public string Cusrate4form { get; set; }
        public string Cusrate5form { get; set; }
        public string Cusrate6form { get; set; }
        public string Cusrate7form { get; set; }
        public string Cusrate8form { get; set; }
        public string Cusrate9form { get; set; }
        public string Cusrate10form { get; set; }
        public string Cusrate11form { get; set; }
        public string Cusrate12form { get; set; }
        public string Cusrate13form { get; set; }
        public string Cusrate14form { get; set; }
        public string Cusrate15form { get; set; }
        public string Cusrate16form { get; set; }
        public string Cusrate17form { get; set; }
        public string Cusrate18form { get; set; }
        public string Cusrate19form { get; set; }
        public string Cusrate20form { get; set; }
        public string Cuscum1form { get; set; }
        public string Cuscum2form { get; set; }
        public string Cuscum3form { get; set; }
        public string Cuscum4form { get; set; }
        public string Cuscum5form { get; set; }
        public string Cuscum6form { get; set; }
        public string Cuscum7form { get; set; }
        public string Cuscum8form { get; set; }
        public string Cuscum9form { get; set; }
        public string Cuscum10form { get; set; }
        public string Cuscum11form { get; set; }
        public string Cuscum12form { get; set; }
        public string Cuscum13form { get; set; }
        public string Cuscum14form { get; set; }
        public string Cuscum15form { get; set; }
        public string Cuscum16form { get; set; }
        public string Cuscum17form { get; set; }
        public string Cuscum18form { get; set; }
        public string Cuscum19form { get; set; }
        public string Cuscum20form { get; set; }
        public string Cusper1form { get; set; }
        public string Cusper2form { get; set; }
        public string Cusper3form { get; set; }
        public string Cusper4form { get; set; }
        public string Cusper5form { get; set; }
        public string Cusper6form { get; set; }
        public string Cusper7form { get; set; }
        public string Cusper8form { get; set; }
        public string Cusper9form { get; set; }
        public string Cusper10form { get; set; }
        public string Cusper11form { get; set; }
        public string Cusper12form { get; set; }
        public string Cusper13form { get; set; }
        public string Cusper14form { get; set; }
        public string Cusper15form { get; set; }
        public string Cusper16form { get; set; }
        public string Cusper17form { get; set; }
        public string Cusper18form { get; set; }
        public string Cusper19form { get; set; }
        public string Cusper20form { get; set; }
        public string Custxt1form { get; set; }
        public string Custxt2form { get; set; }
        public string Custxt3form { get; set; }
        public string Custxt4form { get; set; }
        public string Custxt5form { get; set; }
        public string Custxt6form { get; set; }
        public string Custxt7form { get; set; }
        public string Custxt8form { get; set; }
        public string Custxt9form { get; set; }
        public string Custxt10form { get; set; }
        public string Custxt11form { get; set; }
        public string Custxt12form { get; set; }
        public string Custxt13form { get; set; }
        public string Custxt14form { get; set; }
        public string Custxt15form { get; set; }
        public string Custxt16form { get; set; }
        public string Custxt17form { get; set; }
        public string Custxt18form { get; set; }
        public string Custxt19form { get; set; }
        public string Custxt20form { get; set; }
        public string Custxt21form { get; set; }
        public string Custxt22form { get; set; }
        public string Custxt23form { get; set; }
        public string Custxt24form { get; set; }
        public string Custxt25form { get; set; }
        public DateTime? Cusdate1 { get; set; }
        public DateTime? Cusdate2 { get; set; }
        public DateTime? Cusdate3 { get; set; }
        public DateTime? Cusdate4 { get; set; }
        public DateTime? Cusdate5 { get; set; }
        public byte? Asrt { get; set; }
        public byte? Eqrt { get; set; }
        public byte? Sbrt { get; set; }
        public byte? Lbrt { get; set; }
        public byte? Mart { get; set; }
        public byte? Cmrt { get; set; }
        public byte? Cnqt { get; set; }
        public long? Prjid { get; set; }
        public long? RefId { get; set; }

        public virtual Paramitem Paramitem { get; set; }
        public virtual ICollection<BoqitemAssembly> BoqitemAssembly { get; set; }
        public virtual ICollection<BoqitemCondition> BoqitemCondition { get; set; }
        public virtual ICollection<BoqitemConsumable> BoqitemConsumable { get; set; }
        public virtual ICollection<BoqitemEquipment> BoqitemEquipment { get; set; }
        public virtual ICollection<BoqitemLabor> BoqitemLabor { get; set; }
        public virtual ICollection<BoqitemMaterial> BoqitemMaterial { get; set; }
        public virtual ICollection<BoqitemSubcontractor> BoqitemSubcontractor { get; set; }
        public virtual ICollection<Paramitem> ParamitemNavigation { get; set; }
        public virtual ICollection<Quoteitem> Quoteitem { get; set; }
    }
}
