CREATE TABLE [dbo].[ASSEMBLY_MATERIAL] (
    [ASSEMBLYMATERIALID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [LASTUPDATE]         DATETIME2 (7)    NULL,
    [FRATE]              NUMERIC (30, 10) NULL,
    [FACTOR1]            NUMERIC (30, 10) NULL,
    [FACTOR2]            NUMERIC (30, 10) NULL,
    [DIVIDER]            NUMERIC (30, 10) NULL,
    [QTYPUNIT]           NUMERIC (30, 10) NULL,
    [QTYPUNITFORM]       NVARCHAR (MAX)   NULL,
    [QTYPUFORMSTATE]     TINYINT          NULL,
    [LOCALFACTOR]        NUMERIC (30, 10) NULL,
    [LOCALCOUNTRY]       NVARCHAR (255)   NULL,
    [LOCALSTATE]         NVARCHAR (255)   NULL,
    [EXCHANGERATE]       NUMERIC (30, 10) NULL,
    [FIXEDCOST]          NUMERIC (30, 10) NULL,
    [FINALFIXEDCOST]     NUMERIC (30, 10) NULL,
    [PV_VARS]            NVARCHAR (MAX)   NULL,
    [MATERIALID]         BIGINT           NULL,
    [ASSEMBLYID]         BIGINT           NULL,
    [PRJID]              BIGINT           NULL,
    [REF__ID]            BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([ASSEMBLYMATERIALID] ASC),
    CONSTRAINT [FKC0D89B6014030E1E] FOREIGN KEY ([ASSEMBLYID]) REFERENCES [dbo].[ASSEMBLY] ([ASSEMBLYID]),
    CONSTRAINT [FKC0D89B602461A27E] FOREIGN KEY ([MATERIALID]) REFERENCES [dbo].[MATERIAL] ([MATERIALID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSEMBLY]
    ON [dbo].[ASSEMBLY_MATERIAL]([ASSEMBLYID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_MATERIAL]
    ON [dbo].[ASSEMBLY_MATERIAL]([MATERIALID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[ASSEMBLY_MATERIAL]([PRJID] ASC);

