CREATE TABLE [dbo].[BOQITEM_LABOR] (
    [BOQITEMLABORID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [FRATE]          NUMERIC (30, 10) NULL,
    [TOTALCOST]      NUMERIC (30, 10) NULL,
    [PARAMITEMID]    BIGINT           NULL,
    [FACTOR1]        NUMERIC (30, 10) NULL,
    [FACTOR2]        NUMERIC (30, 10) NULL,
    [FACTOR3]        NUMERIC (30, 10) NULL,
    [QTYPUNIT]       NUMERIC (30, 10) NULL,
    [QTYPUNITFORM]   NVARCHAR (MAX)   NULL,
    [QTYPUFORMSTATE] TINYINT          NULL,
    [COSTCENTER]     NUMERIC (30, 10) NULL,
    [LOCALFACTOR]    NUMERIC (30, 10) NULL,
    [LOCALCOUNTRY]   NVARCHAR (255)   NULL,
    [LOCALSTATE]     NVARCHAR (255)   NULL,
    [TOTALUNITS]     NUMERIC (30, 10) NULL,
    [USERTOTALUNITS] BIT              NULL,
    [FIXEDCOST]      NUMERIC (30, 10) NULL,
    [FINALFIXEDCOST] NUMERIC (30, 10) NULL,
    [VARIABLECOST]   NUMERIC (30, 10) NULL,
    [UNITHOURS]      NUMERIC (30, 10) NULL,
    [PV_VARS]        NVARCHAR (MAX)   NULL,
    [LAST_UPDATE]    DATETIME2 (7)    NULL,
    [LABORID]        BIGINT           NULL,
    [BOQITEMID]      BIGINT           NULL,
    [PRJID]          BIGINT           NULL,
    [REF__ID]        BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([BOQITEMLABORID] ASC),
    CONSTRAINT [FKD8B6C8885C7E33D4] FOREIGN KEY ([LABORID]) REFERENCES [dbo].[LABOR] ([LABORID]),
    CONSTRAINT [FKD8B6C88889F3BCA6] FOREIGN KEY ([BOQITEMID]) REFERENCES [dbo].[BOQITEM] ([BOQITEMID]),
    CONSTRAINT [FKD8B6C888B8FEF034] FOREIGN KEY ([PARAMITEMID]) REFERENCES [dbo].[PARAMITEM] ([PARAMITEMID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_BOQITEM]
    ON [dbo].[BOQITEM_LABOR]([BOQITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_LABOR]
    ON [dbo].[BOQITEM_LABOR]([LABORID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[BOQITEM_LABOR]([PRJID] ASC);

