CREATE TABLE [dbo].[IFCPROPERTY] (
    [PROPID]       BIGINT           IDENTITY (1, 1) NOT NULL,
    [IFCPROPGROUP] NVARCHAR (255)   NULL,
    [IFCPROPNAME]  NVARCHAR (255)   NULL,
    [IFCQTYTYPE]   INT              NULL,
    [IFCISNUM]     BIT              NULL,
    [IFCVALUE]     NVARCHAR (255)   NULL,
    [IFCNUMVAL]    NUMERIC (30, 10) NULL,
    [IFCMTUOM]     NVARCHAR (255)   NULL,
    [ELEMID]       BIGINT           NULL,
    [PRJID]        BIGINT           NULL,
    [REF__ID]      BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([PROPID] ASC),
    CONSTRAINT [FK2A8C29BE515D4A5] FOREIGN KEY ([ELEMID]) REFERENCES [dbo].[IFCELEMENT] ([ELEMID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ELEMID]
    ON [dbo].[IFCPROPERTY]([ELEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PNAME]
    ON [dbo].[IFCPROPERTY]([IFCPROPNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[IFCPROPERTY]([PRJID] ASC);

