CREATE TABLE [dbo].[PARAMCONDITION] (
    [CONDITIONID]  BIGINT           IDENTITY (1, 1) NOT NULL,
    [VIRT]         BIT              NULL,
    [DESCRIPTION]  NVARCHAR (MAX)   NULL,
    [TITLE]        NVARCHAR (255)   NULL,
    [SELQTY]       INT              NULL,
    [QTY1]         NUMERIC (30, 10) NULL,
    [QTY2]         NUMERIC (30, 10) NULL,
    [QTY3]         NUMERIC (30, 10) NULL,
    [QTYF]         NUMERIC (30, 10) NULL,
    [UNIT1]        NVARCHAR (255)   NULL,
    [UNIT2]        NVARCHAR (255)   NULL,
    [UNIT3]        NVARCHAR (255)   NULL,
    [UNITF]        NVARCHAR (255)   NULL,
    [DBNAME]       NVARCHAR (255)   NULL,
    [USERNAME]     NVARCHAR (255)   NULL,
    [PASSWORD]     NVARCHAR (255)   NULL,
    [HOST]         NVARCHAR (255)   NULL,
    [BIDNO]        INT              NULL,
    [CNDNO]        INT              NULL,
    [CNDTYPE]      NVARCHAR (255)   NULL,
    [CNDID]        INT              NULL,
    [GLOBALID]     NVARCHAR (255)   NULL,
    [PICKTYPE]     INT              NULL,
    [PICKDATA]     NVARCHAR (MAX)   NULL,
    [TAKEOFFTYPE]  NVARCHAR (255)   NULL,
    [BUILDING]     NVARCHAR (255)   NULL,
    [STOREY]       NVARCHAR (255)   NULL,
    [LOCATION]     NVARCHAR (255)   NULL,
    [LAYER]        NVARCHAR (255)   NULL,
    [QTY1NAME]     NVARCHAR (255)   NULL,
    [QTY2NAME]     NVARCHAR (255)   NULL,
    [QTY3NAME]     NVARCHAR (255)   NULL,
    [QTYFNAME]     NVARCHAR (255)   NULL,
    [FORMULA1]     NVARCHAR (255)   NULL,
    [FORMULA2]     NVARCHAR (255)   NULL,
    [FORMULA3]     NVARCHAR (255)   NULL,
    [FORMULAF]     NVARCHAR (MAX)   NULL,
    [BIMTYPE]      NVARCHAR (255)   NULL,
    [FCTSTATE]     NVARCHAR (MAX)   NULL,
    [BIMMATERIAL]  NVARCHAR (MAX)   NULL,
    [PARAMITEMID]  BIGINT           NULL,
    [PARAMINPUTID] BIGINT           NULL,
    [PRJID]        BIGINT           NULL,
    [REF__ID]      BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([CONDITIONID] ASC),
    CONSTRAINT [FK5664872E68123411] FOREIGN KEY ([PARAMINPUTID]) REFERENCES [dbo].[PARAMINPUT] ([PARAMINPUTID]),
    CONSTRAINT [FK5664872EB8FEF034] FOREIGN KEY ([PARAMITEMID]) REFERENCES [dbo].[PARAMITEM] ([PARAMITEMID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_PARAMINPUT]
    ON [dbo].[PARAMCONDITION]([PARAMINPUTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PARAMITEM]
    ON [dbo].[PARAMCONDITION]([PARAMITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[PARAMCONDITION]([PRJID] ASC);

