CREATE TABLE [dbo].[RATEBUILDUP] (
    [ID]           BIGINT           IDENTITY (1, 1) NOT NULL,
    [TEMPLATEID]   BIGINT           NULL,
    [RESTYPE]      NVARCHAR (255)   NULL,
    [RESID]        BIGINT           NULL,
    [RESPRJID]     BIGINT           NULL,
    [ONLN]         BIT              NULL,
    [DBCREATEDATE] BIGINT           NULL,
    [CALCFORMULA]  NVARCHAR (MAX)   NULL,
    [OVERRATE1]    NVARCHAR (MAX)   NULL,
    [FRATE]        NUMERIC (30, 10) NULL,
    [RATE0]        NUMERIC (30, 10) NULL,
    [RATE1]        NUMERIC (30, 10) NULL,
    [RATE2]        NUMERIC (30, 10) NULL,
    [RATE3]        NUMERIC (30, 10) NULL,
    [RATE4]        NUMERIC (30, 10) NULL,
    [RATE5]        NUMERIC (30, 10) NULL,
    [RATE6]        NUMERIC (30, 10) NULL,
    [RATE7]        NUMERIC (30, 10) NULL,
    [RATE8]        NUMERIC (30, 10) NULL,
    [RATE9]        NUMERIC (30, 10) NULL,
    [RATE10]       NUMERIC (30, 10) NULL,
    [RATE11]       NUMERIC (30, 10) NULL,
    [RATE12]       NUMERIC (30, 10) NULL,
    [RATE13]       NUMERIC (30, 10) NULL,
    [RATE14]       NUMERIC (30, 10) NULL,
    [PRJID]        BIGINT           NULL,
    [REF__ID]      BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK969BFC899A9C964D] FOREIGN KEY ([TEMPLATEID]) REFERENCES [dbo].[PROJECTTEMPLATE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[RATEBUILDUP]([PRJID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PROJECTTEMPLATE]
    ON [dbo].[RATEBUILDUP]([TEMPLATEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_RESID]
    ON [dbo].[RATEBUILDUP]([RESID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_RESPRJID]
    ON [dbo].[RATEBUILDUP]([RESPRJID] ASC);

