CREATE TABLE [dbo].[RAWMATERIAL] (
    [RAWMATID]  BIGINT           IDENTITY (1, 1) NOT NULL,
    [CODE]      NVARCHAR (255)   NULL,
    [RATE]      NUMERIC (30, 10) NULL,
    [RATE_DATE] DATETIME2 (7)    NULL,
    [PRJID]     BIGINT           NULL,
    [REF__ID]   BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([RAWMATID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_CODE]
    ON [dbo].[RAWMATERIAL]([CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[RAWMATERIAL]([PRJID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_RATEDATE]
    ON [dbo].[RAWMATERIAL]([RATE_DATE] ASC);

