CREATE TABLE [dbo].[SUPPLIER] (
    [SUPPLIERID]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION]          NVARCHAR (MAX) NULL,
    [GROUPCODE]            NVARCHAR (255) NULL,
    [GEKCODE]              NVARCHAR (255) NULL,
    [PERFORMANCE]          NVARCHAR (255) NULL,
    [URL]                  NVARCHAR (255) NULL,
    [CONTACTPERSON]        NVARCHAR (255) NULL,
    [PHONENUMBER]          NVARCHAR (255) NULL,
    [MOBILENUMBER]         NVARCHAR (255) NULL,
    [FAXNUMBER]            NVARCHAR (255) NULL,
    [EMAIL]                NVARCHAR (255) NULL,
    [CITY]                 NVARCHAR (255) NULL,
    [ADDRESS]              NVARCHAR (255) NULL,
    [NOTES]                NVARCHAR (255) NULL,
    [EDITORID]             NVARCHAR (255) NULL,
    [STATEPROVINCE]        NVARCHAR (255) NULL,
    [COUNTRY]              NVARCHAR (255) NULL,
    [DATABASEID]           BIGINT         NULL,
    [DATABASECREATIONDATE] BIGINT         NULL,
    [CREATEUSER]           NVARCHAR (255) NULL,
    [CREATEDATE]           DATETIME2 (7)  NULL,
    [RESCODE]              NVARCHAR (255) NULL,
    [LASTUPDATE]           DATETIME2 (7)  NULL,
    [TITLE]                NVARCHAR (255) NULL,
    [GEOLOC]               NVARCHAR (255) NULL,
    [EXTRACODE1]           NVARCHAR (255) NOT NULL,
    [EXTRACODE2]           NVARCHAR (255) NOT NULL,
    [EXTRACODE3]           NVARCHAR (255) NOT NULL,
    [EXTRACODE4]           NVARCHAR (255) NOT NULL,
    [EXTRACODE5]           NVARCHAR (255) NOT NULL,
    [EXTRACODE6]           NVARCHAR (255) NOT NULL,
    [EXTRACODE7]           NVARCHAR (255) NOT NULL,
    [EXTRACODE8]           NVARCHAR (255) NOT NULL,
    [EXTRACODE9]           NVARCHAR (255) NOT NULL,
    [EXTRACODE10]          NVARCHAR (255) NOT NULL,
    [PRJID]                BIGINT         NULL,
    [REF__ID]              BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([SUPPLIERID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_MDBID]
    ON [dbo].[SUPPLIER]([DATABASEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[SUPPLIER]([PRJID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_TITLE]
    ON [dbo].[SUPPLIER]([TITLE] ASC);

