CREATE TABLE [dbo].[XCHANGERATE] (
    [XCHANGERATEID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [FROM_CURRENCY] NVARCHAR (255)   NULL,
    [TO_CURRENCY]   NVARCHAR (255)   NULL,
    [RATE]          NUMERIC (30, 10) NULL,
    [RATE_DATE]     DATETIME2 (7)    NULL,
    [PRJID]         BIGINT           NULL,
    [REF__ID]       BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([XCHANGERATEID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_FROMCUR]
    ON [dbo].[XCHANGERATE]([FROM_CURRENCY] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[XCHANGERATE]([PRJID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_RATEDATE]
    ON [dbo].[XCHANGERATE]([RATE_DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_TOCUR]
    ON [dbo].[XCHANGERATE]([TO_CURRENCY] ASC);

