
namespace Models.local
{
	public class Assembly : BaseClass.Assembly, Interfaces.IAssembly
	{
		public Assembly Clone()
		{
			Assembly c = new Assembly();
			c.Assemblyid = Assemblyid;
			c.Lastupdate = Lastupdate;
			c.Virtual = Virtual;
			c.Virtualequ = Virtualequ;
			c.Virtualsub = Virtualsub;
			c.Virtuallab = Virtuallab;
			c.Virtualmat = Virtualmat;
			c.Virtualcon = Virtualcon;
			c.Overtype = Overtype;
			c.Actbased = Actbased;
			c.Description = Description;
			c.Unit = Unit;
			c.Productivity = Productivity;
			c.Publishedrate = Publishedrate;
			c.Publishedcode = Publishedcode;
			c.Rescode = Rescode;
			c.Groupcode = Groupcode;
			c.Gekcode = Gekcode;
			c.Project = Project;
			c.Accrights = Accrights;
			c.Keyw = Keyw;
			c.Title = Title;
			c.Notes = Notes;
			c.Editorid = Editorid;
			c.Currency = Currency;
			c.Stateprovince = Stateprovince;
			c.Rate = Rate;
			c.Labrate = Labrate;
			c.Matrate = Matrate;
			c.Subrate = Subrate;
			c.Conrate = Conrate;
			c.Equrate = Equrate;
			c.Umhours = Umhours;
			c.Uehours = Uehours;
			c.Qty = Qty;
			c.Accuracy = Accuracy;
			c.Createuser = Createuser;
			c.Createdate = Createdate;
			c.Bimtype = Bimtype;
			c.Bimmaterial = Bimmaterial;
			c.Country = Country;
			c.Custxt1 = Custxt1;
			c.Custxt2 = Custxt2;
			c.Custxt3 = Custxt3;
			c.Custxt4 = Custxt4;
			c.Custxt5 = Custxt5;
			c.Custxt6 = Custxt6;
			c.Custxt7 = Custxt7;
			c.Custxt8 = Custxt8;
			c.Custxt9 = Custxt9;
			c.Custxt10 = Custxt10;
			c.Custxt11 = Custxt11;
			c.Custxt12 = Custxt12;
			c.Custxt13 = Custxt13;
			c.Custxt14 = Custxt14;
			c.Custxt15 = Custxt15;
			c.Custxt16 = Custxt16;
			c.Custxt17 = Custxt17;
			c.Custxt18 = Custxt18;
			c.Custxt19 = Custxt19;
			c.Custxt20 = Custxt20;
			c.Custxt21 = Custxt21;
			c.Custxt22 = Custxt22;
			c.Custxt23 = Custxt23;
			c.Custxt24 = Custxt24;
			c.Custxt25 = Custxt25;
			c.Cusrate1 = Cusrate1;
			c.Cusrate2 = Cusrate2;
			c.Cusrate3 = Cusrate3;
			c.Cusrate4 = Cusrate4;
			c.Cusrate5 = Cusrate5;
			c.Cusrate6 = Cusrate6;
			c.Cusrate7 = Cusrate7;
			c.Cusrate8 = Cusrate8;
			c.Cusrate9 = Cusrate9;
			c.Cusrate10 = Cusrate10;
			c.Cusrate11 = Cusrate11;
			c.Cusrate12 = Cusrate12;
			c.Cusrate13 = Cusrate13;
			c.Cusrate14 = Cusrate14;
			c.Cusrate15 = Cusrate15;
			c.Cusrate16 = Cusrate16;
			c.Cusrate17 = Cusrate17;
			c.Cusrate18 = Cusrate18;
			c.Cusrate19 = Cusrate19;
			c.Cusrate20 = Cusrate20;
			c.Extracode1 = Extracode1;
			c.Extracode2 = Extracode2;
			c.Extracode3 = Extracode3;
			c.Extracode4 = Extracode4;
			c.Extracode5 = Extracode5;
			c.Extracode6 = Extracode6;
			c.Extracode7 = Extracode7;
			c.Extracode8 = Extracode8;
			c.Extracode9 = Extracode9;
			c.Extracode10 = Extracode10;
			c.Vars = Vars;
			c.Pugrcfactor = Pugrcfactor;
			c.Pugekfactor = Pugekfactor;
			c.Puex1factor = Puex1factor;
			c.Puex2factor = Puex2factor;
			c.Puex3factor = Puex3factor;
			c.Puex4factor = Puex4factor;
			c.Puex5factor = Puex5factor;
			c.Puex6factor = Puex6factor;
			c.Puex7factor = Puex7factor;
            c.AssemblyChildAssembly = AssemblyChildAssembly;
            c.AssemblyChildChild = AssemblyChildChild;
            c.AssemblyConsumable = AssemblyConsumable;
            c.AssemblyEquipment = AssemblyEquipment;
            c.AssemblyLabor = AssemblyLabor;
            c.AssemblyMaterial = AssemblyMaterial;
            c.AssemblySubcontractor = AssemblySubcontractor;

            return c;
		}
	}
}
