

CREATE PROCEDURE dbo.usp_dyn_boq_with_expanded_resources
@PrjId BIGINT,
@LineItemMaterials bit = 0 ,
@LineItemEquipment bit = 0 ,
@LineItemLabor bit = 0 ,
@LineItemSubcontructor bit = 0 ,
@LineItemConsumable bit = 0,
@Materials bit = 0 ,
@Equipment bit = 0 ,
@Labor bit = 0 ,
@Subcontructor bit = 0 ,
@Consumable bit = 0,
@SqlQuery nvarchar(max) ='' OUTPUT 
AS	
DECLARE @Dbname nvarchar(max)
DECLARE @MainPart NVARCHAR(MAX)
DECLARE @LineItemsUnion NVARCHAR(MAX)
DECLARE @LineItemMaterialPart NVARCHAR(MAX)
DECLARE @LineItemEquipmentPart NVARCHAR(MAX)
DECLARE @LineItemLaborPart NVARCHAR(MAX)
DECLARE @LineItemSubcontructorPart NVARCHAR(MAX)
DECLARE @LineItemConsumablePart NVARCHAR(MAX)

DECLARE @MaterialPart NVARCHAR(MAX)
DECLARE @EquipmentPart NVARCHAR(MAX)
DECLARE @LaborPart NVARCHAR(MAX)
DECLARE @SubcontructorPart NVARCHAR(MAX)
DECLARE @ConsumablePart NVARCHAR(MAX)

BEGIN

SELECT @Dbname = DBNAME
  FROM PROJECTURL
 WHERE PROJECTURLID = @PrjId;


SET @MainPart ='/*MainPart Start*/(SELECT 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.code'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCode, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.eps'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectEPS, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.currency.symbol'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCurrency, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.country'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCountry, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.budget'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientBudget,
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.contractor.signature'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectSignature, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.description'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDescription, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.mainsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectJobSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.unit'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectUnit, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.basementsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectBasementSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.floors'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDuration, 
o.BOQITEMID AS id,
o.BOQITEMID AS boqitemId,
o.CODE AS boqItemCode,
o.TITLE AS boqItemTitle,
o.EDITORID AS boqItemEditorId,
o.CREATEUSERID AS boqItemCreateUserId,
o.ESTIMATOR AS boqItemEstimator,
o.PAYMENT_DATE AS boqItemPaymentDate,
o.LAST_UPDATE AS boqItemLastUpdate,
o.CREATE_DATE AS boqItemCreateDate,
o.STATUS AS boqItemStatus,
o.ACCURACY AS boqItemAccuracy,
o.FLAG AS boqItemFlag,
o.LOCCOUNTRY AS boqItemLocalizationCountry,
o.LOCSTATE AS boqItemLocalizationState,
o.LOCFAC AS boqItemLocalizationFactor,
o.QUANTITY AS boqItemQuantity1,
o.SECQUANTITY AS boqItemQuantity2,
o.ESTQUANT AS  boqItemEstimatedQuantity,
o.MEASQUANT AS boqItemTakeoffQuantity,
o.QUANTLOSS AS boqItemQuantityLoss,
o.CNQT AS boqItemConditionQT,
o.HAS_PRODUCTIVITY AS boqItemHasProductivity,
o.ACTBASED AS boqItemActivityBased,
o.DURATION AS boqItemDuration,
o.PRODUCTIVITY AS boqItemProductivity,
o.PRODFACTOR AS boqItemProductivityFactor,
o.ADJPROD AS boqItemAdjustedProductivity,
o.MANHOURS AS boqItemTotalManHours,
o.UNITMHOURS AS boqItemUnitManHours,
o.MHOURSFACTOR AS boqItemUnitManHoursFactor,
o.AUNITMHOURS AS boqItemAdjustedUnitManHours,
o.EQUHOURS AS boqItemEquipmentHours,
o.UNIT AS boqItemUnit1,
o.SECOND_UNIT AS boqItemUnit2,
o.UNITS_DIV AS boqItemUnitDivider,
o.ASSRATE AS boqItemLineItemRate,
o.ASRT AS boqItemLineItemRT,
o.EQURATE AS boqItemEquipmentRate,
o.EQRT AS boqItemEquipmentRT,
o.SUBRATE AS boqItemSubcontractorRate,
o.SUBQUOTERATE AS boqItemSubcontractorQuotedRate,
o.SBRT AS boqItemSubcontractorRateRT,
o.LABRATE AS boqItemLaborRate,
o.LBRT AS boqItemLaborRT,
o.MATRATE AS boqItemMaterialRate,
o.MATQUOTERATE AS boqItemMaterialQuotedRate,
o.MART AS boqItemMaterialRateRT,
o.CONRATE AS boqItemConsumableRate,
o.CMRT AS boqItemConsumableRateRT,
o.FABRATE AS boqItemFabricationRate,
o.SHIPRATE AS boqItemShipmentRate,
o.RATE AS boqItemTotalRate1,
o.SECRATE AS boqItemTotalRate2,
o.PUBLISHEDRATE AS boqItemPublishedRate,
o.OFFRATE AS boqItemOfferedRate1,
o.OFFSECRATE AS boqItemOfferedRate2,
o.ASSCOST AS boqItemLineItemCost,
o.EQUCOST AS boqItemEquipmentCost,
o.SUBCOST AS boqItemSubcontractorCost,
o.LABCOST AS boqItemLaborCost,
o.MATCOST AS boqItemMaterialCost,
o.CONCOST AS boqItemConsumableCost,
o.FABCOST AS boqItemFabricationCost,
o.SHIPCOST AS boqItemShipmentCost,
o.MATRESCOST AS boqItemMaterialResourcesCost,
o.TOTALCOST AS boqItemTotalCost,
o.OFFPRICE AS boqItemOfferedPrice,
o.MARKUP AS boqItemMarkup,
o.ESCALATION AS boqItemEscalation,
o.CUSTXT1 AS boqItemCustomText1,
o.CUSTXT2 AS boqItemCustomText2,
o.CUSTXT3 AS boqItemCustomText3,
o.CUSTXT4 AS boqItemCustomText4,
o.CUSTXT5 AS boqItemCustomText5,
o.CUSTXT6 AS boqItemCustomText6,
o.CUSTXT7 AS boqItemCustomText7,
o.CUSTXT8 AS boqItemCustomText8,
o.CUSTXT9 AS boqItemCustomText9,
o.CUSTXT10 AS boqItemCustomText10,
o.CUSTXT11 AS boqItemCustomText11,
o.CUSTXT12 AS boqItemCustomText12,
o.CUSTXT13 AS boqItemCustomText13,
o.CUSTXT14 AS boqItemCustomText14,
o.CUSTXT15 AS boqItemCustomText15,
o.CUSTXT16 AS boqItemCustomText16,
o.CUSTXT17 AS boqItemCustomText17,
o.CUSTXT18 AS boqItemCustomText18,
o.CUSTXT19 AS boqItemCustomText19,
o.CUSTXT20 AS boqItemCustomText20,
o.CUSRATE1 AS boqItemCustomDecimal1,
o.CUSRATE2 AS boqItemCustomDecimal2,
o.CUSRATE3 AS boqItemCustomDecimal3,
o.CUSRATE4 AS boqItemCustomDecimal4,
o.CUSRATE5 AS boqItemCustomDecimal5,
o.CUSRATE6 AS boqItemCustomDecimal6,
o.CUSRATE7 AS boqItemCustomDecimal7,
o.CUSRATE8 AS boqItemCustomDecimal8,
o.CUSRATE9 AS boqItemCustomDecimal9,
o.CUSRATE10 AS boqItemCustomDecimal10,
o.CUSCUMRATE1 AS boqItemCustomCumDecimal1,
o.CUSCUMRATE2 AS boqItemCustomCumDecimal2,
o.CUSCUMRATE3 AS boqItemCustomCumDecimal3,
o.CUSCUMRATE4 AS boqItemCustomCumDecimal4,
o.CUSCUMRATE5 AS boqItemCustomCumDecimal5,
o.CUSPER1 AS boqItemCustomPercentange1,
o.CUSPER2 AS boqItemCustomPercentange2,
o.CUSPER3 AS boqItemCustomPercentange3, ' -- Literals have smaller max size so we need to break them
+ '
o.CUSPER4 AS boqItemCustomPercentange4,
o.CUSPER5 AS boqItemCustomPercentange5,
o.CUSPER6 AS boqItemCustomPercentange6,
o.CUSPER7 AS boqItemCustomPercentange7,
o.CUSPER8 AS boqItemCustomPercentange8,
o.CUSPER9 AS boqItemCustomPercentange9,
o.CUSPER10 AS boqItemCustomPercentange10,
o.PUBLISHEDITEMCODE AS boqItemPublishedItemCode,
o.PUBLISHEDREVISIONCODE AS boqItemPublishedRevisionCode,
o.SCHEDULED AS boqItemScheduled,
o.PUGRCFACTOR AS boqItemGroupCode1UnitFactor,
o.PUGEKFACTOR AS boqItemGroupCode2UnitFactor,
o.PUEX1FACTOR AS boqItemGroupCode3UnitFactor,
o.PUEX2FACTOR AS boqItemGroupCode4UnitFactor,
o.PUEX3FACTOR AS boqItemGroupCode5UnitFactor,
o.PUEX4FACTOR AS boqItemGroupCode6UnitFactor,
o.PUEX5FACTOR AS boqItemGroupCode7UnitFactor,
o.PUEX6FACTOR AS boqItemGroupCode8UnitFactor,
o.PUEX7FACTOR AS boqItemGroupCode9UnitFactor,
o.WBSCODE    AS boqItemWbsCode1,
o.WBS2CODE   AS boqItemWbsCode2,
o.LOCATION   AS boqItemLocation,
o.GROUPCODE  AS boqItemGroupCode1,
o.GEKCODE    AS boqItemGroupCode2,
o.EXTRACODE1 AS boqItemGroupCode3,
o.EXTRACODE2 AS boqItemGroupCode4,
o.EXTRACODE3 AS boqItemGroupCode5,
o.EXTRACODE4 AS boqItemGroupCode6,
o.EXTRACODE5 AS boqItemGroupCode7,
o.EXTRACODE6 AS boqItemGroupCode8,
o.EXTRACODE7 AS boqItemGroupCode9,
o.DESCRIPTION AS boqItemDescription,
o.NOTES AS boqItemNotes,
o.ASRT AS boqItemAssemblyRateType,
o.EQRT AS boqItemEquipmentRateType,
o.LBRT AS boqItemLaborRateType,
o.SBRT AS boqItemSubcontractorRateType,
o.MART AS boqItemMaterialRateType,
o.CMRT AS boqItemConsumableRateType,
o.CNQT AS boqItemTakeoffQuantityType,
NULL AS lineItemId,
NULL AS lineItemItemCode,
NULL AS lineItemTitle,
NULL AS lineItemDescription,
NULL AS lineItemActBased,
NULL AS lineItemProductivity,
NULL AS lineItemQuantityPerUnit,
NULL AS lineItemUnit,
NULL AS lineItemProject,
NULL AS lineItemCurrency,
NULL AS lineItemTotalRate,
NULL AS lineItemMaterialRate,
NULL AS lineItemLaborRate,
NULL AS lineItemSubcontractorRate,
NULL AS lineItemEquipmentRate,
NULL AS lineItemConsumablesRate,       
''Empty'' AS assignmentType,
NULL AS assignmentId,
NULL AS assignmentFactor1,
NULL AS assignmentFactor2,
NULL AS assignmentFactor3,
NULL AS assignmentQuantityPerUnit,
NULL AS assignmentLocalFactor,
NULL AS assignmentLocalCountry,
NULL AS assignmentLocalStateProvince,
NULL AS assignmentExchangeRate,
NULL AS assignmentTotalUnits,
NULL AS assignmentFinalRate,
NULL AS assignmentTotalCost,
NULL AS resourceId,
NULL AS resourceItemCode,
NULL AS resourceTitle,
NULL AS resourceDescription,
NULL AS resourceNotes,
NULL AS resourceRate,
NULL AS resourceCompany,
NULL AS resourceUnit,
NULL AS resourceCurrency,
NULL AS resourceCountry,
NULL AS resourceEditorId,
NULL AS resourceCreateUserId,
NULL AS resourceCreateDate,
NULL AS resourceLastUpdate,
NULL AS resourceGroupCode1,
NULL AS resourceGroupCode2,
NULL AS resourceGroupCode3,
NULL AS resourceGroupCode4,
NULL AS resourceGroupCode5,
NULL AS resourceGroupCode6,
NULL AS resourceGroupCode7,
NULL AS resourceGroupCode8,
NULL AS resourceGroupCode9
FROM '+@Dbname+'.dbo.BOQITEM AS o WHERE 
o.PRJID = ' + CAST(@PrjId as VARCHAR(MAX)) + '
AND NOT EXISTS (
    SELECT k.BOQITEMID FROM '+@Dbname+'.dbo.BOQITEM_MATERIAL AS k WHERE k.BOQITEMID = o.BOQITEMID
) AND NOT EXISTS (
    SELECT k.BOQITEMID FROM '+@Dbname+'.dbo.BOQITEM_SUBCONTRACTOR AS k WHERE k.BOQITEMID = o.BOQITEMID
) AND NOT EXISTS (
    SELECT k.BOQITEMID FROM '+@Dbname+'.dbo.BOQITEM_ASSEMBLY AS k WHERE k.BOQITEMID = o.BOQITEMID
) AND NOT EXISTS (
    SELECT k.BOQITEMID FROM '+@Dbname+'.dbo.BOQITEM_EQUIPMENT AS k WHERE k.BOQITEMID = o.BOQITEMID
) AND NOT EXISTS (
    SELECT k.BOQITEMID FROM '+@Dbname+'.dbo.BOQITEM_LABOR AS k WHERE k.BOQITEMID = o.BOQITEMID
) AND NOT EXISTS (
    SELECT k.BOQITEMID FROM '+@Dbname+'.dbo.BOQITEM_CONSUMABLE AS k WHERE k.BOQITEMID = o.BOQITEMID
))
/*MainPart End*/'

SET @LineItemsUnion = ' /*LineItemsUnion Start*/
UNION ALL
(SELECT
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.code'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCode, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.eps'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectEPS, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.currency.symbol'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCurrency, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.country'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCountry, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.budget'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientBudget,
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.contractor.signature'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectSignature, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.description'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDescription, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.mainsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectJobSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.unit'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectUnit, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.basementsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectBasementSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.floors'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDuration, 
a.BOQITEMASSEMBLYID+1000000000 AS id,
o.BOQITEMID AS boqitemId,
o.CODE AS boqItemCode,
o.TITLE AS boqItemTitle,
o.EDITORID AS boqItemEditorId,
o.CREATEUSERID AS boqItemCreateUserId,
o.ESTIMATOR AS boqItemEstimator,
o.PAYMENT_DATE AS boqItemPaymentDate,
o.LAST_UPDATE AS boqItemLastUpdate,
o.CREATE_DATE AS boqItemCreateDate,
o.STATUS AS boqItemStatus,
o.ACCURACY AS boqItemAccuracy,
o.FLAG AS boqItemFlag,
o.LOCCOUNTRY AS boqItemLocalizationCountry,
o.LOCSTATE AS boqItemLocalizationState,
o.LOCFAC AS boqItemLocalizationFactor,
o.QUANTITY AS boqItemQuantity1,
o.SECQUANTITY AS boqItemQuantity2,
o.ESTQUANT AS  boqItemEstimatedQuantity,
o.MEASQUANT AS boqItemTakeoffQuantity,
o.QUANTLOSS AS boqItemQuantityLoss,
o.CNQT AS boqItemConditionQT,
o.HAS_PRODUCTIVITY AS boqItemHasProductivity,
o.ACTBASED AS boqItemActivityBased,
o.DURATION AS boqItemDuration,
o.PRODUCTIVITY AS boqItemProductivity,
o.PRODFACTOR AS boqItemProductivityFactor,
o.ADJPROD AS boqItemAdjustedProductivity,
o.MANHOURS AS boqItemTotalManHours,
o.UNITMHOURS AS boqItemUnitManHours,
o.MHOURSFACTOR AS boqItemUnitManHoursFactor,
o.AUNITMHOURS AS boqItemAdjustedUnitManHours,
o.EQUHOURS AS boqItemEquipmentHours,
o.UNIT AS boqItemUnit1,
o.SECOND_UNIT AS boqItemUnit2,
o.UNITS_DIV AS boqItemUnitDivider,
o.ASSRATE AS boqItemLineItemRate,
o.ASRT AS boqItemLineItemRT,
o.EQURATE AS boqItemEquipmentRate,
o.EQRT AS boqItemEquipmentRT,
o.SUBRATE AS boqItemSubcontractorRate,
o.SUBQUOTERATE AS boqItemSubcontractorQuotedRate,
o.SBRT AS boqItemSubcontractorRateRT,
o.LABRATE AS boqItemLaborRate,
o.LBRT AS boqItemLaborRT,
o.MATRATE AS boqItemMaterialRate,
o.MATQUOTERATE AS boqItemMaterialQuotedRate,
o.MART AS boqItemMaterialRateRT,
o.CONRATE AS boqItemConsumableRate,
o.CMRT AS boqItemConsumableRateRT,
o.FABRATE AS boqItemFabricationRate,
o.SHIPRATE AS boqItemShipmentRate,
o.RATE AS boqItemTotalRate1,
o.SECRATE AS boqItemTotalRate2,
o.PUBLISHEDRATE AS boqItemPublishedRate,
o.OFFRATE AS boqItemOfferedRate1,
o.OFFSECRATE AS boqItemOfferedRate2,
o.ASSCOST AS boqItemLineItemCost,
o.EQUCOST AS boqItemEquipmentCost,
o.SUBCOST AS boqItemSubcontractorCost,
o.LABCOST AS boqItemLaborCost,
o.MATCOST AS boqItemMaterialCost,
o.CONCOST AS boqItemConsumableCost,
o.FABCOST AS boqItemFabricationCost,
o.SHIPCOST AS boqItemShipmentCost,
o.MATRESCOST AS boqItemMaterialResourcesCost,
o.TOTALCOST AS boqItemTotalCost,
o.OFFPRICE AS boqItemOfferedPrice,
o.MARKUP AS boqItemMarkup,
o.ESCALATION AS boqItemEscalation,
o.CUSTXT1 AS boqItemCustomText1,
o.CUSTXT2 AS boqItemCustomText2,
o.CUSTXT3 AS boqItemCustomText3,
o.CUSTXT4 AS boqItemCustomText4,
o.CUSTXT5 AS boqItemCustomText5,
o.CUSTXT6 AS boqItemCustomText6,
o.CUSTXT7 AS boqItemCustomText7,
o.CUSTXT8 AS boqItemCustomText8,
o.CUSTXT9 AS boqItemCustomText9,
o.CUSTXT10 AS boqItemCustomText10,
o.CUSTXT11 AS boqItemCustomText11,
o.CUSTXT12 AS boqItemCustomText12,
o.CUSTXT13 AS boqItemCustomText13,
o.CUSTXT14 AS boqItemCustomText14,
o.CUSTXT15 AS boqItemCustomText15,
o.CUSTXT16 AS boqItemCustomText16,
o.CUSTXT17 AS boqItemCustomText17,
o.CUSTXT18 AS boqItemCustomText18,
o.CUSTXT19 AS boqItemCustomText19,
o.CUSTXT20 AS boqItemCustomText20,
o.CUSRATE1 AS boqItemCustomDecimal1,
o.CUSRATE2 AS boqItemCustomDecimal2,
o.CUSRATE3 AS boqItemCustomDecimal3,
o.CUSRATE4 AS boqItemCustomDecimal4,
o.CUSRATE5 AS boqItemCustomDecimal5,
o.CUSRATE6 AS boqItemCustomDecimal6,
o.CUSRATE7 AS boqItemCustomDecimal7,
o.CUSRATE8 AS boqItemCustomDecimal8,
o.CUSRATE9 AS boqItemCustomDecimal9,
o.CUSRATE10 AS boqItemCustomDecimal10,
o.CUSCUMRATE1 AS boqItemCustomCumDecimal1,
o.CUSCUMRATE2 AS boqItemCustomCumDecimal2,
o.CUSCUMRATE3 AS boqItemCustomCumDecimal3,
o.CUSCUMRATE4 AS boqItemCustomCumDecimal4,
o.CUSCUMRATE5 AS boqItemCustomCumDecimal5,
o.CUSPER1 AS boqItemCustomPercentange1,
o.CUSPER2 AS boqItemCustomPercentange2,
o.CUSPER3 AS boqItemCustomPercentange3, ' -- Literals have smaller max size so we need to break them
+ '
o.CUSPER4 AS boqItemCustomPercentange4,
o.CUSPER5 AS boqItemCustomPercentange5,
o.CUSPER6 AS boqItemCustomPercentange6,
o.CUSPER7 AS boqItemCustomPercentange7,
o.CUSPER8 AS boqItemCustomPercentange8,
o.CUSPER9 AS boqItemCustomPercentange9,
o.CUSPER10 AS boqItemCustomPercentange10,
o.PUBLISHEDITEMCODE AS boqItemPublishedItemCode,
o.PUBLISHEDREVISIONCODE AS boqItemPublishedRevisionCode,
o.SCHEDULED AS boqItemScheduled,
o.PUGRCFACTOR AS boqItemGroupCode1UnitFactor,
o.PUGEKFACTOR AS boqItemGroupCode2UnitFactor,
o.PUEX1FACTOR AS boqItemGroupCode3UnitFactor,
o.PUEX2FACTOR AS boqItemGroupCode4UnitFactor,
o.PUEX3FACTOR AS boqItemGroupCode5UnitFactor,
o.PUEX4FACTOR AS boqItemGroupCode6UnitFactor,
o.PUEX5FACTOR AS boqItemGroupCode7UnitFactor,
o.PUEX6FACTOR AS boqItemGroupCode8UnitFactor,
o.PUEX7FACTOR AS boqItemGroupCode9UnitFactor,
o.WBSCODE    AS boqItemWbsCode1,
o.WBS2CODE   AS boqItemWbsCode2,
o.LOCATION   AS boqItemLocation,
o.GROUPCODE  AS boqItemGroupCode1,
o.GEKCODE    AS boqItemGroupCode2,
o.EXTRACODE1 AS boqItemGroupCode3,
o.EXTRACODE2 AS boqItemGroupCode4,
o.EXTRACODE3 AS boqItemGroupCode5,
o.EXTRACODE4 AS boqItemGroupCode6,
o.EXTRACODE5 AS boqItemGroupCode7,
o.EXTRACODE6 AS boqItemGroupCode8,
o.EXTRACODE7 AS boqItemGroupCode9,
o.DESCRIPTION AS boqItemDescription,
o.NOTES AS boqItemNotes,
o.ASRT AS boqItemAssemblyRateType,
o.EQRT AS boqItemEquipmentRateType,
o.LBRT AS boqItemLaborRateType,
o.SBRT AS boqItemSubcontractorRateType,
o.MART AS boqItemMaterialRateType,
o.CMRT AS boqItemConsumableRateType,
o.CNQT AS boqItemTakeoffQuantityType,
a.BOQITEMASSEMBLYID AS lineItemId,
r.lineItemItemCode AS lineItemItemCode,
r.lineItemTitle AS lineItemTitle,
r.lineItemDescription AS lineItemDescription,
r.lineItemActBased AS lineItemActBased,
r.lineItemProductivity AS lineItemProductivity,
a.QTYPUNIT AS lineItemQuantityPerUnit,
r.lineItemUnit AS lineItemUnit,
r.lineItemProject AS lineItemProject,
r.lineItemCurrency AS lineItemCurrency,
r.lineItemTotalRate AS lineItemTotalRate,
r.lineItemMaterialRate AS lineItemMaterialRate,
r.lineItemLaborRate AS lineItemLaborRate,
r.lineItemSubcontractorRate AS lineItemSubcontractorRate,
r.lineItemEquipmentRate AS lineItemEquipmentRate,
r.lineItemConsumablesRate AS lineItemConsumablesRate,       
r.assignmentType AS assignmentType,
a.BOQITEMASSEMBLYID AS assignmentId,
a.FACTOR1 AS assignmentFactor1,
a.FACTOR2 AS assignmentFactor2,
a.FACTOR3 AS assignmentFactor3,
a.QTYPUNIT AS assignmentQuantityPerUnit,
a.LOCALFACTOR AS assignmentLocalFactor,
a.LOCALCOUNTRY AS assignmentLocalCountry,
a.LOCALSTATE AS assignmentLocalStateProvince,
a.COSTCENTER AS assignmentExchangeRate,
a.TOTALUNITS AS assignmentTotalUnits,
(r.assignmentFinalRate*a.COSTCENTER*a.LOCALFACTOR*a.FACTOR1*a.FACTOR2*a.FACTOR3*a.QTYPUNIT) AS assignmentFinalRate,
o.QUANTITY*(r.assignmentFinalRate*a.COSTCENTER*a.LOCALFACTOR*a.FACTOR1*a.FACTOR2*a.FACTOR3*a.QTYPUNIT) AS assignmentTotalCost,
r.resourceId AS resourceId,
r.resourceItemCode AS resourceItemCode,
r.resourceTitle AS resourceTitle,
r.resourceDescription AS resourceDescription,
r.resourceNotes AS resourceNotes,
r.resourceRate AS resourceRate,
r.resourceCompany AS resourceCompany,
r.resourceUnit AS resourceUnit,
r.resourceCurrency AS resourceCurrency,
r.resourceCountry AS resourceCountry,
r.resourceEditorId AS resourceEditorId,
r.resourceCreateUserId AS resourceCreateUserId,
r.resourceCreateDate AS resourceCreateDate,
r.resourceLastUpdate AS resourceLastUpdate,
r.resourceGroupCode1 AS resourceGroupCode1,
r.resourceGroupCode2 AS resourceGroupCode2,
r.resourceGroupCode3 AS resourceGroupCode3,
r.resourceGroupCode4 AS resourceGroupCode4,
r.resourceGroupCode5 AS resourceGroupCode5,
r.resourceGroupCode6 AS resourceGroupCode6,
r.resourceGroupCode7 AS resourceGroupCode7,
r.resourceGroupCode8 AS resourceGroupCode8,
r.resourceGroupCode9 AS resourceGroupCode9
FROM '+@Dbname+'.dbo.BOQITEM_ASSEMBLY a
LEFT JOIN '+@Dbname+'.dbo.BOQITEM o ON o.BOQITEMID = a.BOQITEMID
LEFT JOIN 
(
SELECT lineItemId, lineItemItemCode, lineItemTitle, lineItemDescription, lineItemActBased, lineItemProductivity,
       lineItemUnit, lineItemProject, lineItemCurrency, lineItemTotalRate,
       lineItemMaterialRate, lineItemLaborRate, lineItemSubcontractorRate,
       lineItemEquipmentRate, lineItemConsumablesRate,
       assignmentType, assignmentId, assignmentFactor1,
       assignmentFactor2, assignmentFactor3, assignmentQuantityPerUnit, assignmentLocalFactor, assignmentLocalCountry, assignmentLocalStateProvince, assignmentExchangeRate,
       assignmentTotalUnits, assignmentFinalRate, assignmentTotalCost, resourceId, resourceItemCode, resourceTitle,
       resourceDescription, resourceNotes, resourceRate, resourceCompany, resourceUnit,
       resourceCurrency, resourceCountry, resourceEditorId, resourceCreateUserId, resourceCreateDate, resourceLastUpdate, resourceGroupCode1,
       resourceGroupCode2, resourceGroupCode3, resourceGroupCode4, resourceGroupCode5, resourceGroupCode6, resourceGroupCode7,
       resourceGroupCode8, resourceGroupCode9
    FROM (
   (SELECT  
       o.ASSEMBLYID AS lineResourceId,
       o.ASSEMBLYID AS lineItemId,
       o.RESCODE AS lineItemItemCode,	   
       o.TITLE AS lineItemTitle,
       o.DESCRIPTION AS lineItemDescription,   
       o.ACTBASED AS lineItemActBased,
       o.PRODUCTIVITY AS lineItemProductivity,
       o.UNIT AS lineItemUnit,
       o.PROJECT AS lineItemProject,
       o.CURRENCY AS lineItemCurrency,
       o.RATE AS lineItemTotalRate,
       o.MATRATE AS lineItemMaterialRate,
       o.LABRATE AS lineItemLaborRate,
       o.SUBRATE AS lineItemSubcontractorRate,
       o.EQURATE AS lineItemEquipmentRate,
       o.CONRATE AS lineItemConsumablesRate,       
       ''Empty'' AS assignmentType,
       NULL AS assignmentId,
       NULL AS assignmentFactor1,
       NULL AS assignmentFactor2,
       NULL AS assignmentFactor3,
       NULL AS assignmentQuantityPerUnit,
       NULL AS assignmentLocalFactor,
       NULL AS assignmentLocalCountry,
       NULL AS assignmentLocalStateProvince,
       NULL AS assignmentExchangeRate,
       NULL AS assignmentTotalUnits,
       NULL AS assignmentFinalRate,
       NULL AS assignmentTotalCost,
       NULL AS resourceId,
       NULL AS resourceItemCode,
       NULL AS resourceTitle,
       NULL AS resourceDescription,
       NULL AS resourceNotes,
       NULL AS resourceRate,
       NULL AS resourceCompany,
       NULL AS resourceUnit,
       NULL AS resourceCurrency,
       NULL AS resourceCountry,
       NULL AS resourceEditorId,
       NULL AS resourceCreateUserId,
       NULL AS resourceCreateDate,
       NULL AS resourceLastUpdate,
       NULL AS resourceGroupCode1,
       NULL AS resourceGroupCode2,
       NULL AS resourceGroupCode3,
       NULL AS resourceGroupCode4,
       NULL AS resourceGroupCode5,
       NULL AS resourceGroupCode6,
       NULL AS resourceGroupCode7,
       NULL AS resourceGroupCode8,
       NULL AS resourceGroupCode9       
   FROM '+@Dbname+'.dbo.ASSEMBLY AS o WHERE 
	  o.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + '
       AND NOT EXISTS (
           SELECT k.ASSEMBLYID FROM '+@Dbname+'.dbo.ASSEMBLY_MATERIAL AS k WHERE k.ASSEMBLYID = o.ASSEMBLYID
       ) AND NOT EXISTS (
           SELECT k.ASSEMBLYID FROM '+@Dbname+'.dbo.ASSEMBLY_SUBCONTRACTOR AS k WHERE k.ASSEMBLYID = o.ASSEMBLYID
       ) AND NOT EXISTS (
           SELECT k.ASSEMBLYID FROM '+@Dbname+'.dbo.ASSEMBLY_EQUIPMENT AS k WHERE k.ASSEMBLYID = o.ASSEMBLYID
       ) AND NOT EXISTS (
           SELECT k.ASSEMBLYID FROM '+@Dbname+'.dbo.ASSEMBLY_LABOR AS k WHERE k.ASSEMBLYID = o.ASSEMBLYID
       ) AND NOT EXISTS (
           SELECT k.ASSEMBLYID FROM '+@Dbname+'.dbo.ASSEMBLY_CONSUMABLE AS k WHERE k.ASSEMBLYID = o.ASSEMBLYID
       ) AND NOT EXISTS (
           SELECT k.ASSEMBLYID FROM '+@Dbname+'.dbo.ASSEMBLY_CHILD AS k WHERE k.ASSEMBLYID = o.ASSEMBLYID
       )
   )
   /* Inner Line Items */
   UNION ALL
   (SELECT  
       o.ASSEMBLYID+1000000000 AS lineResourceId,
       o.ASSEMBLYID AS lineItemId,
	   o.RESCODE AS lineItemItemCode,
       o.TITLE AS lineItemTitle,
       o.DESCRIPTION AS lineItemDescription, 
       o.ACTBASED AS lineItemActBased,  
       o.PRODUCTIVITY AS lineItemProductivity,
       o.UNIT AS lineItemUnit,
       o.PROJECT AS lineItemProject,
       o.CURRENCY AS lineItemCurrency,
       o.RATE AS lineItemTotalRate,
       o.MATRATE AS lineItemMaterialRate,
       o.LABRATE AS lineItemLaborRate,
       o.SUBRATE AS lineItemSubcontractorRate,
       o.EQURATE AS lineItemEquipmentRate,
       o.CONRATE AS lineItemConsumablesRate,
       ''InnerLineItem'' AS assignmentType,
       a.ASSEMBLYCHILDID AS assignmentId,
       a.FACTOR1 AS assignmentFactor1,
       a.FACTOR2 AS assignmentFactor2,
       a.DIVIDER AS assignmentFactor3,
       a.QTYPUNIT AS assignmentQuantityPerUnit,
       a.LOCALFACTOR AS assignmentLocalFactor,
       a.LOCALCOUNTRY AS assignmentLocalCountry,
       a.LOCALSTATE AS assignmentLocalStateProvince,
       a.EXCHANGERATE AS assignmentExchangeRate,
       NULL AS assignmentTotalUnits,
       a.FRATE AS assignmentFinalRate,
       NULL AS assignmentTotalCost,
       r.ASSEMBLYID AS resourceId,
       r.RESCODE AS resourceItemCode,	   
       r.TITLE AS resourceTitle,
       r.DESCRIPTION AS resourceDescription,
       r.NOTES AS resourceNotes,
       r.RATE AS resourceRate,
       NULL AS resourceCompany,
       r.UNIT AS resourceUnit,
       r.CURRENCY AS resourceCurrency,
       r.COUNTRY AS resourceCountry,
       r.EDITORID AS resourceEditorId,
       r.CREATEUSER AS resourceCreateUserId,
       r.CREATEDATE AS resourceCreateDate,
       r.LASTUPDATE AS resourceLastUpdate,
       r.GROUPCODE AS resourceGroupCode1,
       r.GEKCODE AS resourceGroupCode2,
       r.EXTRACODE1 AS resourceGroupCode3,
       r.EXTRACODE2 AS resourceGroupCode4,
       r.EXTRACODE3 AS resourceGroupCode5,
       r.EXTRACODE4 AS resourceGroupCode6,
       r.EXTRACODE5 AS resourceGroupCode7,
       r.EXTRACODE6 AS resourceGroupCode8,
       r.EXTRACODE7 AS resourceGroupCode9       
   FROM '+@Dbname+'.dbo.ASSEMBLY_CHILD a
       LEFT JOIN '+@Dbname+'.dbo.ASSEMBLY o ON o.ASSEMBLYID = a.ASSEMBLYID
       LEFT JOIN '+@Dbname+'.dbo.ASSEMBLY r ON r.ASSEMBLYID = a.CHILDID
	  WHERE a.PRJID = ' + CAST(@PrjId as VARCHAR(MAX)) + '
   ) 
    /*LineItemsUnion End*/'

IF @LineItemMaterials = 1
SET @LineItemMaterialPart = '/* LineItemMaterials Start*/
   UNION ALL
   (SELECT  
       o.ASSEMBLYID+2000000000 AS lineResourceId,
       o.ASSEMBLYID AS lineItemId,
	   o.RESCODE AS lineItemItemCode,
       o.TITLE AS lineItemTitle,
       o.DESCRIPTION AS lineItemDescription, 
       o.ACTBASED AS lineItemActBased,  
       o.PRODUCTIVITY AS lineItemProductivity,
       o.UNIT AS lineItemUnit,
       o.PROJECT AS lineItemProject,
       o.CURRENCY AS lineItemCurrency,
       o.RATE AS lineItemTotalRate,
       o.MATRATE AS lineItemMaterialRate,
       o.LABRATE AS lineItemLaborRate,
       o.SUBRATE AS lineItemSubcontractorRate,
       o.EQURATE AS lineItemEquipmentRate,
       o.CONRATE AS lineItemConsumablesRate,
       ''Material'' AS assignmentType,
       a.ASSEMBLYMATERIALID AS assignmentId,
       a.FACTOR1 AS assignmentFactor1,
       a.FACTOR2 AS assignmentFactor2,
       a.DIVIDER AS assignmentFactor3,
       a.QTYPUNIT AS assignmentQuantityPerUnit,
       a.LOCALFACTOR AS assignmentLocalFactor,
       a.LOCALCOUNTRY AS assignmentLocalCountry,
       a.LOCALSTATE AS assignmentLocalStateProvince,
       a.EXCHANGERATE AS assignmentExchangeRate,
       NULL AS assignmentTotalUnits,
       a.FRATE AS assignmentFinalRate,
       NULL AS assignmentTotalCost,
       r.MATERIALID AS resourceId,
       r.RESCODE AS resourceItemCode,	   	   
       r.TITLE AS resourceTitle,
       r.DESCRIPTION AS resourceDescription,
       r.NOTES AS resourceNotes,
       r.TOTALRATE AS resourceRate,
       r.SUPPLIERNAME AS resourceCompany,
       r.UNIT AS resourceUnit,
       r.CURRENCY AS resourceCurrency,
       r.COUNTRY AS resourceCountry,
       r.EDITORID AS resourceEditorId,
       r.CREATEUSER AS resourceCreateUserId,
       r.CREATEDATE AS resourceCreateDate,
       r.LASTUPDATE AS resourceLastUpdate,
       r.GROUPCODE AS resourceGroupCode1,
       r.GEKCODE AS resourceGroupCode2,
       r.EXTRACODE1 AS resourceGroupCode3,
       r.EXTRACODE2 AS resourceGroupCode4,
       r.EXTRACODE3 AS resourceGroupCode5,
       r.EXTRACODE4 AS resourceGroupCode6,
       r.EXTRACODE5 AS resourceGroupCode7,
       r.EXTRACODE6 AS resourceGroupCode8,
       r.EXTRACODE7 AS resourceGroupCode9       
   FROM '+@Dbname+'.dbo.ASSEMBLY_MATERIAL a
       LEFT JOIN '+@Dbname+'.dbo.ASSEMBLY o ON o.ASSEMBLYID = a.ASSEMBLYID
       LEFT JOIN '+@Dbname+'.dbo.MATERIAL r ON r.MATERIALID = a.MATERIALID
   )/*LineItemMaterials End*/'
ELSE SET @LineItemMaterialPart = ''

IF @LineItemEquipment = 1
SET @LineItemEquipmentPart = '/*LineItemEquipment Start*/
   UNION ALL
   (SELECT  
       o.ASSEMBLYID+3000000000 AS lineResourceId,
       o.ASSEMBLYID AS lineItemId,
	   o.RESCODE AS lineItemItemCode,
       o.TITLE AS lineItemTitle,
       o.DESCRIPTION AS lineItemDescription,
       o.ACTBASED AS lineItemActBased,   
       o.PRODUCTIVITY AS lineItemProductivity,    
       o.UNIT AS lineItemUnit,
       o.PROJECT AS lineItemProject,
       o.CURRENCY AS lineItemCurrency,
       o.RATE AS lineItemTotalRate,
       o.MATRATE AS lineItemMaterialRate,
       o.LABRATE AS lineItemLaborRate,
       o.SUBRATE AS lineItemSubcontractorRate,
       o.EQURATE AS lineItemEquipmentRate,
       o.CONRATE AS lineItemConsumablesRate,
       ''Equipment'' AS assignmentType,
       a.ASSEMBLYEQUIPMENTID AS assignmentId,
       a.FACTOR1 AS assignmentFactor1,
       a.FACTOR2 AS assignmentFactor2,
       a.FACTOR3 AS assignmentFactor3,
       a.QTYPUNIT AS assignmentQuantityPerUnit,
       a.LOCALFACTOR AS assignmentLocalFactor,
       a.LOCALCOUNTRY AS assignmentLocalCountry,
       a.LOCALSTATE AS assignmentLocalStateProvince,
       a.EXCHANGERATE AS assignmentExchangeRate,
       NULL AS assignmentTotalUnits,
       a.FRATE AS assignmentFinalRate,
       NULL AS assignmentTotalCost,
       r.EQUIPMENTID AS resourceId,
       r.RESCODE AS resourceItemCode,	   	   
       r.TITLE AS resourceTitle,
       r.DESCRIPTION AS resourceDescription,
       r.NOTES AS resourceNotes,
       r.TOTALRATE AS resourceRate,
       NULL AS resourceCompany,
       r.UNIT AS resourceUnit,
       r.CURRENCY AS resourceCurrency,
       r.COUNTRY AS resourceCountry,
       r.EDITORID AS resourceEditorId,
       r.CREATEUSER AS resourceCreateUserId,
       r.CREATEDATE AS resourceCreateDate,
       r.LASTUPDATE AS resourceLastUpdate,
       r.GROUPCODE AS resourceGroupCode1,
       r.GEKCODE AS resourceGroupCode2,
       r.EXTRACODE1 AS resourceGroupCode3,
       r.EXTRACODE2 AS resourceGroupCode4,
       r.EXTRACODE3 AS resourceGroupCode5,
       r.EXTRACODE4 AS resourceGroupCode6,
       r.EXTRACODE5 AS resourceGroupCode7,
       r.EXTRACODE6 AS resourceGroupCode8,
       r.EXTRACODE7 AS resourceGroupCode9       
   FROM '+@Dbname+'.dbo.ASSEMBLY_EQUIPMENT a
       LEFT JOIN '+@Dbname+'.dbo.ASSEMBLY o ON o.ASSEMBLYID = a.ASSEMBLYID
       LEFT JOIN '+@Dbname+'.dbo.EQUIPMENT r ON r.EQUIPMENTID = a.EQUIPMENTID
   )/*LineItemEquipment End*/'
ELSE SET @LineItemEquipmentPart = ''

IF @LineItemLabor = 1 
SET @LineItemLaborPart = '   /*LineItemLaborPart Start*/
   UNION ALL
   (SELECT  
       o.ASSEMBLYID+4000000000 AS lineResourceId,
       o.ASSEMBLYID AS lineItemId,
	   o.RESCODE AS lineItemItemCode,
       o.TITLE AS lineItemTitle,
       o.DESCRIPTION AS lineItemDescription, 
       o.ACTBASED AS lineItemActBased,  
       o.PRODUCTIVITY AS lineItemProductivity,   
       o.UNIT AS lineItemUnit,
       o.PROJECT AS lineItemProject,
       o.CURRENCY AS lineItemCurrency,
       o.RATE AS lineItemTotalRate,
       o.MATRATE AS lineItemMaterialRate,
       o.LABRATE AS lineItemLaborRate,
       o.SUBRATE AS lineItemSubcontractorRate,
       o.EQURATE AS lineItemEquipmentRate,
       o.CONRATE AS lineItemConsumablesRate,       
       ''Labor'' AS assignmentType,
       a.ASSEMBLYLABORID AS assignmentId,
       a.FACTOR1 AS assignmentFactor1,
       a.FACTOR2 AS assignmentFactor2,
       a.FACTOR3 AS assignmentFactor3,
       a.QTYPUNIT AS assignmentQuantityPerUnit,
       a.LOCALFACTOR AS assignmentLocalFactor,
       a.LOCALCOUNTRY AS assignmentLocalCountry,
       a.LOCALSTATE AS assignmentLocalStateProvince,
       a.EXCHANGERATE AS assignmentExchangeRate,
       NULL AS assignmentTotalUnits,
       a.FRATE AS assignmentFinalRate,
       NULL AS assignmentTotalCost,
       r.LABORID AS resourceId,
       r.RESCODE AS resourceItemCode,	   	   
       r.TITLE AS resourceTitle,
       r.DESCRIPTION AS resourceDescription,
       r.NOTES AS resourceNotes,
       r.TOTALRATE AS resourceRate,
       r.CONTACTPERSON AS resourceCompany,
       r.UNIT AS resourceUnit,
       r.CURRENCY AS resourceCurrency,
       r.COUNTRY AS resourceCountry,
       r.EDITORID AS resourceEditorId,
       r.CREATEUSER AS resourceCreateUserId,
       r.CREATEDATE AS resourceCreateDate,
       r.LASTUPDATE AS resourceLastUpdate,
       r.GROUPCODE AS resourceGroupCode1,
       r.GEKCODE AS resourceGroupCode2,
       r.EXTRACODE1 AS resourceGroupCode3,
       r.EXTRACODE2 AS resourceGroupCode4,
       r.EXTRACODE3 AS resourceGroupCode5,
       r.EXTRACODE4 AS resourceGroupCode6,
       r.EXTRACODE5 AS resourceGroupCode7,
       r.EXTRACODE6 AS resourceGroupCode8,
       r.EXTRACODE7 AS resourceGroupCode9       
   FROM '+@Dbname+'.dbo.ASSEMBLY_LABOR a
       LEFT JOIN '+@Dbname+'.dbo.ASSEMBLY o ON o.ASSEMBLYID = a.ASSEMBLYID
       LEFT JOIN '+@Dbname+'.dbo.LABOR r ON r.LABORID = a.LABORID
   )
/*LineItemLaborPart End*/'  
ELSE 
SET @LineItemLaborPart = ''
IF @LineItemSubcontructor = 1 
SET @LineItemSubcontructorPart = '/*LineItemSubcontructorPart Start*/
   UNION ALL
   (SELECT  
       o.ASSEMBLYID+5000000000 AS lineResourceId,
       o.ASSEMBLYID AS lineItemId,
	   o.RESCODE AS lineItemItemCode,
       o.TITLE AS lineItemTitle,
       o.DESCRIPTION AS lineItemDescription,   
       o.ACTBASED AS lineItemActBased,
       o.PRODUCTIVITY AS lineItemProductivity,
       o.UNIT AS lineItemUnit,
       o.PROJECT AS lineItemProject,
       o.CURRENCY AS lineItemCurrency,
       o.RATE AS lineItemTotalRate,
       o.MATRATE AS lineItemMaterialRate,
       o.LABRATE AS lineItemLaborRate,
       o.SUBRATE AS lineItemSubcontractorRate,
       o.EQURATE AS lineItemEquipmentRate,
       o.CONRATE AS lineItemConsumablesRate,              
       ''Subcontractor'' AS assignmentType,
       a.ASSEMBLYSUBCONTRACTORID AS assignmentId,
       a.FACTOR1 AS assignmentFactor1,
       a.FACTOR2 AS assignmentFactor2,
       a.FACTOR3 AS assignmentFactor3,
       a.QTYPUNIT AS assignmentQuantityPerUnit,
       a.LOCALFACTOR AS assignmentLocalFactor,
       a.LOCALCOUNTRY AS assignmentLocalCountry,
       a.LOCALSTATE AS assignmentLocalStateProvince,
       a.EXCHANGERATE AS assignmentExchangeRate,
       NULL AS assignmentTotalUnits,
       a.FRATE AS assignmentFinalRate,
       NULL AS assignmentTotalCost,
       r.SUBCONTRACTORID AS resourceId,
       r.RESCODE AS resourceItemCode,	   	   
       r.TITLE AS resourceTitle,
       r.DESCRIPTION AS resourceDescription,
       r.NOTES AS resourceNotes,
       r.TOTALRATE AS resourceRate,
       r.COMPANY AS resourceCompany,
       r.UNIT AS resourceUnit,
       r.CURRENCY AS resourceCurrency,
       r.COUNTRY AS resourceCountry,
       r.EDITORID AS resourceEditorId,
       r.CREATEUSER AS resourceCreateUserId,
       r.CREATEDATE AS resourceCreateDate,
       r.LASTUPDATE AS resourceLastUpdate,
       r.GROUPCODE AS resourceGroupCode1,
       r.GEKCODE AS resourceGroupCode2,
       r.EXTRACODE1 AS resourceGroupCode3,
       r.EXTRACODE2 AS resourceGroupCode4,
       r.EXTRACODE3 AS resourceGroupCode5,
       r.EXTRACODE4 AS resourceGroupCode6,
       r.EXTRACODE5 AS resourceGroupCode7,
       r.EXTRACODE6 AS resourceGroupCode8,
       r.EXTRACODE7 AS resourceGroupCode9       
   FROM '+@Dbname+'.dbo.ASSEMBLY_SUBCONTRACTOR a
       LEFT JOIN '+@Dbname+'.dbo.ASSEMBLY o ON o.ASSEMBLYID = a.ASSEMBLYID
       LEFT JOIN '+@Dbname+'.dbo.SUBCONTRACTOR r ON r.SUBCONTRACTORID = a.SUBCONTRACTORID
   )/*LineItemSubcontructorPart End*/'
ELSE SET @LineItemSubcontructorPart= '' 

IF @LineItemConsumable =1 
SET @LineItemConsumablePart = ' /*LineItemConsumablePart Start*/
   UNION ALL
   (SELECT  
       o.ASSEMBLYID+6000000000 AS lineResourceId,
       o.ASSEMBLYID AS lineItemId,
	   o.RESCODE AS lineItemItemCode,
       o.TITLE AS lineItemTitle,
       o.DESCRIPTION AS lineItemDescription,   
       o.ACTBASED AS lineItemActBased,
       o.PRODUCTIVITY AS lineItemProductivity,
       o.UNIT AS lineItemUnit,
       o.PROJECT AS lineItemProject,
       o.CURRENCY AS lineItemCurrency,
       o.RATE AS lineItemTotalRate,
       o.MATRATE AS lineItemMaterialRate,
       o.LABRATE AS lineItemLaborRate,
       o.SUBRATE AS lineItemSubcontractorRate,
       o.EQURATE AS lineItemEquipmentRate,
       o.CONRATE AS lineItemConsumablesRate,       
       ''Consumable'' AS assignmentType,
       a.ASSEMBLYCONSUMABLEID AS assignmentId,
       a.FACTOR1 AS assignmentFactor1,
       a.FACTOR2 AS assignmentFactor2,
       a.DIVIDER AS assignmentFactor3,
       a.QTYPUNIT AS assignmentQuantityPerUnit,
       a.LOCALFACTOR AS assignmentLocalFactor,
       a.LOCALCOUNTRY AS assignmentLocalCountry,
       a.LOCALSTATE AS assignmentLocalStateProvince,
       a.EXCHANGERATE AS assignmentExchangeRate,
       NULL AS assignmentTotalUnits,
       a.FRATE AS assignmentFinalRate,
       NULL AS assignmentTotalCost,
       r.CONSUMABLEID AS resourceId,
       r.RESCODE AS resourceItemCode,	   	   
       r.TITLE AS resourceTitle,
       r.DESCRIPTION AS resourceDescription,
       r.NOTES AS resourceNotes,
       r.RATE AS resourceRate,
       NULL AS resourceCompany,
       r.UNIT AS resourceUnit,
       r.CURRENCY AS resourceCurrency,
       r.COUNTRY AS resourceCountry,
       r.EDITORID AS resourceEditorId,
       r.CREATEUSER AS resourceCreateUserId,
       r.CREATEDATE AS resourceCreateDate,
       r.LASTUPDATE AS resourceLastUpdate,
       r.GROUPCODE AS resourceGroupCode1,
       r.GEKCODE AS resourceGroupCode2,
       r.EXTRACODE1 AS resourceGroupCode3,
       r.EXTRACODE2 AS resourceGroupCode4,
       r.EXTRACODE3 AS resourceGroupCode5,
       r.EXTRACODE4 AS resourceGroupCode6,
       r.EXTRACODE5 AS resourceGroupCode7,
       r.EXTRACODE6 AS resourceGroupCode8,
       r.EXTRACODE7 AS resourceGroupCode9       
   FROM '+@Dbname+'.dbo.ASSEMBLY_CONSUMABLE a
       LEFT JOIN '+@Dbname+'.dbo.ASSEMBLY o ON o.ASSEMBLYID = a.ASSEMBLYID
       LEFT JOIN '+@Dbname+'.dbo.CONSUMABLE r ON r.CONSUMABLEID = a.CONSUMABLEID
   )/*LineItemConsumablePart End*/' 
ELSE SET @LineItemConsumablePart = '' 

IF @Materials = 1 
SET @MaterialPart = '/*@MaterialPart Start*/
UNION ALL
(SELECT
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.code'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCode, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.eps'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectEPS, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.currency.symbol'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCurrency, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.country'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCountry, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.budget'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientBudget,
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.contractor.signature'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectSignature, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.description'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDescription, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.mainsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectJobSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.unit'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectUnit, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.basementsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectBasementSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.floors'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDuration, 
a.BOQITEMMATERIALID+2000000000 AS id,
o.BOQITEMID AS boqitemId,
o.CODE AS boqItemCode,
o.TITLE AS boqItemTitle,
o.EDITORID AS boqItemEditorId,
o.CREATEUSERID AS boqItemCreateUserId,
o.ESTIMATOR AS boqItemEstimator,
o.PAYMENT_DATE AS boqItemPaymentDate,
o.LAST_UPDATE AS boqItemLastUpdate,
o.CREATE_DATE AS boqItemCreateDate,
o.STATUS AS boqItemStatus,
o.ACCURACY AS boqItemAccuracy,
o.FLAG AS boqItemFlag,
o.LOCCOUNTRY AS boqItemLocalizationCountry,
o.LOCSTATE AS boqItemLocalizationState,
o.LOCFAC AS boqItemLocalizationFactor,
o.QUANTITY AS boqItemQuantity1,
o.SECQUANTITY AS boqItemQuantity2,
o.ESTQUANT AS  boqItemEstimatedQuantity,
o.MEASQUANT AS boqItemTakeoffQuantity,
o.QUANTLOSS AS boqItemQuantityLoss,
o.CNQT AS boqItemConditionQT,
o.HAS_PRODUCTIVITY AS boqItemHasProductivity,
o.ACTBASED AS boqItemActivityBased,
o.DURATION AS boqItemDuration,
o.PRODUCTIVITY AS boqItemProductivity,
o.PRODFACTOR AS boqItemProductivityFactor,
o.ADJPROD AS boqItemAdjustedProductivity,
o.MANHOURS AS boqItemTotalManHours,
o.UNITMHOURS AS boqItemUnitManHours,
o.MHOURSFACTOR AS boqItemUnitManHoursFactor,
o.AUNITMHOURS AS boqItemAdjustedUnitManHours,
o.EQUHOURS AS boqItemEquipmentHours,
o.UNIT AS boqItemUnit1,
o.SECOND_UNIT AS boqItemUnit2,
o.UNITS_DIV AS boqItemUnitDivider,
o.ASSRATE AS boqItemLineItemRate,
o.ASRT AS boqItemLineItemRT,
o.EQURATE AS boqItemEquipmentRate,
o.EQRT AS boqItemEquipmentRT,
o.SUBRATE AS boqItemSubcontractorRate,
o.SUBQUOTERATE AS boqItemSubcontractorQuotedRate,
o.SBRT AS boqItemSubcontractorRateRT,
o.LABRATE AS boqItemLaborRate,
o.LBRT AS boqItemLaborRT,
o.MATRATE AS boqItemMaterialRate,
o.MATQUOTERATE AS boqItemMaterialQuotedRate,
o.MART AS boqItemMaterialRateRT,
o.CONRATE AS boqItemConsumableRate,
o.CMRT AS boqItemConsumableRateRT,
o.FABRATE AS boqItemFabricationRate,
o.SHIPRATE AS boqItemShipmentRate,
o.RATE AS boqItemTotalRate1,
o.SECRATE AS boqItemTotalRate2,
o.PUBLISHEDRATE AS boqItemPublishedRate,
o.OFFRATE AS boqItemOfferedRate1,
o.OFFSECRATE AS boqItemOfferedRate2,
o.ASSCOST AS boqItemLineItemCost,
o.EQUCOST AS boqItemEquipmentCost,
o.SUBCOST AS boqItemSubcontractorCost,
o.LABCOST AS boqItemLaborCost,
o.MATCOST AS boqItemMaterialCost,
o.CONCOST AS boqItemConsumableCost,
o.FABCOST AS boqItemFabricationCost,
o.SHIPCOST AS boqItemShipmentCost,
o.MATRESCOST AS boqItemMaterialResourcesCost,
o.TOTALCOST AS boqItemTotalCost,
o.OFFPRICE AS boqItemOfferedPrice,
o.MARKUP AS boqItemMarkup,
o.ESCALATION AS boqItemEscalation,
o.CUSTXT1 AS boqItemCustomText1,
o.CUSTXT2 AS boqItemCustomText2,
o.CUSTXT3 AS boqItemCustomText3,
o.CUSTXT4 AS boqItemCustomText4,
o.CUSTXT5 AS boqItemCustomText5,
o.CUSTXT6 AS boqItemCustomText6,
o.CUSTXT7 AS boqItemCustomText7,
o.CUSTXT8 AS boqItemCustomText8,
o.CUSTXT9 AS boqItemCustomText9,
o.CUSTXT10 AS boqItemCustomText10,
o.CUSTXT11 AS boqItemCustomText11,
o.CUSTXT12 AS boqItemCustomText12,
o.CUSTXT13 AS boqItemCustomText13,
o.CUSTXT14 AS boqItemCustomText14,
o.CUSTXT15 AS boqItemCustomText15,
o.CUSTXT16 AS boqItemCustomText16,
o.CUSTXT17 AS boqItemCustomText17,
o.CUSTXT18 AS boqItemCustomText18,
o.CUSTXT19 AS boqItemCustomText19,
o.CUSTXT20 AS boqItemCustomText20,
o.CUSRATE1 AS boqItemCustomDecimal1,
o.CUSRATE2 AS boqItemCustomDecimal2,
o.CUSRATE3 AS boqItemCustomDecimal3,
o.CUSRATE4 AS boqItemCustomDecimal4,
o.CUSRATE5 AS boqItemCustomDecimal5,
o.CUSRATE6 AS boqItemCustomDecimal6,
o.CUSRATE7 AS boqItemCustomDecimal7,
o.CUSRATE8 AS boqItemCustomDecimal8,
o.CUSRATE9 AS boqItemCustomDecimal9,
o.CUSRATE10 AS boqItemCustomDecimal10,
o.CUSCUMRATE1 AS boqItemCustomCumDecimal1,
o.CUSCUMRATE2 AS boqItemCustomCumDecimal2,
o.CUSCUMRATE3 AS boqItemCustomCumDecimal3,
o.CUSCUMRATE4 AS boqItemCustomCumDecimal4,
o.CUSCUMRATE5 AS boqItemCustomCumDecimal5,
o.CUSPER1 AS boqItemCustomPercentange1,
o.CUSPER2 AS boqItemCustomPercentange2,
o.CUSPER3 AS boqItemCustomPercentange3, ' -- Literals have smaller max size so we need to break them
+ '
o.CUSPER4 AS boqItemCustomPercentange4,
o.CUSPER5 AS boqItemCustomPercentange5,
o.CUSPER6 AS boqItemCustomPercentange6,
o.CUSPER7 AS boqItemCustomPercentange7,
o.CUSPER8 AS boqItemCustomPercentange8,
o.CUSPER9 AS boqItemCustomPercentange9,
o.CUSPER10 AS boqItemCustomPercentange10,
o.PUBLISHEDITEMCODE AS boqItemPublishedItemCode,
o.PUBLISHEDREVISIONCODE AS boqItemPublishedRevisionCode,
o.SCHEDULED AS boqItemScheduled,
o.PUGRCFACTOR AS boqItemGroupCode1UnitFactor,
o.PUGEKFACTOR AS boqItemGroupCode2UnitFactor,
o.PUEX1FACTOR AS boqItemGroupCode3UnitFactor,
o.PUEX2FACTOR AS boqItemGroupCode4UnitFactor,
o.PUEX3FACTOR AS boqItemGroupCode5UnitFactor,
o.PUEX4FACTOR AS boqItemGroupCode6UnitFactor,
o.PUEX5FACTOR AS boqItemGroupCode7UnitFactor,
o.PUEX6FACTOR AS boqItemGroupCode8UnitFactor,
o.PUEX7FACTOR AS boqItemGroupCode9UnitFactor,
o.WBSCODE    AS boqItemWbsCode1,
o.WBS2CODE   AS boqItemWbsCode2,
o.LOCATION   AS boqItemLocation,
o.GROUPCODE  AS boqItemGroupCode1,
o.GEKCODE    AS boqItemGroupCode2,
o.EXTRACODE1 AS boqItemGroupCode3,
o.EXTRACODE2 AS boqItemGroupCode4,
o.EXTRACODE3 AS boqItemGroupCode5,
o.EXTRACODE4 AS boqItemGroupCode6,
o.EXTRACODE5 AS boqItemGroupCode7,
o.EXTRACODE6 AS boqItemGroupCode8,
o.EXTRACODE7 AS boqItemGroupCode9,
o.DESCRIPTION AS boqItemDescription,
o.NOTES AS boqItemNotes,
o.ASRT AS boqItemAssemblyRateType,
o.EQRT AS boqItemEquipmentRateType,
o.LBRT AS boqItemLaborRateType,
o.SBRT AS boqItemSubcontractorRateType,
o.MART AS boqItemMaterialRateType,
o.CMRT AS boqItemConsumableRateType,
o.CNQT AS boqItemTakeoffQuantityType,
NULL AS lineItemId,
NULL AS lineItemItemCode,
NULL AS lineItemTitle,
NULL AS lineItemDescription,
NULL AS lineItemActBased,
NULL AS lineItemProductivity,
NULL AS lineItemQuantityPerUnit,
NULL AS lineItemUnit,
NULL AS lineItemProject,
NULL AS lineItemCurrency,
NULL AS lineItemTotalRate,
NULL AS lineItemMaterialRate,
NULL AS lineItemLaborRate,
NULL AS lineItemSubcontractorRate,
NULL AS lineItemEquipmentRate,
NULL AS lineItemConsumablesRate,       
''Material'' AS assignmentType,
a.BOQITEMMATERIALID AS assignmentId,
a.FACTOR1 AS assignmentFactor1,
a.FACTOR2 AS assignmentFactor2,
a.DIVIDER AS assignmentFactor3,
a.QTYPUNIT AS assignmentQuantityPerUnit,
a.LOCALFACTOR AS assignmentLocalFactor,
a.LOCALCOUNTRY AS assignmentLocalCountry,
a.LOCALSTATE AS assignmentLocalStateProvince,
a.COSTCENTER AS assignmentExchangeRate,
a.TOTALUNITS AS assignmentTotalUnits,
a.FRATE AS assignmentFinalRate,
a.TOTALCOST AS assignmentTotalCost,
/*(r.TOTALRATE*a.COSTCENTER*a.LOCALFACTOR*a.FACTOR1*a.FACTOR2*a.DIVIDER*a.QTYPUNIT) AS assignmentFinalRate,
(a.TOTALUNITS*r.TOTALRATE*a.COSTCENTER*a.LOCALFACTOR*a.FACTOR1*a.FACTOR2*a.DIVIDER*a.QTYPUNIT) AS assignmentTotalCost,*/
r.MATERIALID AS resourceId,
r.RESCODE AS resourceItemCode,	   
r.TITLE AS resourceTitle,
r.DESCRIPTION AS resourceDescription,
r.NOTES AS resourceNotes,
r.TOTALRATE AS resourceRate,
r.SUPPLIERNAME AS resourceCompany,
r.UNIT AS resourceUnit,
r.CURRENCY AS resourceCurrency,
r.COUNTRY AS resourceCountry,
r.EDITORID AS resourceEditorId,
r.CREATEUSER AS resourceCreateUserId,
r.CREATEDATE AS resourceCreateDate,
r.LASTUPDATE AS resourceLastUpdate,
r.GROUPCODE AS resourceGroupCode1,
r.GEKCODE AS resourceGroupCode2,
r.EXTRACODE1 AS resourceGroupCode3,
r.EXTRACODE2 AS resourceGroupCode4,
r.EXTRACODE3 AS resourceGroupCode5,
r.EXTRACODE4 AS resourceGroupCode6,
r.EXTRACODE5 AS resourceGroupCode7,
r.EXTRACODE6 AS resourceGroupCode8,
r.EXTRACODE7 AS resourceGroupCode9
FROM '+@Dbname+'.dbo.BOQITEM_MATERIAL a
LEFT JOIN '+@Dbname+'.dbo.BOQITEM o ON o.BOQITEMID = a.BOQITEMID
LEFT JOIN '+@Dbname+'.dbo.MATERIAL r ON r.MATERIALID = a.MATERIALID
WHERE a.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + '
)/*@MaterialPart End*/
'
ELSE SET @MaterialPart = '' 

IF @Subcontructor = 1 
SET @SubcontructorPart = '/*SubcontructorPart Start*/
UNION ALL
(SELECT
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.code'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCode, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.eps'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectEPS, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.currency.symbol'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCurrency, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.country'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCountry, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.budget'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientBudget,
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.contractor.signature'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectSignature, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.description'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDescription, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.mainsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectJobSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.unit'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectUnit, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.basementsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectBasementSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.floors'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDuration, 
a.BOQITEMSUBCONTRACTORID+3000000000 AS id,
o.BOQITEMID AS boqitemId,
o.CODE AS boqItemCode,
o.TITLE AS boqItemTitle,
o.EDITORID AS boqItemEditorId,
o.CREATEUSERID AS boqItemCreateUserId,
o.ESTIMATOR AS boqItemEstimator,
o.PAYMENT_DATE AS boqItemPaymentDate,
o.LAST_UPDATE AS boqItemLastUpdate,
o.CREATE_DATE AS boqItemCreateDate,
o.STATUS AS boqItemStatus,
o.ACCURACY AS boqItemAccuracy,
o.FLAG AS boqItemFlag,
o.LOCCOUNTRY AS boqItemLocalizationCountry,
o.LOCSTATE AS boqItemLocalizationState,
o.LOCFAC AS boqItemLocalizationFactor,
o.QUANTITY AS boqItemQuantity1,
o.SECQUANTITY AS boqItemQuantity2,
o.ESTQUANT AS  boqItemEstimatedQuantity,
o.MEASQUANT AS boqItemTakeoffQuantity,
o.QUANTLOSS AS boqItemQuantityLoss,
o.CNQT AS boqItemConditionQT,
o.HAS_PRODUCTIVITY AS boqItemHasProductivity,
o.ACTBASED AS boqItemActivityBased,
o.DURATION AS boqItemDuration,
o.PRODUCTIVITY AS boqItemProductivity,
o.PRODFACTOR AS boqItemProductivityFactor,
o.ADJPROD AS boqItemAdjustedProductivity,
o.MANHOURS AS boqItemTotalManHours,
o.UNITMHOURS AS boqItemUnitManHours,
o.MHOURSFACTOR AS boqItemUnitManHoursFactor,
o.AUNITMHOURS AS boqItemAdjustedUnitManHours,
o.EQUHOURS AS boqItemEquipmentHours,
o.UNIT AS boqItemUnit1,
o.SECOND_UNIT AS boqItemUnit2,
o.UNITS_DIV AS boqItemUnitDivider,
o.ASSRATE AS boqItemLineItemRate,
o.ASRT AS boqItemLineItemRT,
o.EQURATE AS boqItemEquipmentRate,
o.EQRT AS boqItemEquipmentRT,
o.SUBRATE AS boqItemSubcontractorRate,
o.SUBQUOTERATE AS boqItemSubcontractorQuotedRate,
o.SBRT AS boqItemSubcontractorRateRT,
o.LABRATE AS boqItemLaborRate,
o.LBRT AS boqItemLaborRT,
o.MATRATE AS boqItemMaterialRate,
o.MATQUOTERATE AS boqItemMaterialQuotedRate,
o.MART AS boqItemMaterialRateRT,
o.CONRATE AS boqItemConsumableRate,
o.CMRT AS boqItemConsumableRateRT,
o.FABRATE AS boqItemFabricationRate,
o.SHIPRATE AS boqItemShipmentRate,
o.RATE AS boqItemTotalRate1,
o.SECRATE AS boqItemTotalRate2,
o.PUBLISHEDRATE AS boqItemPublishedRate,
o.OFFRATE AS boqItemOfferedRate1,
o.OFFSECRATE AS boqItemOfferedRate2,
o.ASSCOST AS boqItemLineItemCost,
o.EQUCOST AS boqItemEquipmentCost,
o.SUBCOST AS boqItemSubcontractorCost,
o.LABCOST AS boqItemLaborCost,
o.MATCOST AS boqItemMaterialCost,
o.CONCOST AS boqItemConsumableCost,
o.FABCOST AS boqItemFabricationCost,
o.SHIPCOST AS boqItemShipmentCost,
o.MATRESCOST AS boqItemMaterialResourcesCost,
o.TOTALCOST AS boqItemTotalCost,
o.OFFPRICE AS boqItemOfferedPrice,
o.MARKUP AS boqItemMarkup,
o.ESCALATION AS boqItemEscalation,
o.CUSTXT1 AS boqItemCustomText1,
o.CUSTXT2 AS boqItemCustomText2,
o.CUSTXT3 AS boqItemCustomText3,
o.CUSTXT4 AS boqItemCustomText4,
o.CUSTXT5 AS boqItemCustomText5,
o.CUSTXT6 AS boqItemCustomText6,
o.CUSTXT7 AS boqItemCustomText7,
o.CUSTXT8 AS boqItemCustomText8,
o.CUSTXT9 AS boqItemCustomText9,
o.CUSTXT10 AS boqItemCustomText10,
o.CUSTXT11 AS boqItemCustomText11,
o.CUSTXT12 AS boqItemCustomText12,
o.CUSTXT13 AS boqItemCustomText13,
o.CUSTXT14 AS boqItemCustomText14,
o.CUSTXT15 AS boqItemCustomText15,
o.CUSTXT16 AS boqItemCustomText16,
o.CUSTXT17 AS boqItemCustomText17,
o.CUSTXT18 AS boqItemCustomText18,
o.CUSTXT19 AS boqItemCustomText19,
o.CUSTXT20 AS boqItemCustomText20,
o.CUSRATE1 AS boqItemCustomDecimal1,
o.CUSRATE2 AS boqItemCustomDecimal2,
o.CUSRATE3 AS boqItemCustomDecimal3,
o.CUSRATE4 AS boqItemCustomDecimal4,
o.CUSRATE5 AS boqItemCustomDecimal5,
o.CUSRATE6 AS boqItemCustomDecimal6,
o.CUSRATE7 AS boqItemCustomDecimal7,
o.CUSRATE8 AS boqItemCustomDecimal8,
o.CUSRATE9 AS boqItemCustomDecimal9,
o.CUSRATE10 AS boqItemCustomDecimal10,
o.CUSCUMRATE1 AS boqItemCustomCumDecimal1,
o.CUSCUMRATE2 AS boqItemCustomCumDecimal2,
o.CUSCUMRATE3 AS boqItemCustomCumDecimal3,
o.CUSCUMRATE4 AS boqItemCustomCumDecimal4,
o.CUSCUMRATE5 AS boqItemCustomCumDecimal5,
o.CUSPER1 AS boqItemCustomPercentange1,
o.CUSPER2 AS boqItemCustomPercentange2,
o.CUSPER3 AS boqItemCustomPercentange3, ' -- Literals have smaller max size so we need to break them
+ '
o.CUSPER4 AS boqItemCustomPercentange4,
o.CUSPER5 AS boqItemCustomPercentange5,
o.CUSPER6 AS boqItemCustomPercentange6,
o.CUSPER7 AS boqItemCustomPercentange7,
o.CUSPER8 AS boqItemCustomPercentange8,
o.CUSPER9 AS boqItemCustomPercentange9,
o.CUSPER10 AS boqItemCustomPercentange10,
o.PUBLISHEDITEMCODE AS boqItemPublishedItemCode,
o.PUBLISHEDREVISIONCODE AS boqItemPublishedRevisionCode,
o.SCHEDULED AS boqItemScheduled,
o.PUGRCFACTOR AS boqItemGroupCode1UnitFactor,
o.PUGEKFACTOR AS boqItemGroupCode2UnitFactor,
o.PUEX1FACTOR AS boqItemGroupCode3UnitFactor,
o.PUEX2FACTOR AS boqItemGroupCode4UnitFactor,
o.PUEX3FACTOR AS boqItemGroupCode5UnitFactor,
o.PUEX4FACTOR AS boqItemGroupCode6UnitFactor,
o.PUEX5FACTOR AS boqItemGroupCode7UnitFactor,
o.PUEX6FACTOR AS boqItemGroupCode8UnitFactor,
o.PUEX7FACTOR AS boqItemGroupCode9UnitFactor,
o.WBSCODE    AS boqItemWbsCode1,
o.WBS2CODE   AS boqItemWbsCode2,
o.LOCATION   AS boqItemLocation,
o.GROUPCODE  AS boqItemGroupCode1,
o.GEKCODE    AS boqItemGroupCode2,
o.EXTRACODE1 AS boqItemGroupCode3,
o.EXTRACODE2 AS boqItemGroupCode4,
o.EXTRACODE3 AS boqItemGroupCode5,
o.EXTRACODE4 AS boqItemGroupCode6,
o.EXTRACODE5 AS boqItemGroupCode7,
o.EXTRACODE6 AS boqItemGroupCode8,
o.EXTRACODE7 AS boqItemGroupCode9,
o.DESCRIPTION AS boqItemDescription,
o.NOTES AS boqItemNotes,
o.ASRT AS boqItemAssemblyRateType,
o.EQRT AS boqItemEquipmentRateType,
o.LBRT AS boqItemLaborRateType,
o.SBRT AS boqItemSubcontractorRateType,
o.MART AS boqItemMaterialRateType,
o.CMRT AS boqItemConsumableRateType,
o.CNQT AS boqItemTakeoffQuantityType,
NULL AS lineItemId,
NULL AS lineItemItemCode,
NULL AS lineItemTitle,
NULL AS lineItemDescription,
NULL AS lineItemActBased,
NULL AS lineItemProductivity,
NULL AS lineItemQuantityPerUnit,
NULL AS lineItemUnit,
NULL AS lineItemProject,
NULL AS lineItemCurrency,
NULL AS lineItemTotalRate,
NULL AS lineItemMaterialRate,
NULL AS lineItemLaborRate,
NULL AS lineItemSubcontractorRate,
NULL AS lineItemEquipmentRate,
NULL AS lineItemConsumablesRate,       
''Subcontractor'' AS assignmentType,
a.BOQITEMSUBCONTRACTORID AS assignmentId,
a.FACTOR1 AS assignmentFactor1,
a.FACTOR2 AS assignmentFactor2,
a.FACTOR3 AS assignmentFactor3,
a.QTYPUNIT AS assignmentQuantityPerUnit,
a.LOCALFACTOR AS assignmentLocalFactor,
a.LOCALCOUNTRY AS assignmentLocalCountry,
a.LOCALSTATE AS assignmentLocalStateProvince,
a.COSTCENTER AS assignmentExchangeRate,
a.TOTALUNITS AS assignmentTotalUnits,
a.FRATE AS assignmentFinalRate,
a.TOTALCOST AS assignmentTotalCost,
r.SUBCONTRACTORID AS resourceId,
r.RESCODE AS resourceItemCode,
r.TITLE AS resourceTitle,
r.DESCRIPTION AS resourceDescription,
r.NOTES AS resourceNotes,
r.TOTALRATE AS resourceRate,
r.COMPANY AS resourceCompany,
r.UNIT AS resourceUnit,
r.CURRENCY AS resourceCurrency,
r.COUNTRY AS resourceCountry,
r.EDITORID AS resourceEditorId,
r.CREATEUSER AS resourceCreateUserId,
r.CREATEDATE AS resourceCreateDate,
r.LASTUPDATE AS resourceLastUpdate,
r.GROUPCODE AS resourceGroupCode1,
r.GEKCODE AS resourceGroupCode2,
r.EXTRACODE1 AS resourceGroupCode3,
r.EXTRACODE2 AS resourceGroupCode4,
r.EXTRACODE3 AS resourceGroupCode5,
r.EXTRACODE4 AS resourceGroupCode6,
r.EXTRACODE5 AS resourceGroupCode7,
r.EXTRACODE6 AS resourceGroupCode8,
r.EXTRACODE7 AS resourceGroupCode9
FROM '+@Dbname+'.dbo.BOQITEM_SUBCONTRACTOR a
LEFT JOIN '+@Dbname+'.dbo.BOQITEM o ON o.BOQITEMID = a.BOQITEMID
LEFT JOIN '+@Dbname+'.dbo.SUBCONTRACTOR r ON r.SUBCONTRACTORID = a.SUBCONTRACTORID
WHERE a.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + '
)/*SubcontructorPart End*/'  
ELSE SET @SubcontructorPart = '' 

IF @Labor = 1
SET @LaborPart = '/*LaborPart Start*/
UNION ALL
(SELECT
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.code'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCode, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.eps'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectEPS, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.currency.symbol'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCurrency, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.country'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCountry, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.budget'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientBudget,
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.contractor.signature'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectSignature, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.description'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDescription, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.mainsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectJobSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.unit'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectUnit, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.basementsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectBasementSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.floors'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDuration, 
a.BOQITEMLABORID+4000000000 AS id,
o.BOQITEMID AS boqitemId,
o.CODE AS boqItemCode,
o.TITLE AS boqItemTitle,
o.EDITORID AS boqItemEditorId,
o.CREATEUSERID AS boqItemCreateUserId,
o.ESTIMATOR AS boqItemEstimator,
o.PAYMENT_DATE AS boqItemPaymentDate,
o.LAST_UPDATE AS boqItemLastUpdate,
o.CREATE_DATE AS boqItemCreateDate,
o.STATUS AS boqItemStatus,
o.ACCURACY AS boqItemAccuracy,
o.FLAG AS boqItemFlag,
o.LOCCOUNTRY AS boqItemLocalizationCountry,
o.LOCSTATE AS boqItemLocalizationState,
o.LOCFAC AS boqItemLocalizationFactor,
o.QUANTITY AS boqItemQuantity1,
o.SECQUANTITY AS boqItemQuantity2,
o.ESTQUANT AS  boqItemEstimatedQuantity,
o.MEASQUANT AS boqItemTakeoffQuantity,
o.QUANTLOSS AS boqItemQuantityLoss,
o.CNQT AS boqItemConditionQT,
o.HAS_PRODUCTIVITY AS boqItemHasProductivity,
o.ACTBASED AS boqItemActivityBased,
o.DURATION AS boqItemDuration,
o.PRODUCTIVITY AS boqItemProductivity,
o.PRODFACTOR AS boqItemProductivityFactor,
o.ADJPROD AS boqItemAdjustedProductivity,
o.MANHOURS AS boqItemTotalManHours,
o.UNITMHOURS AS boqItemUnitManHours,
o.MHOURSFACTOR AS boqItemUnitManHoursFactor,
o.AUNITMHOURS AS boqItemAdjustedUnitManHours,
o.EQUHOURS AS boqItemEquipmentHours,
o.UNIT AS boqItemUnit1,
o.SECOND_UNIT AS boqItemUnit2,
o.UNITS_DIV AS boqItemUnitDivider,
o.ASSRATE AS boqItemLineItemRate,
o.ASRT AS boqItemLineItemRT,
o.EQURATE AS boqItemEquipmentRate,
o.EQRT AS boqItemEquipmentRT,
o.SUBRATE AS boqItemSubcontractorRate,
o.SUBQUOTERATE AS boqItemSubcontractorQuotedRate,
o.SBRT AS boqItemSubcontractorRateRT,
o.LABRATE AS boqItemLaborRate,
o.LBRT AS boqItemLaborRT,
o.MATRATE AS boqItemMaterialRate,
o.MATQUOTERATE AS boqItemMaterialQuotedRate,
o.MART AS boqItemMaterialRateRT,
o.CONRATE AS boqItemConsumableRate,
o.CMRT AS boqItemConsumableRateRT,
o.FABRATE AS boqItemFabricationRate,
o.SHIPRATE AS boqItemShipmentRate,
o.RATE AS boqItemTotalRate1,
o.SECRATE AS boqItemTotalRate2,
o.PUBLISHEDRATE AS boqItemPublishedRate,
o.OFFRATE AS boqItemOfferedRate1,
o.OFFSECRATE AS boqItemOfferedRate2,
o.ASSCOST AS boqItemLineItemCost,
o.EQUCOST AS boqItemEquipmentCost,
o.SUBCOST AS boqItemSubcontractorCost,
o.LABCOST AS boqItemLaborCost,
o.MATCOST AS boqItemMaterialCost,
o.CONCOST AS boqItemConsumableCost,
o.FABCOST AS boqItemFabricationCost,
o.SHIPCOST AS boqItemShipmentCost,
o.MATRESCOST AS boqItemMaterialResourcesCost,
o.TOTALCOST AS boqItemTotalCost,
o.OFFPRICE AS boqItemOfferedPrice,
o.MARKUP AS boqItemMarkup,
o.ESCALATION AS boqItemEscalation,
o.CUSTXT1 AS boqItemCustomText1,
o.CUSTXT2 AS boqItemCustomText2,
o.CUSTXT3 AS boqItemCustomText3,
o.CUSTXT4 AS boqItemCustomText4,
o.CUSTXT5 AS boqItemCustomText5,
o.CUSTXT6 AS boqItemCustomText6,
o.CUSTXT7 AS boqItemCustomText7,
o.CUSTXT8 AS boqItemCustomText8,
o.CUSTXT9 AS boqItemCustomText9,
o.CUSTXT10 AS boqItemCustomText10,
o.CUSTXT11 AS boqItemCustomText11,
o.CUSTXT12 AS boqItemCustomText12,
o.CUSTXT13 AS boqItemCustomText13,
o.CUSTXT14 AS boqItemCustomText14,
o.CUSTXT15 AS boqItemCustomText15,
o.CUSTXT16 AS boqItemCustomText16,
o.CUSTXT17 AS boqItemCustomText17,
o.CUSTXT18 AS boqItemCustomText18,
o.CUSTXT19 AS boqItemCustomText19,
o.CUSTXT20 AS boqItemCustomText20,
o.CUSRATE1 AS boqItemCustomDecimal1,
o.CUSRATE2 AS boqItemCustomDecimal2,
o.CUSRATE3 AS boqItemCustomDecimal3,
o.CUSRATE4 AS boqItemCustomDecimal4,
o.CUSRATE5 AS boqItemCustomDecimal5,
o.CUSRATE6 AS boqItemCustomDecimal6,
o.CUSRATE7 AS boqItemCustomDecimal7,
o.CUSRATE8 AS boqItemCustomDecimal8,
o.CUSRATE9 AS boqItemCustomDecimal9,
o.CUSRATE10 AS boqItemCustomDecimal10,
o.CUSCUMRATE1 AS boqItemCustomCumDecimal1,
o.CUSCUMRATE2 AS boqItemCustomCumDecimal2,
o.CUSCUMRATE3 AS boqItemCustomCumDecimal3,
o.CUSCUMRATE4 AS boqItemCustomCumDecimal4,
o.CUSCUMRATE5 AS boqItemCustomCumDecimal5,
o.CUSPER1 AS boqItemCustomPercentange1,
o.CUSPER2 AS boqItemCustomPercentange2,
o.CUSPER3 AS boqItemCustomPercentange3, ' -- Literals have smaller max size so we need to break them
+ '
o.CUSPER4 AS boqItemCustomPercentange4,
o.CUSPER5 AS boqItemCustomPercentange5,
o.CUSPER6 AS boqItemCustomPercentange6,
o.CUSPER7 AS boqItemCustomPercentange7,
o.CUSPER8 AS boqItemCustomPercentange8,
o.CUSPER9 AS boqItemCustomPercentange9,
o.CUSPER10 AS boqItemCustomPercentange10,
o.PUBLISHEDITEMCODE AS boqItemPublishedItemCode,
o.PUBLISHEDREVISIONCODE AS boqItemPublishedRevisionCode,
o.SCHEDULED AS boqItemScheduled,
o.PUGRCFACTOR AS boqItemGroupCode1UnitFactor,
o.PUGEKFACTOR AS boqItemGroupCode2UnitFactor,
o.PUEX1FACTOR AS boqItemGroupCode3UnitFactor,
o.PUEX2FACTOR AS boqItemGroupCode4UnitFactor,
o.PUEX3FACTOR AS boqItemGroupCode5UnitFactor,
o.PUEX4FACTOR AS boqItemGroupCode6UnitFactor,
o.PUEX5FACTOR AS boqItemGroupCode7UnitFactor,
o.PUEX6FACTOR AS boqItemGroupCode8UnitFactor,
o.PUEX7FACTOR AS boqItemGroupCode9UnitFactor,
o.WBSCODE    AS boqItemWbsCode1,
o.WBS2CODE   AS boqItemWbsCode2,
o.LOCATION   AS boqItemLocation,
o.GROUPCODE  AS boqItemGroupCode1,
o.GEKCODE    AS boqItemGroupCode2,
o.EXTRACODE1 AS boqItemGroupCode3,
o.EXTRACODE2 AS boqItemGroupCode4,
o.EXTRACODE3 AS boqItemGroupCode5,
o.EXTRACODE4 AS boqItemGroupCode6,
o.EXTRACODE5 AS boqItemGroupCode7,
o.EXTRACODE6 AS boqItemGroupCode8,
o.EXTRACODE7 AS boqItemGroupCode9,
o.DESCRIPTION AS boqItemDescription,
o.NOTES AS boqItemNotes,
o.ASRT AS boqItemAssemblyRateType,
o.EQRT AS boqItemEquipmentRateType,
o.LBRT AS boqItemLaborRateType,
o.SBRT AS boqItemSubcontractorRateType,
o.MART AS boqItemMaterialRateType,
o.CMRT AS boqItemConsumableRateType,
o.CNQT AS boqItemTakeoffQuantityType,
NULL AS lineItemId,
NULL AS lineItemItemCode,
NULL AS lineItemTitle,
NULL AS lineItemDescription,
NULL AS lineItemActBased,
NULL AS lineItemProductivity,
NULL AS lineItemQuantityPerUnit,
NULL AS lineItemUnit,
NULL AS lineItemProject,
NULL AS lineItemCurrency,
NULL AS lineItemTotalRate,
NULL AS lineItemMaterialRate,
NULL AS lineItemLaborRate,
NULL AS lineItemSubcontractorRate,
NULL AS lineItemEquipmentRate,
NULL AS lineItemConsumablesRate,       
''Labor'' AS assignmentType,
a.BOQITEMLABORID AS assignmentId,
a.FACTOR1 AS assignmentFactor1,
a.FACTOR2 AS assignmentFactor2,
a.FACTOR3 AS assignmentFactor3,
a.QTYPUNIT AS assignmentQuantityPerUnit,
a.LOCALFACTOR AS assignmentLocalFactor,
a.LOCALCOUNTRY AS assignmentLocalCountry,
a.LOCALSTATE AS assignmentLocalStateProvince,
a.COSTCENTER AS assignmentExchangeRate,
a.TOTALUNITS AS assignmentTotalUnits,
a.FRATE AS assignmentFinalRate,
a.TOTALCOST AS assignmentTotalCost,
r.LABORID AS resourceId,
r.RESCODE AS resourceItemCode,
r.TITLE AS resourceTitle,
r.DESCRIPTION AS resourceDescription,
r.NOTES AS resourceNotes,
r.TOTALRATE AS resourceRate,
r.CONTACTPERSON AS resourceCompany,
r.UNIT AS resourceUnit,
r.CURRENCY AS resourceCurrency,
r.COUNTRY AS resourceCountry,
r.EDITORID AS resourceEditorId,
r.CREATEUSER AS resourceCreateUserId,
r.CREATEDATE AS resourceCreateDate,
r.LASTUPDATE AS resourceLastUpdate,
r.GROUPCODE AS resourceGroupCode1,
r.GEKCODE AS resourceGroupCode2,
r.EXTRACODE1 AS resourceGroupCode3,
r.EXTRACODE2 AS resourceGroupCode4,
r.EXTRACODE3 AS resourceGroupCode5,
r.EXTRACODE4 AS resourceGroupCode6,
r.EXTRACODE5 AS resourceGroupCode7,
r.EXTRACODE6 AS resourceGroupCode8,
r.EXTRACODE7 AS resourceGroupCode9
FROM '+@Dbname+'.dbo.BOQITEM_LABOR a
LEFT JOIN '+@Dbname+'.dbo.BOQITEM o ON o.BOQITEMID = a.BOQITEMID
LEFT JOIN '+@Dbname+'.dbo.LABOR r ON r.LABORID = a.LABORID
WHERE a.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + '
)/*LaborPart End*/'
ELSE SET @LaborPart = '' 

IF @Equipment = 1 
SET @EquipmentPart = '/*EquipmentPart Start*/
UNION ALL
(SELECT
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.code'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCode, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.eps'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectEPS, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.currency.symbol'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCurrency, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.country'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCountry, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.budget'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientBudget,
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.contractor.signature'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectSignature, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.description'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDescription, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.mainsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectJobSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.unit'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectUnit, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.basementsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectBasementSize, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.floors'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDuration, 
a.BOQITEMEQUIPMENTID+5000000000 AS id,
o.BOQITEMID AS boqitemId,
o.CODE AS boqItemCode,
o.TITLE AS boqItemTitle,
o.EDITORID AS boqItemEditorId,
o.CREATEUSERID AS boqItemCreateUserId,
o.ESTIMATOR AS boqItemEstimator,
o.PAYMENT_DATE AS boqItemPaymentDate,
o.LAST_UPDATE AS boqItemLastUpdate,
o.CREATE_DATE AS boqItemCreateDate,
o.STATUS AS boqItemStatus,
o.ACCURACY AS boqItemAccuracy,
o.FLAG AS boqItemFlag,
o.LOCCOUNTRY AS boqItemLocalizationCountry,
o.LOCSTATE AS boqItemLocalizationState,
o.LOCFAC AS boqItemLocalizationFactor,
o.QUANTITY AS boqItemQuantity1,
o.SECQUANTITY AS boqItemQuantity2,
o.ESTQUANT AS  boqItemEstimatedQuantity,
o.MEASQUANT AS boqItemTakeoffQuantity,
o.QUANTLOSS AS boqItemQuantityLoss,
o.CNQT AS boqItemConditionQT,
o.HAS_PRODUCTIVITY AS boqItemHasProductivity,
o.ACTBASED AS boqItemActivityBased,
o.DURATION AS boqItemDuration,
o.PRODUCTIVITY AS boqItemProductivity,
o.PRODFACTOR AS boqItemProductivityFactor,
o.ADJPROD AS boqItemAdjustedProductivity,
o.MANHOURS AS boqItemTotalManHours,
o.UNITMHOURS AS boqItemUnitManHours,
o.MHOURSFACTOR AS boqItemUnitManHoursFactor,
o.AUNITMHOURS AS boqItemAdjustedUnitManHours,
o.EQUHOURS AS boqItemEquipmentHours,
o.UNIT AS boqItemUnit1,
o.SECOND_UNIT AS boqItemUnit2,
o.UNITS_DIV AS boqItemUnitDivider,
o.ASSRATE AS boqItemLineItemRate,
o.ASRT AS boqItemLineItemRT,
o.EQURATE AS boqItemEquipmentRate,
o.EQRT AS boqItemEquipmentRT,
o.SUBRATE AS boqItemSubcontractorRate,
o.SUBQUOTERATE AS boqItemSubcontractorQuotedRate,
o.SBRT AS boqItemSubcontractorRateRT,
o.LABRATE AS boqItemLaborRate,
o.LBRT AS boqItemLaborRT,
o.MATRATE AS boqItemMaterialRate,
o.MATQUOTERATE AS boqItemMaterialQuotedRate,
o.MART AS boqItemMaterialRateRT,
o.CONRATE AS boqItemConsumableRate,
o.CMRT AS boqItemConsumableRateRT,
o.FABRATE AS boqItemFabricationRate,
o.SHIPRATE AS boqItemShipmentRate,
o.RATE AS boqItemTotalRate1,
o.SECRATE AS boqItemTotalRate2,
o.PUBLISHEDRATE AS boqItemPublishedRate,
o.OFFRATE AS boqItemOfferedRate1,
o.OFFSECRATE AS boqItemOfferedRate2,
o.ASSCOST AS boqItemLineItemCost,
o.EQUCOST AS boqItemEquipmentCost,
o.SUBCOST AS boqItemSubcontractorCost,
o.LABCOST AS boqItemLaborCost,
o.MATCOST AS boqItemMaterialCost,
o.CONCOST AS boqItemConsumableCost,
o.FABCOST AS boqItemFabricationCost,
o.SHIPCOST AS boqItemShipmentCost,
o.MATRESCOST AS boqItemMaterialResourcesCost,
o.TOTALCOST AS boqItemTotalCost,
o.OFFPRICE AS boqItemOfferedPrice,
o.MARKUP AS boqItemMarkup,
o.ESCALATION AS boqItemEscalation,
o.CUSTXT1 AS boqItemCustomText1,
o.CUSTXT2 AS boqItemCustomText2,
o.CUSTXT3 AS boqItemCustomText3,
o.CUSTXT4 AS boqItemCustomText4,
o.CUSTXT5 AS boqItemCustomText5,
o.CUSTXT6 AS boqItemCustomText6,
o.CUSTXT7 AS boqItemCustomText7,
o.CUSTXT8 AS boqItemCustomText8,
o.CUSTXT9 AS boqItemCustomText9,
o.CUSTXT10 AS boqItemCustomText10,
o.CUSTXT11 AS boqItemCustomText11,
o.CUSTXT12 AS boqItemCustomText12,
o.CUSTXT13 AS boqItemCustomText13,
o.CUSTXT14 AS boqItemCustomText14,
o.CUSTXT15 AS boqItemCustomText15,
o.CUSTXT16 AS boqItemCustomText16,
o.CUSTXT17 AS boqItemCustomText17,
o.CUSTXT18 AS boqItemCustomText18,
o.CUSTXT19 AS boqItemCustomText19,
o.CUSTXT20 AS boqItemCustomText20,
o.CUSRATE1 AS boqItemCustomDecimal1,
o.CUSRATE2 AS boqItemCustomDecimal2,
o.CUSRATE3 AS boqItemCustomDecimal3,
o.CUSRATE4 AS boqItemCustomDecimal4,
o.CUSRATE5 AS boqItemCustomDecimal5,
o.CUSRATE6 AS boqItemCustomDecimal6,
o.CUSRATE7 AS boqItemCustomDecimal7,
o.CUSRATE8 AS boqItemCustomDecimal8,
o.CUSRATE9 AS boqItemCustomDecimal9,
o.CUSRATE10 AS boqItemCustomDecimal10,
o.CUSCUMRATE1 AS boqItemCustomCumDecimal1,
o.CUSCUMRATE2 AS boqItemCustomCumDecimal2,
o.CUSCUMRATE3 AS boqItemCustomCumDecimal3,
o.CUSCUMRATE4 AS boqItemCustomCumDecimal4,
o.CUSCUMRATE5 AS boqItemCustomCumDecimal5,
o.CUSPER1 AS boqItemCustomPercentange1,
o.CUSPER2 AS boqItemCustomPercentange2,
o.CUSPER3 AS boqItemCustomPercentange3, ' -- Literals have smaller max size so we need to break them
+ '
o.CUSPER4 AS boqItemCustomPercentange4,
o.CUSPER5 AS boqItemCustomPercentange5,
o.CUSPER6 AS boqItemCustomPercentange6,
o.CUSPER7 AS boqItemCustomPercentange7,
o.CUSPER8 AS boqItemCustomPercentange8,
o.CUSPER9 AS boqItemCustomPercentange9,
o.CUSPER10 AS boqItemCustomPercentange10,
o.PUBLISHEDITEMCODE AS boqItemPublishedItemCode,
o.PUBLISHEDREVISIONCODE AS boqItemPublishedRevisionCode,
o.SCHEDULED AS boqItemScheduled,
o.PUGRCFACTOR AS boqItemGroupCode1UnitFactor,
o.PUGEKFACTOR AS boqItemGroupCode2UnitFactor,
o.PUEX1FACTOR AS boqItemGroupCode3UnitFactor,
o.PUEX2FACTOR AS boqItemGroupCode4UnitFactor,
o.PUEX3FACTOR AS boqItemGroupCode5UnitFactor,
o.PUEX4FACTOR AS boqItemGroupCode6UnitFactor,
o.PUEX5FACTOR AS boqItemGroupCode7UnitFactor,
o.PUEX6FACTOR AS boqItemGroupCode8UnitFactor,
o.PUEX7FACTOR AS boqItemGroupCode9UnitFactor,
o.WBSCODE    AS boqItemWbsCode1,
o.WBS2CODE   AS boqItemWbsCode2,
o.LOCATION   AS boqItemLocation,
o.GROUPCODE  AS boqItemGroupCode1,
o.GEKCODE    AS boqItemGroupCode2,
o.EXTRACODE1 AS boqItemGroupCode3,
o.EXTRACODE2 AS boqItemGroupCode4,
o.EXTRACODE3 AS boqItemGroupCode5,
o.EXTRACODE4 AS boqItemGroupCode6,
o.EXTRACODE5 AS boqItemGroupCode7,
o.EXTRACODE6 AS boqItemGroupCode8,
o.EXTRACODE7 AS boqItemGroupCode9,
o.DESCRIPTION AS boqItemDescription,
o.NOTES AS boqItemNotes,
o.ASRT AS boqItemAssemblyRateType,
o.EQRT AS boqItemEquipmentRateType,
o.LBRT AS boqItemLaborRateType,
o.SBRT AS boqItemSubcontractorRateType,
o.MART AS boqItemMaterialRateType,
o.CMRT AS boqItemConsumableRateType,
o.CNQT AS boqItemTakeoffQuantityType,
NULL AS lineItemId,
NULL AS lineItemItemCode,
NULL AS lineItemTitle,
NULL AS lineItemDescription,
NULL AS lineItemActBased,
NULL AS lineItemProductivity,
NULL AS lineItemQuantityPerUnit,
NULL AS lineItemUnit,
NULL AS lineItemProject,
NULL AS lineItemCurrency,
NULL AS lineItemTotalRate,
NULL AS lineItemMaterialRate,
NULL AS lineItemLaborRate,
NULL AS lineItemSubcontractorRate,
NULL AS lineItemEquipmentRate,
NULL AS lineItemConsumablesRate,       
''Equipment'' AS assignmentType,
a.BOQITEMEQUIPMENTID AS assignmentId,
a.FACTOR1 AS assignmentFactor1,
a.FACTOR2 AS assignmentFactor2,
a.FACTOR3 AS assignmentFactor3,
a.QTYPUNIT AS assignmentQuantityPerUnit,
a.LOCALFACTOR AS assignmentLocalFactor,
a.LOCALCOUNTRY AS assignmentLocalCountry,
a.LOCALSTATE AS assignmentLocalStateProvince,
a.COSTCENTER AS assignmentExchangeRate,
a.TOTALUNITS AS assignmentTotalUnits,
a.FRATE AS assignmentFinalRate,
a.TOTALCOST AS assignmentTotalCost,
r.EQUIPMENTID AS resourceId,
r.RESCODE AS resourceItemCode,
r.TITLE AS resourceTitle,
r.DESCRIPTION AS resourceDescription,
r.NOTES AS resourceNotes,
r.TOTALRATE AS resourceRate,
NULL AS resourceCompany,
r.UNIT AS resourceUnit,
r.CURRENCY AS resourceCurrency,
r.COUNTRY AS resourceCountry,
r.EDITORID AS resourceEditorId,
r.CREATEUSER AS resourceCreateUserId,
r.CREATEDATE AS resourceCreateDate,
r.LASTUPDATE AS resourceLastUpdate,
r.GROUPCODE AS resourceGroupCode1,
r.GEKCODE AS resourceGroupCode2,
r.EXTRACODE1 AS resourceGroupCode3,
r.EXTRACODE2 AS resourceGroupCode4,
r.EXTRACODE3 AS resourceGroupCode5,
r.EXTRACODE4 AS resourceGroupCode6,
r.EXTRACODE5 AS resourceGroupCode7,
r.EXTRACODE6 AS resourceGroupCode8,
r.EXTRACODE7 AS resourceGroupCode9
FROM '+@Dbname+'.dbo.BOQITEM_EQUIPMENT a
LEFT JOIN '+@Dbname+'.dbo.BOQITEM o ON o.BOQITEMID = a.BOQITEMID
LEFT JOIN '+@Dbname+'.dbo.EQUIPMENT r ON r.EQUIPMENTID = a.EQUIPMENTID
WHERE a.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + '
)/*EquipmentPart End*/
'
ELSE SET @EquipmentPart = ''
 
IF @Consumable = 1
SET @ConsumablePart = ' /*ConsumablePart Start*/
UNION ALL
(SELECT
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.code'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCode, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.eps'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectEPS, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.currency.symbol'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCurrency, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.country'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectCountry, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.name'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientName, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.client.budget'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectClientBudget,
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.contractor.signature'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectSignature, 
(SELECT p.PVAL FROM '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.description'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDescription, 
(SELECT p.PVAL from '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.mainsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectJobSize, 
(SELECT p.PVAL from '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.unit'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectUnit, 
(SELECT p.PVAL from '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.basementsqm'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectBasementSize, 
(SELECT p.PVAL from '+@Dbname+'.dbo.PRJPROP AS p WHERE p.PKEY=''project.floors'' AND p.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + ') AS projectDuration, 
a.BOQITEMCONSUMABLEID+6000000000 AS id,
o.BOQITEMID AS boqitemId,
o.CODE AS boqItemCode,
o.TITLE AS boqItemTitle,
o.EDITORID AS boqItemEditorId,
o.CREATEUSERID AS boqItemCreateUserId,
o.ESTIMATOR AS boqItemEstimator,
o.PAYMENT_DATE AS boqItemPaymentDate,
o.LAST_UPDATE AS boqItemLastUpdate,
o.CREATE_DATE AS boqItemCreateDate,
o.STATUS AS boqItemStatus,
o.ACCURACY AS boqItemAccuracy,
o.FLAG AS boqItemFlag,
o.LOCCOUNTRY AS boqItemLocalizationCountry,
o.LOCSTATE AS boqItemLocalizationState,
o.LOCFAC AS boqItemLocalizationFactor,
o.QUANTITY AS boqItemQuantity1,
o.SECQUANTITY AS boqItemQuantity2,
o.ESTQUANT AS  boqItemEstimatedQuantity,
o.MEASQUANT AS boqItemTakeoffQuantity,
o.QUANTLOSS AS boqItemQuantityLoss,
o.CNQT AS boqItemConditionQT,
o.HAS_PRODUCTIVITY AS boqItemHasProductivity,
o.ACTBASED AS boqItemActivityBased,
o.DURATION AS boqItemDuration,
o.PRODUCTIVITY AS boqItemProductivity,
o.PRODFACTOR AS boqItemProductivityFactor,
o.ADJPROD AS boqItemAdjustedProductivity,
o.MANHOURS AS boqItemTotalManHours,
o.UNITMHOURS AS boqItemUnitManHours,
o.MHOURSFACTOR AS boqItemUnitManHoursFactor,
o.AUNITMHOURS AS boqItemAdjustedUnitManHours,
o.EQUHOURS AS boqItemEquipmentHours,
o.UNIT AS boqItemUnit1,
o.SECOND_UNIT AS boqItemUnit2,
o.UNITS_DIV AS boqItemUnitDivider,
o.ASSRATE AS boqItemLineItemRate,
o.ASRT AS boqItemLineItemRT,
o.EQURATE AS boqItemEquipmentRate,
o.EQRT AS boqItemEquipmentRT,
o.SUBRATE AS boqItemSubcontractorRate,
o.SUBQUOTERATE AS boqItemSubcontractorQuotedRate,
o.SBRT AS boqItemSubcontractorRateRT,
o.LABRATE AS boqItemLaborRate,
o.LBRT AS boqItemLaborRT,
o.MATRATE AS boqItemMaterialRate,
o.MATQUOTERATE AS boqItemMaterialQuotedRate,
o.MART AS boqItemMaterialRateRT,
o.CONRATE AS boqItemConsumableRate,
o.CMRT AS boqItemConsumableRateRT,
o.FABRATE AS boqItemFabricationRate,
o.SHIPRATE AS boqItemShipmentRate,
o.RATE AS boqItemTotalRate1,
o.SECRATE AS boqItemTotalRate2,
o.PUBLISHEDRATE AS boqItemPublishedRate,
o.OFFRATE AS boqItemOfferedRate1,
o.OFFSECRATE AS boqItemOfferedRate2,
o.ASSCOST AS boqItemLineItemCost,
o.EQUCOST AS boqItemEquipmentCost,
o.SUBCOST AS boqItemSubcontractorCost,
o.LABCOST AS boqItemLaborCost,
o.MATCOST AS boqItemMaterialCost,
o.CONCOST AS boqItemConsumableCost,
o.FABCOST AS boqItemFabricationCost,
o.SHIPCOST AS boqItemShipmentCost,
o.MATRESCOST AS boqItemMaterialResourcesCost,
o.TOTALCOST AS boqItemTotalCost,
o.OFFPRICE AS boqItemOfferedPrice,
o.MARKUP AS boqItemMarkup,
o.ESCALATION AS boqItemEscalation,
o.CUSTXT1 AS boqItemCustomText1,
o.CUSTXT2 AS boqItemCustomText2,
o.CUSTXT3 AS boqItemCustomText3,
o.CUSTXT4 AS boqItemCustomText4,
o.CUSTXT5 AS boqItemCustomText5,
o.CUSTXT6 AS boqItemCustomText6,
o.CUSTXT7 AS boqItemCustomText7,
o.CUSTXT8 AS boqItemCustomText8,
o.CUSTXT9 AS boqItemCustomText9,
o.CUSTXT10 AS boqItemCustomText10,
o.CUSTXT11 AS boqItemCustomText11,
o.CUSTXT12 AS boqItemCustomText12,
o.CUSTXT13 AS boqItemCustomText13,
o.CUSTXT14 AS boqItemCustomText14,
o.CUSTXT15 AS boqItemCustomText15,
o.CUSTXT16 AS boqItemCustomText16,
o.CUSTXT17 AS boqItemCustomText17,
o.CUSTXT18 AS boqItemCustomText18,
o.CUSTXT19 AS boqItemCustomText19,
o.CUSTXT20 AS boqItemCustomText20,
o.CUSRATE1 AS boqItemCustomDecimal1,
o.CUSRATE2 AS boqItemCustomDecimal2,
o.CUSRATE3 AS boqItemCustomDecimal3,
o.CUSRATE4 AS boqItemCustomDecimal4,
o.CUSRATE5 AS boqItemCustomDecimal5,
o.CUSRATE6 AS boqItemCustomDecimal6,
o.CUSRATE7 AS boqItemCustomDecimal7,
o.CUSRATE8 AS boqItemCustomDecimal8,
o.CUSRATE9 AS boqItemCustomDecimal9,
o.CUSRATE10 AS boqItemCustomDecimal10,
o.CUSCUMRATE1 AS boqItemCustomCumDecimal1,
o.CUSCUMRATE2 AS boqItemCustomCumDecimal2,
o.CUSCUMRATE3 AS boqItemCustomCumDecimal3,
o.CUSCUMRATE4 AS boqItemCustomCumDecimal4,
o.CUSCUMRATE5 AS boqItemCustomCumDecimal5,
o.CUSPER1 AS boqItemCustomPercentange1,
o.CUSPER2 AS boqItemCustomPercentange2,
o.CUSPER3 AS boqItemCustomPercentange3, ' -- Literals have smaller max size so we need to break them
+ '
o.CUSPER4 AS boqItemCustomPercentange4,
o.CUSPER5 AS boqItemCustomPercentange5,
o.CUSPER6 AS boqItemCustomPercentange6,
o.CUSPER7 AS boqItemCustomPercentange7,
o.CUSPER8 AS boqItemCustomPercentange8,
o.CUSPER9 AS boqItemCustomPercentange9,
o.CUSPER10 AS boqItemCustomPercentange10,
o.PUBLISHEDITEMCODE AS boqItemPublishedItemCode,
o.PUBLISHEDREVISIONCODE AS boqItemPublishedRevisionCode,
o.SCHEDULED AS boqItemScheduled,
o.PUGRCFACTOR AS boqItemGroupCode1UnitFactor,
o.PUGEKFACTOR AS boqItemGroupCode2UnitFactor,
o.PUEX1FACTOR AS boqItemGroupCode3UnitFactor,
o.PUEX2FACTOR AS boqItemGroupCode4UnitFactor,
o.PUEX3FACTOR AS boqItemGroupCode5UnitFactor,
o.PUEX4FACTOR AS boqItemGroupCode6UnitFactor,
o.PUEX5FACTOR AS boqItemGroupCode7UnitFactor,
o.PUEX6FACTOR AS boqItemGroupCode8UnitFactor,
o.PUEX7FACTOR AS boqItemGroupCode9UnitFactor,
o.WBSCODE    AS boqItemWbsCode1,
o.WBS2CODE   AS boqItemWbsCode2,
o.LOCATION   AS boqItemLocation,
o.GROUPCODE  AS boqItemGroupCode1,
o.GEKCODE    AS boqItemGroupCode2,
o.EXTRACODE1 AS boqItemGroupCode3,
o.EXTRACODE2 AS boqItemGroupCode4,
o.EXTRACODE3 AS boqItemGroupCode5,
o.EXTRACODE4 AS boqItemGroupCode6,
o.EXTRACODE5 AS boqItemGroupCode7,
o.EXTRACODE6 AS boqItemGroupCode8,
o.EXTRACODE7 AS boqItemGroupCode9,
o.DESCRIPTION AS boqItemDescription,
o.NOTES AS boqItemNotes,
o.ASRT AS boqItemAssemblyRateType,
o.EQRT AS boqItemEquipmentRateType,
o.LBRT AS boqItemLaborRateType,
o.SBRT AS boqItemSubcontractorRateType,
o.MART AS boqItemMaterialRateType,
o.CMRT AS boqItemConsumableRateType,
o.CNQT AS boqItemTakeoffQuantityType,
NULL AS lineItemId,
NULL AS lineItemItemCode,
NULL AS lineItemTitle,
NULL AS lineItemDescription,
NULL AS lineItemActBased,
NULL AS lineItemProductivity,
NULL AS lineItemQuantityPerUnit,
NULL AS lineItemUnit,
NULL AS lineItemProject,
NULL AS lineItemCurrency,
NULL AS lineItemTotalRate,
NULL AS lineItemMaterialRate,
NULL AS lineItemLaborRate,
NULL AS lineItemSubcontractorRate,
NULL AS lineItemEquipmentRate,
NULL AS lineItemConsumablesRate,       
''Consumable'' AS assignmentType,
a.BOQITEMCONSUMABLEID AS assignmentId,
a.FACTOR1 AS assignmentFactor1,
a.FACTOR2 AS assignmentFactor2,
a.DIVIDER AS assignmentFactor3,
a.QTYPUNIT AS assignmentQuantityPerUnit,
a.LOCALFACTOR AS assignmentLocalFactor,
a.LOCALCOUNTRY AS assignmentLocalCountry,
a.LOCALSTATE AS assignmentLocalStateProvince,
a.COSTCENTER AS assignmentExchangeRate,
a.TOTALUNITS AS assignmentTotalUnits,
a.FRATE AS assignmentFinalRate,
a.TOTALCOST AS assignmentTotalCost,
r.CONSUMABLEID AS resourceId,
r.RESCODE AS resourceItemCode,
r.TITLE AS resourceTitle,
r.DESCRIPTION AS resourceDescription,
r.NOTES AS resourceNotes,
r.RATE AS resourceRate,
NULL AS resourceCompany,
r.UNIT AS resourceUnit,
r.CURRENCY AS resourceCurrency,
r.COUNTRY AS resourceCountry,
r.EDITORID AS resourceEditorId,
r.CREATEUSER AS resourceCreateUserId,
r.CREATEDATE AS resourceCreateDate,
r.LASTUPDATE AS resourceLastUpdate,
r.GROUPCODE AS resourceGroupCode1,
r.GEKCODE AS resourceGroupCode2,
r.EXTRACODE1 AS resourceGroupCode3,
r.EXTRACODE2 AS resourceGroupCode4,
r.EXTRACODE3 AS resourceGroupCode5,
r.EXTRACODE4 AS resourceGroupCode6,
r.EXTRACODE5 AS resourceGroupCode7,
r.EXTRACODE6 AS resourceGroupCode8,
r.EXTRACODE7 AS resourceGroupCode9
FROM '+@Dbname+'.dbo.BOQITEM_CONSUMABLE a
LEFT JOIN '+@Dbname+'.dbo.BOQITEM o ON o.BOQITEMID = a.BOQITEMID
LEFT JOIN '+@Dbname+'.dbo.CONSUMABLE r ON r.CONSUMABLEID = a.CONSUMABLEID
WHERE a.PRJID=' + CAST(@PrjId as VARCHAR(MAX)) + '
)/*ConsumablePart End*/'
ELSE SET @ConsumablePart = ''  

SET @SqlQuery = @LineItemsUnion

SET @SqlQuery = 'SELECT * FROM ( ' +@MainPart 
	+@LineItemsUnion
	+@LineItemMaterialPart
	+@LineItemEquipmentPart
	+@LineItemLaborPart
	+@LineItemSubcontructorPart
	+@LineItemConsumablePart
	+') AS LINEITEMWITHROUSOURCES 
	) /* end of huge join */ 
	  r ON r.lineItemId = a.ASSEMBLYID 
	  WHERE a.PRJID = ' + CAST(@PrjId as VARCHAR(MAX)) + '
	) '
	+@MaterialPart
	+@SubcontructorPart
	+@LaborPart
	+@EquipmentPart
	+@ConsumablePart
	+' ) AS BOQWITHEXPANDEDRESOURCESVIEW '

	RETURN

END
