CREATE TABLE [dbo].[ASSEMBLY_CONSUMABLE] (
    [ASSEMBLYCONSUMABLEID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [LASTUPDATE]           DATETIME2 (7)    NULL,
    [FRATE]                NUMERIC (30, 10) NULL,
    [FACTOR1]              NUMERIC (30, 10) NULL,
    [FACTOR2]              NUMERIC (30, 10) NULL,
    [DIVIDER]              NUMERIC (30, 10) NULL,
    [QTYPUNIT]             NUMERIC (30, 10) NULL,
    [QTYPUNITFORM]         NVARCHAR (MAX)   NULL,
    [QTYPUFORMSTATE]       TINYINT          NULL,
    [LOCALFACTOR]          NUMERIC (30, 10) NULL,
    [LOCALCOUNTRY]         NVARCHAR (255)   NULL,
    [LOCALSTATE]           NVARCHAR (255)   NULL,
    [EXCHANGERATE]         NUMERIC (30, 10) NULL,
    [FIXEDCOST]            NUMERIC (30, 10) NULL,
    [FINALFIXEDCOST]       NUMERIC (30, 10) NULL,
    [PV_VARS]              NVARCHAR (MAX)   NULL,
    [CONSUMABLEID]         BIGINT           NULL,
    [ASSEMBLYID]           BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([ASSEMBLYCONSUMABLEID] ASC),
    CONSTRAINT [FKF8A5E65C14030E1E] FOREIGN KEY ([ASSEMBLYID]) REFERENCES [dbo].[ASSEMBLY] ([ASSEMBLYID]),
    CONSTRAINT [FKF8A5E65CFFA537BE] FOREIGN KEY ([CONSUMABLEID]) REFERENCES [dbo].[CONSUMABLE] ([CONSUMABLEID])
);

