CREATE TABLE [dbo].[ASSEMBLY] (
    [ASSEMBLYID]    BIGINT           IDENTITY (1, 1) NOT NULL,
    [LASTUPDATE]    DATETIME2 (7)    NULL,
    [VIRTUAL]       BIT              NULL,
    [VIRTUALEQU]    BIT              NULL,
    [VIRTUALSUB]    BIT              NULL,
    [VIRTUALLAB]    BIT              NULL,
    [VIRTUALMAT]    BIT              NULL,
    [VIRTUALCON]    BIT              NULL,
    [OVERTYPE]      INT              NULL,
    [ACTBASED]      BIT              NULL,
    [DESCRIPTION]   NVARCHAR (MAX)   NULL,
    [UNIT]          NVARCHAR (255)   NULL,
    [PRODUCTIVITY]  NUMERIC (30, 10) NULL,
    [PUBLISHEDRATE] NUMERIC (30, 10) NULL,
    [PUBLISHEDCODE] NVARCHAR (255)   NULL,
    [RESCODE]       NVARCHAR (255)   NULL,
    [GROUPCODE]     NVARCHAR (255)   NULL,
    [GEKCODE]       NVARCHAR (255)   NULL,
    [PROJECT]       NVARCHAR (255)   NULL,
    [ACCRIGHTS]     NVARCHAR (255)   NULL,
    [KEYW]          NVARCHAR (MAX)   NULL,
    [TITLE]         NVARCHAR (MAX)   NULL,
    [NOTES]         NVARCHAR (MAX)   NULL,
    [EDITORID]      NVARCHAR (255)   NULL,
    [CURRENCY]      NVARCHAR (255)   NULL,
    [STATEPROVINCE] NVARCHAR (255)   NULL,
    [RATE]          NUMERIC (30, 10) NULL,
    [LABRATE]       NUMERIC (30, 10) NULL,
    [MATRATE]       NUMERIC (30, 10) NULL,
    [SUBRATE]       NUMERIC (30, 10) NULL,
    [CONRATE]       NUMERIC (30, 10) NULL,
    [EQURATE]       NUMERIC (30, 10) NULL,
    [UMHOURS]       NUMERIC (30, 10) NULL,
    [UEHOURS]       NUMERIC (30, 10) NULL,
    [QTY]           NUMERIC (30, 10) NULL,
    [ACCURACY]      NVARCHAR (255)   NULL,
    [CREATEUSER]    NVARCHAR (255)   NULL,
    [CREATEDATE]    DATETIME2 (7)    NULL,
    [BIMTYPE]       NVARCHAR (255)   NULL,
    [BIMMATERIAL]   NVARCHAR (MAX)   NULL,
    [COUNTRY]       NVARCHAR (255)   NULL,
    [CUSTXT1]       NVARCHAR (255)   NULL,
    [CUSTXT2]       NVARCHAR (255)   NULL,
    [CUSTXT3]       NVARCHAR (255)   NULL,
    [CUSTXT4]       NVARCHAR (255)   NULL,
    [CUSTXT5]       NVARCHAR (255)   NULL,
    [CUSTXT6]       NVARCHAR (255)   NULL,
    [CUSTXT7]       NVARCHAR (255)   NULL,
    [CUSTXT8]       NVARCHAR (255)   NULL,
    [CUSTXT9]       NVARCHAR (255)   NULL,
    [CUSTXT10]      NVARCHAR (255)   NULL,
    [CUSTXT11]      NVARCHAR (255)   NULL,
    [CUSTXT12]      NVARCHAR (255)   NULL,
    [CUSTXT13]      NVARCHAR (255)   NULL,
    [CUSTXT14]      NVARCHAR (255)   NULL,
    [CUSTXT15]      NVARCHAR (255)   NULL,
    [CUSTXT16]      NVARCHAR (255)   NULL,
    [CUSTXT17]      NVARCHAR (255)   NULL,
    [CUSTXT18]      NVARCHAR (255)   NULL,
    [CUSTXT19]      NVARCHAR (255)   NULL,
    [CUSTXT20]      NVARCHAR (255)   NULL,
    [CUSTXT21]      NVARCHAR (255)   NULL,
    [CUSTXT22]      NVARCHAR (255)   NULL,
    [CUSTXT23]      NVARCHAR (255)   NULL,
    [CUSTXT24]      NVARCHAR (255)   NULL,
    [CUSTXT25]      NVARCHAR (255)   NULL,
    [CUSRATE1]      NUMERIC (30, 10) NULL,
    [CUSRATE2]      NUMERIC (30, 10) NULL,
    [CUSRATE3]      NUMERIC (30, 10) NULL,
    [CUSRATE4]      NUMERIC (30, 10) NULL,
    [CUSRATE5]      NUMERIC (30, 10) NULL,
    [CUSRATE6]      NUMERIC (30, 10) NULL,
    [CUSRATE7]      NUMERIC (30, 10) NULL,
    [CUSRATE8]      NUMERIC (30, 10) NULL,
    [CUSRATE9]      NUMERIC (30, 10) NULL,
    [CUSRATE10]     NUMERIC (30, 10) NULL,
    [CUSRATE11]     NUMERIC (30, 10) NULL,
    [CUSRATE12]     NUMERIC (30, 10) NULL,
    [CUSRATE13]     NUMERIC (30, 10) NULL,
    [CUSRATE14]     NUMERIC (30, 10) NULL,
    [CUSRATE15]     NUMERIC (30, 10) NULL,
    [CUSRATE16]     NUMERIC (30, 10) NULL,
    [CUSRATE17]     NUMERIC (30, 10) NULL,
    [CUSRATE18]     NUMERIC (30, 10) NULL,
    [CUSRATE19]     NUMERIC (30, 10) NULL,
    [CUSRATE20]     NUMERIC (30, 10) NULL,
    [EXTRACODE1]    NVARCHAR (255)   NULL,
    [EXTRACODE2]    NVARCHAR (255)   NULL,
    [EXTRACODE3]    NVARCHAR (255)   NULL,
    [EXTRACODE4]    NVARCHAR (255)   NULL,
    [EXTRACODE5]    NVARCHAR (255)   NULL,
    [EXTRACODE6]    NVARCHAR (255)   NULL,
    [EXTRACODE7]    NVARCHAR (255)   NULL,
    [EXTRACODE8]    NVARCHAR (255)   NULL,
    [EXTRACODE9]    NVARCHAR (255)   NULL,
    [EXTRACODE10]   NVARCHAR (255)   NULL,
    [VARS]          NVARCHAR (MAX)   NULL,
    [PUGRCFACTOR]   NUMERIC (30, 10) NULL,
    [PUGEKFACTOR]   NUMERIC (30, 10) NULL,
    [PUEX1FACTOR]   NUMERIC (30, 10) NULL,
    [PUEX2FACTOR]   NUMERIC (30, 10) NULL,
    [PUEX3FACTOR]   NUMERIC (30, 10) NULL,
    [PUEX4FACTOR]   NUMERIC (30, 10) NULL,
    [PUEX5FACTOR]   NUMERIC (30, 10) NULL,
    [PUEX6FACTOR]   NUMERIC (30, 10) NULL,
    [PUEX7FACTOR]   NUMERIC (30, 10) NULL,
    PRIMARY KEY CLUSTERED ([ASSEMBLYID] ASC)
);


GO

CREATE TRIGGER tr_unique_item_code_assembly on dbo.ASSEMBLY

FOR INSERT ,UPDATE
AS 

SET NOCOUNT ON;
DECLARE @tempRes VARCHAR(max)
DECLARE @tempId bigint
DECLARE @TempString VARCHAR(max)
DECLARE my_Cursor CURSOR LOCAL FAST_FORWARD FOR SELECT RESCODE,ASSEMBLYID FROM INSERTED;
OPEN my_Cursor 
FETCH NEXT FROM my_Cursor into @tempRes,@tempId
 
 WHILE @@FETCH_STATUS = 0 
 
 BEGIN
	IF ( CHARINDEX( '_N_VALID',@tempRes) = 0) 
	IF EXISTS ( SELECT before.RESCODE 
	FROM ( SELECT * FROM dbo.ASSEMBLY AS a WHERE a.ASSEMBLYID NOT IN(SELECT o.ASSEMBLYID FROM inserted o ) ) AS before
	WHERE before.RESCODE=@tempRes )	
	UPDATE a SET  a.RESCODE = a.RESCODE+'_N_VALID' FROM dbo.ASSEMBLY a WHERE  a.ASSEMBLYID = @tempId 
	FETCH NEXT FROM my_Cursor into @tempRes,@tempId
 END 


GO
DISABLE TRIGGER [dbo].[tr_unique_item_code_assembly]
    ON [dbo].[ASSEMBLY];

