CREATE TABLE [dbo].[BC_GROUPELEM] (
    [ID]       BIGINT IDENTITY (1, 1) NOT NULL,
    [ELEM_ID]  BIGINT NULL,
    [GROUP_ID] BIGINT NULL,
    [MODEL_ID] BIGINT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FKE8A39FF04160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FKE8A39FF0536DCE28] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[BC_GROUP] ([ID]),
    CONSTRAINT [FKE8A39FF0CE3F453B] FOREIGN KEY ([ELEM_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

