CREATE TABLE [dbo].[BC_PROJECT] (
    [ID]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [CODE]      NVARCHAR (256) NULL,
    [DESCR]     NVARCHAR (MAX) NULL,
    [GLOBALID]  NVARCHAR (256) NULL,
    [DELETED]   BIT            NULL,
    [NAME]      NVARCHAR (256) NULL,
    [PARENT_ID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK6DC3B4FB6EDCC43] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[BC_PROJECT] ([ID])
);

