CREATE TABLE [dbo].[CNTRLOGITEM] (
    [ID]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [LOGID]  BIGINT         NULL,
    [FLTR]   NVARCHAR (255) NULL,
    [OPRTN]  TINYINT        NULL,
    [ITEMID] BIGINT         NULL,
    [ITEM]   NVARCHAR (MAX) NULL,
    [PRJID]  BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[CNTRLOGITEM]([PRJID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_LOGID]
    ON [dbo].[CNTRLOGITEM]([LOGID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ITEMID]
    ON [dbo].[CNTRLOGITEM]([ITEMID] ASC);

