CREATE TABLE [dbo].[PARAMITEM] (
    [PARAMITEMID]   BIGINT           IDENTITY (1, 1) NOT NULL,
    [SAMPLERATE]    NUMERIC (30, 10) NULL,
    [ICON]          NVARCHAR (255)   NULL,
    [CMODEL]        BIT              NULL,
    [GROUPNAME]     NVARCHAR (255)   NULL,
    [TOTALCOST]     NUMERIC (30, 10) NULL,
    [QTY]           NUMERIC (30, 10) NULL,
    [MULTUNITQTY]   BIT              NULL,
    [VARIABLE]      NVARCHAR (255)   NULL,
    [DESCRIPTION]   NVARCHAR (MAX)   NULL,
    [ACCRIGHTS]     NVARCHAR (255)   NULL,
    [KEYW]          NVARCHAR (MAX)   NULL,
    [RESCODE]       NVARCHAR (255)   NULL,
    [TITLEEQU]      NVARCHAR (MAX)   NULL,
    [GROUPIDENTITY] NVARCHAR (255)   NULL,
    [TITLE]         NVARCHAR (255)   NULL,
    [UNIT]          NVARCHAR (255)   NULL,
    [GROUPCODE]     NVARCHAR (255)   NULL,
    [GEKCODE]       NVARCHAR (255)   NULL,
    [EDITORID]      NVARCHAR (255)   NULL,
    [NOTES]         NVARCHAR (255)   NULL,
    [LASTUPDATE]    DATETIME2 (7)    NULL,
    [EXTRACODE1]    NVARCHAR (255)   NULL,
    [EXTRACODE2]    NVARCHAR (255)   NULL,
    [EXTRACODE3]    NVARCHAR (255)   NULL,
    [EXTRACODE4]    NVARCHAR (255)   NULL,
    [EXTRACODE5]    NVARCHAR (255)   NULL,
    [EXTRACODE6]    NVARCHAR (255)   NULL,
    [EXTRACODE7]    NVARCHAR (255)   NULL,
    [EXTRACODE8]    NVARCHAR (255)   NULL,
    [EXTRACODE9]    NVARCHAR (255)   NULL,
    [EXTRACODE10]   NVARCHAR (255)   NULL,
    [WBS]           NVARCHAR (255)   NULL,
    [WBS2]          NVARCHAR (255)   NULL,
    [LOC]           NVARCHAR (255)   NULL,
    [PSWD]          NVARCHAR (255)   NULL,
    [SNUM]          NVARCHAR (MAX)   NULL,
    [PRTTYPE]       NVARCHAR (255)   NULL,
    [CREATEUSERID]  NVARCHAR (255)   NULL,
    [CREATEDATE]    DATETIME2 (7)    NULL,
    PRIMARY KEY CLUSTERED ([PARAMITEMID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_TITLE]
    ON [dbo].[PARAMITEM]([TITLE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_GROUPIDENTITY]
    ON [dbo].[PARAMITEM]([GROUPIDENTITY] ASC);


GO

create trigger trigger_unique_item_code_paramitem on dbo.PARAMITEM

FOR INSERT ,UPDATE
AS 

SET NOCOUNT ON;
DECLARE @tempRes VARCHAR(max)
DECLARE @tempId bigint
DECLARE @TempString VARCHAR(max)
DECLARE my_Cursor CURSOR LOCAL FAST_FORWARD FOR SELECT RESCODE,PARAMITEMID FROM INSERTED;
OPEN my_Cursor 
FETCH NEXT FROM my_Cursor into @tempRes,@tempId
 
 WHILE @@FETCH_STATUS = 0 
 
 BEGIN
	IF ( CHARINDEX( '_N_VALID',@tempRes) = 0) 
	IF EXISTS ( SELECT before.RESCODE 
	FROM ( SELECT * FROM dbo.PARAMITEM AS a WHERE a.PARAMITEMID NOT IN(SELECT o.PARAMITEMID FROM inserted o ) ) AS before
	WHERE before.RESCODE=@tempRes )	
	UPDATE a SET  a.RESCODE = a.RESCODE+'_N_VALID' FROM dbo.PARAMITEM a WHERE  a.PARAMITEMID = @tempId 
	FETCH NEXT FROM my_Cursor into @tempRes,@tempId
 END 

GO
DISABLE TRIGGER [dbo].[trigger_unique_item_code_paramitem]
    ON [dbo].[PARAMITEM];

