using System;

namespace Models.view
{
    [Serializable]
    public class BoqItemWithTakeoffsView
    {
        public string projectName { get; set; }
        public string projectCode { get; set; }
        public string projectCurrency { get; set; }
        public string projectCountry { get; set; }
        public string projectClientName { get; set; }
        public string projectSignature { get; set; }
        public string projectDescription { get; set; }
        public string projectClientBudget { get; set; }
        public string projectJobSize { get; set; }
        public string projectUnit { get; set; }
        public string projectBasementSize { get; set; }
        public string projectDuration { get; set; }
        public string projectEPS { get; set; }
        public string projectEPSLevel1Code { get; set; }
        public string projectEPSLevel1Title { get; set; }
        public string projectEPSLevel2Code { get; set; }
        public string projectEPSLevel2Title { get; set; }
        public string projectEPSLevel3Code { get; set; }
        public string projectEPSLevel3Title { get; set; }
        public string projectEPSLevel4Code { get; set; }
        public string projectEPSLevel4Title { get; set; }
        public string projectEPSLevel5Code { get; set; }
        public string projectEPSLevel5Title { get; set; }

        public long? boqitemId { get; set; }
        public long? boqItemCode { get; set; }
        public string boqItemTitle { get; set; }
        public string boqItemAssemblyId { get; set; }
        public string boqItemAssemblyTitle { get; set; }
        public string boqItemEditorId { get; set; }
        public string boqItemCreateUserId { get; set; }
        public string boqItemEstimator { get; set; }
        public DateTime boqItemPaymentDate { get; set; }
        public DateTime boqItemLastUpdate { get; set; }
        public DateTime boqItemCreateDate { get; set; }
        public string boqItemStatus { get; set; }
        public string boqItemAccuracy { get; set; }
        public int? boqItemFlag { get; set; }
        public string boqItemLocalizationCountry { get; set; }
        public string boqItemLocalizationState { get; set; }
        public string boqItemLocalizationFactor { get; set; }
        public decimal boqItemQuantity1 { get; set; }
        public decimal boqItemQuantity2 { get; set; }
        public bool? boqItemActivityBased { get; set; }
        public decimal boqItemEstimatedQuantity { get; set; }
        public decimal boqItemTakeoffQuantity { get; set; }
        public decimal boqItemQuantityLoss { get; set; }
        public sbyte? boqItemConditionQT { get; set; }
        public bool? boqItemHasProductivity { get; set; }
        public decimal boqItemDuration { get; set; }
        public decimal boqItemProductivity { get; set; }
        public decimal boqItemProductivityFactor { get; set; }
        public decimal boqItemAdjustedProductivity { get; set; }
        public decimal boqItemTotalManHours { get; set; }
        public decimal boqItemEquipmentHours { get; set; }
        public decimal boqItemUnitManHours { get; set; }
        public decimal boqItemUnitManHoursFactor { get; set; }
        public decimal boqItemAdjustedUnitManHours { get; set; }
        public string boqItemUnit1 { get; set; }
        public string boqItemUnit2 { get; set; }
        public decimal boqItemUnitDivider { get; set; }
        public decimal boqItemLineItemRate { get; set; }
        public sbyte? boqItemLineItemRT { get; set; }
        public decimal boqItemEquipmentRate { get; set; }
        public sbyte? boqItemEquipmentRT { get; set; }
        public decimal boqItemSubcontractorRate { get; set; }
        public decimal boqItemSubcontractorQuotedRate { get; set; }
        public sbyte? boqItemSubcontractorRateRT { get; set; }
        public decimal boqItemLaborRate { get; set; }
        public sbyte? boqItemLaborRT { get; set; }
        public decimal boqItemMaterialRate { get; set; }
        public decimal boqItemMaterialQuotedRate { get; set; }
        public sbyte? boqItemMaterialRateRT { get; set; }
        public decimal boqItemConsumableRate { get; set; }
        public sbyte? boqItemConsumableRateRT { get; set; }
        public decimal boqItemFabricationRate { get; set; }
        public decimal boqItemShipmentRate { get; set; }
        public decimal boqItemTotalRate1 { get; set; }
        public decimal boqItemTotalRate2 { get; set; }
        public decimal boqItemPublishedRate { get; set; }
        public decimal boqItemOfferedRate1 { get; set; }
        public decimal boqItemOfferedRate2 { get; set; }
        public decimal boqItemLineItemCost { get; set; }
        public decimal boqItemEquipmentCost { get; set; }
        public decimal boqItemSubcontractorCost { get; set; }
        public decimal boqItemLaborCost { get; set; }
        public decimal boqItemMaterialCost { get; set; }
        public decimal boqItemConsumableCost { get; set; }
        public decimal boqItemFabricationCost { get; set; }
        public decimal boqItemShipmentCost { get; set; }
        public decimal boqItemMaterialResourcesCost { get; set; }
        public decimal boqItemTotalCost { get; set; }
        public decimal boqItemOfferedPrice { get; set; }
        public decimal boqItemMarkup { get; set; }
        public decimal boqItemEscalation { get; set; }
        public string boqItemCustomText1 { get; set; }
        public string boqItemCustomText2 { get; set; }
        public string boqItemCustomText3 { get; set; }
        public string boqItemCustomText4 { get; set; }
        public string boqItemCustomText5 { get; set; }
        public string boqItemCustomText6 { get; set; }
        public string boqItemCustomText7 { get; set; }
        public string boqItemCustomText8 { get; set; }
        public string boqItemCustomText9 { get; set; }
        public string boqItemCustomText10 { get; set; }
        public string boqItemCustomText11 { get; set; }
        public string boqItemCustomText12 { get; set; }
        public string boqItemCustomText13 { get; set; }
        public string boqItemCustomText14 { get; set; }
        public string boqItemCustomText15 { get; set; }
        public string boqItemCustomText16 { get; set; }
        public string boqItemCustomText17 { get; set; }
        public string boqItemCustomText18 { get; set; }
        public string boqItemCustomText19 { get; set; }
        public string boqItemCustomText20 { get; set; }
        public decimal boqItemCustomDecimal1 { get; set; }
        public decimal boqItemCustomDecimal2 { get; set; }
        public decimal boqItemCustomDecimal3 { get; set; }
        public decimal boqItemCustomDecimal4 { get; set; }
        public decimal boqItemCustomDecimal5 { get; set; }
        public decimal boqItemCustomDecimal6 { get; set; }
        public decimal boqItemCustomDecimal7 { get; set; }
        public decimal boqItemCustomDecimal8 { get; set; }
        public decimal boqItemCustomDecimal9 { get; set; }
        public decimal boqItemCustomDecimal10 { get; set; }
        public decimal boqItemCustomCumDecimal1 { get; set; }
        public decimal boqItemCustomCumDecimal2 { get; set; }
        public decimal boqItemCustomCumDecimal3 { get; set; }
        public decimal boqItemCustomCumDecimal4 { get; set; }
        public decimal boqItemCustomCumDecimal5 { get; set; }
        public decimal boqItemCustomPercentange1 { get; set; }
        public decimal boqItemCustomPercentange2 { get; set; }
        public decimal boqItemCustomPercentange3 { get; set; }
        public decimal boqItemCustomPercentange4 { get; set; }
        public decimal boqItemCustomPercentange5 { get; set; }
        public decimal boqItemCustomPercentange6 { get; set; }
        public decimal boqItemCustomPercentange7 { get; set; }
        public decimal boqItemCustomPercentange8 { get; set; }
        public decimal boqItemCustomPercentange9 { get; set; }
        public decimal boqItemCustomPercentange10 { get; set; }
        public string boqItemPublishedItemCode { get; set; }
        public string boqItemPublishedRevisionCode { get; set; }
        public string boqItemWbsCode1 { get; set; }
        public string boqItemWbsCode1Level1Code { get; set; }
        public string boqItemWbsCode1Level2Code { get; set; }
        public string boqItemWbsCode1Level3Code { get; set; }
        public string boqItemWbsCode1Level4Code { get; set; }
        public string boqItemWbsCode1Level5Code { get; set; }
        public string boqItemWbsCode1Level1Title { get; set; }
        public string boqItemWbsCode1Level2Title { get; set; }
        public string boqItemWbsCode1Level3Title { get; set; }
        public string boqItemWbsCode1Level4Title { get; set; }
        public string boqItemWbsCode1Level5Title { get; set; }
        public string boqItemWbsCode2 { get; set; }
        public string boqItemWbsCode2Level1Code { get; set; }
        public string boqItemWbsCode2Level2Code { get; set; }
        public string boqItemWbsCode2Level3Code { get; set; }
        public string boqItemWbsCode2Level4Code { get; set; }
        public string boqItemWbsCode2Level5Code { get; set; }
        public string boqItemWbsCode2Level1Title { get; set; }
        public string boqItemWbsCode2Level2Title { get; set; }
        public string boqItemWbsCode2Level3Title { get; set; }
        public string boqItemWbsCode2Level4Title { get; set; }
        public string boqItemWbsCode2Level5Title { get; set; }
        public string boqItemLocation { get; set; }
        public string boqItemLocationLevel1Code { get; set; }
        public string boqItemLocationLevel2Code { get; set; }
        public string boqItemLocationLevel3Code { get; set; }
        public string boqItemLocationLevel4Code { get; set; }
        public string boqItemLocationLevel5Code { get; set; }
        public string boqItemLocationLevel1Title { get; set; }
        public string boqItemLocationLevel2Title { get; set; }
        public string boqItemLocationLevel3Title { get; set; }
        public string boqItemLocationLevel4Title { get; set; }
        public string boqItemLocationLevel5Title { get; set; }
        public string boqItemGroupCode1 { get; set; }
        public string boqItemGroupCode1Level1Code { get; set; }
        public string boqItemGroupCode1Level2Code { get; set; }
        public string boqItemGroupCode1Level3Code { get; set; }
        public string boqItemGroupCode1Level4Code { get; set; }
        public string boqItemGroupCode1Level5Code { get; set; }
        public string boqItemGroupCode1Level1Title { get; set; }
        public string boqItemGroupCode1Level2Title { get; set; }
        public string boqItemGroupCode1Level3Title { get; set; }
        public string boqItemGroupCode1Level4Title { get; set; }
        public string boqItemGroupCode1Level5Title { get; set; }
        public string boqItemGroupCode1Level1Description { get; set; }
        public string boqItemGroupCode1Level2Description { get; set; }
        public string boqItemGroupCode1Level3Description { get; set; }
        public string boqItemGroupCode1Level4Description { get; set; }
        public string boqItemGroupCode1Level5Description { get; set; }
        public string boqItemGroupCode1Level1Unit { get; set; }
        public string boqItemGroupCode1Level2Unit { get; set; }
        public string boqItemGroupCode1Level3Unit { get; set; }
        public string boqItemGroupCode1Level4Unit { get; set; }
        public string boqItemGroupCode1Level5Unit { get; set; }
        public string boqItemGroupCode2 { get; set; }
        public string boqItemGroupCode2Level1Code { get; set; }
        public string boqItemGroupCode2Level2Code { get; set; }
        public string boqItemGroupCode2Level3Code { get; set; }
        public string boqItemGroupCode2Level4Code { get; set; }
        public string boqItemGroupCode2Level5Code { get; set; }
        public string boqItemGroupCode2Level1Title { get; set; }
        public string boqItemGroupCode2Level2Title { get; set; }
        public string boqItemGroupCode2Level3Title { get; set; }
        public string boqItemGroupCode2Level4Title { get; set; }
        public string boqItemGroupCode2Level5Title { get; set; }
        public string boqItemGroupCode2Level1Description { get; set; }
        public string boqItemGroupCode2Level2Description { get; set; }
        public string boqItemGroupCode2Level3Description { get; set; }
        public string boqItemGroupCode2Level4Description { get; set; }
        public string boqItemGroupCode2Level5Description { get; set; }
        public string boqItemGroupCode2Level1Unit { get; set; }
        public string boqItemGroupCode2Level2Unit { get; set; }
        public string boqItemGroupCode2Level3Unit { get; set; }
        public string boqItemGroupCode2Level4Unit { get; set; }
        public string boqItemGroupCode2Level5Unit { get; set; }
        public string boqItemGroupCode3 { get; set; }
        public string boqItemGroupCode3Level1Code { get; set; }
        public string boqItemGroupCode3Level2Code { get; set; }
        public string boqItemGroupCode3Level3Code { get; set; }
        public string boqItemGroupCode3Level4Code { get; set; }
        public string boqItemGroupCode3Level5Code { get; set; }
        public string boqItemGroupCode3Level1Title { get; set; }
        public string boqItemGroupCode3Level2Title { get; set; }
        public string boqItemGroupCode3Level3Title { get; set; }
        public string boqItemGroupCode3Level4Title { get; set; }
        public string boqItemGroupCode3Level5Title { get; set; }
        public string boqItemGroupCode3Level1Description { get; set; }
        public string boqItemGroupCode3Level2Description { get; set; }
        public string boqItemGroupCode3Level3Description { get; set; }
        public string boqItemGroupCode3Level4Description { get; set; }
        public string boqItemGroupCode3Level5Description { get; set; }
        public string boqItemGroupCode3Level1Unit { get; set; }
        public string boqItemGroupCode3Level2Unit { get; set; }
        public string boqItemGroupCode3Level3Unit { get; set; }
        public string boqItemGroupCode3Level4Unit { get; set; }
        public string boqItemGroupCode3Level5Unit { get; set; }
        public string boqItemGroupCode4 { get; set; }
        public string boqItemGroupCode4Level1Code { get; set; }
        public string boqItemGroupCode4Level2Code { get; set; }
        public string boqItemGroupCode4Level3Code { get; set; }
        public string boqItemGroupCode4Level4Code { get; set; }
        public string boqItemGroupCode4Level5Code { get; set; }
        public string boqItemGroupCode4Level1Title { get; set; }
        public string boqItemGroupCode4Level2Title { get; set; }
        public string boqItemGroupCode4Level3Title { get; set; }
        public string boqItemGroupCode4Level4Title { get; set; }
        public string boqItemGroupCode4Level5Title { get; set; }
        public string boqItemGroupCode4Level1Description { get; set; }
        public string boqItemGroupCode4Level2Description { get; set; }
        public string boqItemGroupCode4Level3Description { get; set; }
        public string boqItemGroupCode4Level4Description { get; set; }
        public string boqItemGroupCode4Level5Description { get; set; }
        public string boqItemGroupCode4Level1Unit { get; set; }
        public string boqItemGroupCode4Level2Unit { get; set; }
        public string boqItemGroupCode4Level3Unit { get; set; }
        public string boqItemGroupCode4Level4Unit { get; set; }
        public string boqItemGroupCode4Level5Unit { get; set; }
        public string boqItemGroupCode5 { get; set; }
        public string boqItemGroupCode5Level1Code { get; set; }
        public string boqItemGroupCode5Level2Code { get; set; }
        public string boqItemGroupCode5Level3Code { get; set; }
        public string boqItemGroupCode5Level4Code { get; set; }
        public string boqItemGroupCode5Level5Code { get; set; }
        public string boqItemGroupCode5Level1Title { get; set; }
        public string boqItemGroupCode5Level2Title { get; set; }
        public string boqItemGroupCode5Level3Title { get; set; }
        public string boqItemGroupCode5Level4Title { get; set; }
        public string boqItemGroupCode5Level5Title { get; set; }
        public string boqItemGroupCode5Level1Description { get; set; }
        public string boqItemGroupCode5Level2Description { get; set; }
        public string boqItemGroupCode5Level3Description { get; set; }
        public string boqItemGroupCode5Level4Description { get; set; }
        public string boqItemGroupCode5Level5Description { get; set; }
        public string boqItemGroupCode5Level1Unit { get; set; }
        public string boqItemGroupCode5Level2Unit { get; set; }
        public string boqItemGroupCode5Level3Unit { get; set; }
        public string boqItemGroupCode5Level4Unit { get; set; }
        public string boqItemGroupCode5Level5Unit { get; set; }
        public string boqItemGroupCode6 { get; set; }
        public string boqItemGroupCode6Level1Code { get; set; }
        public string boqItemGroupCode6Level2Code { get; set; }
        public string boqItemGroupCode6Level3Code { get; set; }
        public string boqItemGroupCode6Level4Code { get; set; }
        public string boqItemGroupCode6Level5Code { get; set; }
        public string boqItemGroupCode6Level1Title { get; set; }
        public string boqItemGroupCode6Level2Title { get; set; }
        public string boqItemGroupCode6Level3Title { get; set; }
        public string boqItemGroupCode6Level4Title { get; set; }
        public string boqItemGroupCode6Level5Title { get; set; }
        public string boqItemGroupCode6Level1Description { get; set; }
        public string boqItemGroupCode6Level2Description { get; set; }
        public string boqItemGroupCode6Level3Description { get; set; }
        public string boqItemGroupCode6Level4Description { get; set; }
        public string boqItemGroupCode6Level5Description { get; set; }
        public string boqItemGroupCode6Level1Unit { get; set; }
        public string boqItemGroupCode6Level2Unit { get; set; }
        public string boqItemGroupCode6Level3Unit { get; set; }
        public string boqItemGroupCode6Level4Unit { get; set; }
        public string boqItemGroupCode6Level5Unit { get; set; }
        public string boqItemGroupCode7 { get; set; }
        public string boqItemGroupCode7Level1Code { get; set; }
        public string boqItemGroupCode7Level2Code { get; set; }
        public string boqItemGroupCode7Level3Code { get; set; }
        public string boqItemGroupCode7Level4Code { get; set; }
        public string boqItemGroupCode7Level5Code { get; set; }
        public string boqItemGroupCode7Level1Title { get; set; }
        public string boqItemGroupCode7Level2Title { get; set; }
        public string boqItemGroupCode7Level3Title { get; set; }
        public string boqItemGroupCode7Level4Title { get; set; }
        public string boqItemGroupCode7Level5Title { get; set; }
        public string boqItemGroupCode7Level1Description { get; set; }
        public string boqItemGroupCode7Level2Description { get; set; }
        public string boqItemGroupCode7Level3Description { get; set; }
        public string boqItemGroupCode7Level4Description { get; set; }
        public string boqItemGroupCode7Level5Description { get; set; }
        public string boqItemGroupCode7Level1Unit { get; set; }
        public string boqItemGroupCode7Level2Unit { get; set; }
        public string boqItemGroupCode7Level3Unit { get; set; }
        public string boqItemGroupCode7Level4Unit { get; set; }
        public string boqItemGroupCode7Level5Unit { get; set; }
        public string boqItemGroupCode8 { get; set; }
        public string boqItemGroupCode8Level1Code { get; set; }
        public string boqItemGroupCode8Level2Code { get; set; }
        public string boqItemGroupCode8Level3Code { get; set; }
        public string boqItemGroupCode8Level4Code { get; set; }
        public string boqItemGroupCode8Level5Code { get; set; }
        public string boqItemGroupCode8Level1Title { get; set; }
        public string boqItemGroupCode8Level2Title { get; set; }
        public string boqItemGroupCode8Level3Title { get; set; }
        public string boqItemGroupCode8Level4Title { get; set; }
        public string boqItemGroupCode8Level5Title { get; set; }
        public string boqItemGroupCode8Level1Description { get; set; }
        public string boqItemGroupCode8Level2Description { get; set; }
        public string boqItemGroupCode8Level3Description { get; set; }
        public string boqItemGroupCode8Level4Description { get; set; }
        public string boqItemGroupCode8Level5Description { get; set; }
        public string boqItemGroupCode8Level1Unit { get; set; }
        public string boqItemGroupCode8Level2Unit { get; set; }
        public string boqItemGroupCode8Level3Unit { get; set; }
        public string boqItemGroupCode8Level4Unit { get; set; }
        public string boqItemGroupCode8Level5Unit { get; set; }
        public string boqItemGroupCode9 { get; set; }
        public string boqItemGroupCode9Level1Code { get; set; }
        public string boqItemGroupCode9Level2Code { get; set; }
        public string boqItemGroupCode9Level3Code { get; set; }
        public string boqItemGroupCode9Level4Code { get; set; }
        public string boqItemGroupCode9Level5Code { get; set; }
        public string boqItemGroupCode9Level1Title { get; set; }
        public string boqItemGroupCode9Level2Title { get; set; }
        public string boqItemGroupCode9Level3Title { get; set; }
        public string boqItemGroupCode9Level4Title { get; set; }
        public string boqItemGroupCode9Level5Title { get; set; }
        public string boqItemGroupCode9Level1Description { get; set; }
        public string boqItemGroupCode9Level2Description { get; set; }
        public string boqItemGroupCode9Level3Description { get; set; }
        public string boqItemGroupCode9Level4Description { get; set; }
        public string boqItemGroupCode9Level5Description { get; set; }
        public string boqItemGroupCode9Level1Unit { get; set; }
        public string boqItemGroupCode9Level2Unit { get; set; }
        public string boqItemGroupCode9Level3Unit { get; set; }
        public string boqItemGroupCode9Level4Unit { get; set; }
        public string boqItemGroupCode9Level5Unit { get; set; }
        public string boqItemDescription { get; set; }
        public string boqItemNotes { get; set; }

        public long? assignmentId { get; set; }
        public decimal assignmentFactor1 { get; set; }
        public decimal assignmentFactor2 { get; set; }
        public decimal assignmentWaste { get; set; }
        public decimal assignmentSelectedQuantity { get; set; }
        public decimal assignmentFinalQuantity { get; set; }
        public string assignmentFinalUnit { get; set; }
        public string assignmentQuantityName { get; set; }
        public decimal assignmentTotalCost { get; set; }
        public decimal assignmentLaborCost { get; set; }
        public decimal assignmentMaterialCost { get; set; }
        public decimal assignmentEquipmentCost { get; set; }
        public decimal assignmentSubcontractorCost { get; set; }
        public decimal assignmentLineItemCost { get; set; }
        public decimal assignmentConsumableCost { get; set; }

        public long? takeoffId { get; set; }
        public string takeoffTitle { get; set; }
        public string takeoffDescription { get; set; }
        public string takeoffBimMaterial { get; set; }
        public string takeoffBimType { get; set; }
        public string takeoffGlobalId { get; set; }
        public string takeoffType { get; set; }
        public string takeoffGroup { get; set; }
        public string takeoffBuilding { get; set; }
        public string takeoffStorey { get; set; }
        public string takeoffLocation { get; set; }
        public string takeoffLayer { get; set; }
        public string takeoffContainer { get; set; }
        public decimal takeoffQuantity1 { get; set; }
        public decimal takeoffQuantity2 { get; set; }
        public decimal takeoffQuantity3 { get; set; }
        public string takeoffQuantity1Name { get; set; }
        public string takeoffQuantity2Name { get; set; }
        public string takeoffQuantity3Name { get; set; }
        public string takeoffUnit1 { get; set; }
        public string takeoffUnit2 { get; set; }
        public string takeoffUnit3 { get; set; }

        public sbyte? boqItemEquipmentRateType { get; set; }
        public sbyte? boqItemAssemblyRateType { get; set; }
        public sbyte? boqItemSubcontractorRateType { get; set; }
        public sbyte? boqItemLaborRateType { get; set; }
        public sbyte? boqItemMaterialRateType { get; set; }
        public sbyte? boqItemConsumableRateType { get; set; }
        public sbyte? boqItemTakeoffQuantityType { get; set; }

        public string boqItemWbsCode1Level1ItemCode { get; set; }
        public string boqItemWbsCode1Level2ItemCode { get; set; }
        public string boqItemWbsCode1Level3ItemCode { get; set; }
        public string boqItemWbsCode1Level4ItemCode { get; set; }
        public string boqItemWbsCode1Level5ItemCode { get; set; }
        public string boqItemWbsCode2Level1ItemCode { get; set; }
        public string boqItemWbsCode2Level2ItemCode { get; set; }
        public string boqItemWbsCode2Level3ItemCode { get; set; }
        public string boqItemWbsCode2Level4ItemCode { get; set; }
        public string boqItemWbsCode2Level5ItemCode { get; set; }

        public BoqItemWithTakeoffsView()
        { }
    }
}