using System;

namespace Models.view
{
    [Serializable]
    public class BoqItemView
    {
        public string projectName { get; set; }
        public string projectCode { get; set; }
        public string projectCurrency { get; set; }
        public string projectCountry { get; set; }
        public string projectClientName { get; set; }
        public string projectSignature { get; set; }
        public string projectDescription { get; set; }
        public string projectClientBudget { get; set; }
        public string projectJobSize { get; set; }
        public string projectUnit { get; set; }
        public string projectBasementSize { get; set; }
        public string projectDuration { get; set; }
        public string projectEPS { get; set; }
        public string projectEPSLevel1Code { get; set; }
        public string projectEPSLevel1Title { get; set; }
        public string projectEPSLevel2Code { get; set; }
        public string projectEPSLevel2Title { get; set; }
        public string projectEPSLevel3Code { get; set; }
        public string projectEPSLevel3Title { get; set; }
        public string projectEPSLevel4Code { get; set; }
        public string projectEPSLevel4Title { get; set; }
        public string projectEPSLevel5Code { get; set; }
        public string projectEPSLevel5Title { get; set; }

        public long? boqitemId { get; set; }
        public long? boqItemCode { get; set; }
        public long? boqItemAssemblyId { get; set; }
        public string boqItemAssemblyTitle { get; set; }
        public string boqItemTitle { get; set; }
        public string boqItemEditorId { get; set; }
        public string boqItemCreateUserId { get; set; }
        public string boqItemEstimator { get; set; }
        public DateTime boqItemPaymentDate { get; set; }
        public DateTime boqItemLastUpdate { get; set; }
        public DateTime boqItemCreateDate { get; set; }
        public string boqItemStatus { get; set; }
        public string boqItemAccuracy { get; set; }
        public int? boqItemFlag { get; set; }
        public string boqItemLocalizationCountry { get; set; }
        public string boqItemLocalizationState { get; set; }
        public string boqItemLocalizationFactor { get; set; }
        public decimal boqItemQuantity1 { get; set; }
        public decimal boqItemQuantity2 { get; set; }
        public decimal boqItemEstimatedQuantity { get; set; }
        public decimal boqItemTakeoffQuantity { get; set; }
        public decimal boqItemQuantityLoss { get; set; }
        public sbyte? boqItemConditionQT { get; set; }
        public bool? boqItemHasProductivity { get; set; }
        public decimal boqItemDuration { get; set; }
        public decimal boqItemProductivity { get; set; }
        public decimal boqItemProductivityFactor { get; set; }
        public decimal boqItemAdjustedProductivity { get; set; }
        public decimal boqItemTotalManHours { get; set; }
        public decimal boqItemUnitManHours { get; set; }
        public decimal boqItemUnitManHoursFactor { get; set; }
        public decimal boqItemEquipmentHours { get; set; }
        public bool? boqItemActivityBased { get; set; }
        public decimal boqItemAdjustedUnitManHours { get; set; }
        public string boqItemUnit1 { get; set; }
        public string boqItemUnit2 { get; set; }
        public decimal boqItemUnitDivider { get; set; }
        public decimal boqItemLineItemRate { get; set; }
        public sbyte? boqItemLineItemRT { get; set; }
        public decimal boqItemEquipmentRate { get; set; }
        public sbyte? boqItemEquipmentRT { get; set; }
        public decimal boqItemSubcontractorRate { get; set; }
        public decimal boqItemSubcontractorQuotedRate { get; set; }
        public sbyte? boqItemSubcontractorRateRT { get; set; }
        public decimal boqItemLaborRate { get; set; }
        public sbyte? boqItemLaborRT { get; set; }
        public decimal boqItemMaterialRate { get; set; }
        public decimal boqItemMaterialQuotedRate { get; set; }
        public sbyte? boqItemMaterialRateRT { get; set; }
        public decimal boqItemConsumableRate { get; set; }
        public sbyte? boqItemConsumableRateRT { get; set; }
        public decimal boqItemFabricationRate { get; set; }
        public decimal boqItemShipmentRate { get; set; }
        public decimal boqItemTotalRate1 { get; set; }
        public decimal boqItemTotalRate2 { get; set; }
        public decimal boqItemPublishedRate { get; set; }
        public decimal boqItemOfferedRate1 { get; set; }
        public decimal boqItemOfferedRate2 { get; set; }
        public decimal boqItemLineItemCost { get; set; }
        public decimal boqItemEquipmentCost { get; set; }
        public decimal boqItemSubcontractorCost { get; set; }
        public decimal boqItemLaborCost { get; set; }
        public decimal boqItemMaterialCost { get; set; }
        public decimal boqItemConsumableCost { get; set; }
        public decimal boqItemFabricationCost { get; set; }
        public decimal boqItemShipmentCost { get; set; }
        public decimal boqItemMaterialResourcesCost { get; set; }
        public decimal boqItemTotalCost { get; set; }
        public decimal boqItemOfferedPrice { get; set; }
        public decimal boqItemMarkup { get; set; }
        public decimal boqItemEscalation { get; set; }
        public decimal boqItemAwardedMaterialRate { get; set; }
        public decimal boqItemAwardedInsuranceRate { get; set; }
        public decimal boqItemAwardedSubcontractorRate { get; set; }
        public decimal boqItemAwardedManhours { get; set; }
        public decimal boqItemAwardedIndirectRate { get; set; }
        public decimal boqItemAwardedShipmentRate { get; set; }
        public decimal boqItemAwardedTotalRate { get; set; }

        public string boqItemCustomText1 { get; set; }
        public string boqItemCustomText2 { get; set; }
        public string boqItemCustomText3 { get; set; }
        public string boqItemCustomText4 { get; set; }
        public string boqItemCustomText5 { get; set; }
        public string boqItemCustomText6 { get; set; }
        public string boqItemCustomText7 { get; set; }
        public string boqItemCustomText8 { get; set; }
        public string boqItemCustomText9 { get; set; }
        public string boqItemCustomText10 { get; set; }
        public string boqItemCustomText11 { get; set; }
        public string boqItemCustomText12 { get; set; }
        public string boqItemCustomText13 { get; set; }
        public string boqItemCustomText14 { get; set; }
        public string boqItemCustomText15 { get; set; }
        public string boqItemCustomText16 { get; set; }
        public string boqItemCustomText17 { get; set; }
        public string boqItemCustomText18 { get; set; }
        public string boqItemCustomText19 { get; set; }
        public string boqItemCustomText20 { get; set; }
        public string boqItemCustomText21 { get; set; }
        public string boqItemCustomText22 { get; set; }
        public string boqItemCustomText23 { get; set; }
        public string boqItemCustomText24 { get; set; }
        public string boqItemCustomText25 { get; set; }

        public decimal boqItemCustomDecimal1 { get; set; }
        public decimal boqItemCustomDecimal2 { get; set; }
        public decimal boqItemCustomDecimal3 { get; set; }
        public decimal boqItemCustomDecimal4 { get; set; }
        public decimal boqItemCustomDecimal5 { get; set; }
        public decimal boqItemCustomDecimal6 { get; set; }
        public decimal boqItemCustomDecimal7 { get; set; }
        public decimal boqItemCustomDecimal8 { get; set; }
        public decimal boqItemCustomDecimal9 { get; set; }
        public decimal boqItemCustomDecimal10 { get; set; }
        public decimal boqItemCustomDecimal11 { get; set; }
        public decimal boqItemCustomDecimal12 { get; set; }
        public decimal boqItemCustomDecimal13 { get; set; }
        public decimal boqItemCustomDecimal14 { get; set; }
        public decimal boqItemCustomDecimal15 { get; set; }
        public decimal boqItemCustomDecimal16 { get; set; }
        public decimal boqItemCustomDecimal17 { get; set; }
        public decimal boqItemCustomDecimal18 { get; set; }
        public decimal boqItemCustomDecimal19 { get; set; }
        public decimal boqItemCustomDecimal20 { get; set; }

        public decimal boqItemCustomCumDecimal1 { get; set; }
        public decimal boqItemCustomCumDecimal2 { get; set; }
        public decimal boqItemCustomCumDecimal3 { get; set; }
        public decimal boqItemCustomCumDecimal4 { get; set; }
        public decimal boqItemCustomCumDecimal5 { get; set; }
        public decimal boqItemCustomCumDecimal6 { get; set; }
        public decimal boqItemCustomCumDecimal7 { get; set; }
        public decimal boqItemCustomCumDecimal8 { get; set; }
        public decimal boqItemCustomCumDecimal9 { get; set; }
        public decimal boqItemCustomCumDecimal10 { get; set; }
        public decimal boqItemCustomCumDecimal11 { get; set; }
        public decimal boqItemCustomCumDecimal12 { get; set; }
        public decimal boqItemCustomCumDecimal13 { get; set; }
        public decimal boqItemCustomCumDecimal14 { get; set; }
        public decimal boqItemCustomCumDecimal15 { get; set; }
        public decimal boqItemCustomCumDecimal16 { get; set; }
        public decimal boqItemCustomCumDecimal17 { get; set; }
        public decimal boqItemCustomCumDecimal18 { get; set; }
        public decimal boqItemCustomCumDecimal19 { get; set; }
        public decimal boqItemCustomCumDecimal20 { get; set; }

        public decimal boqItemCustomPercentange1 { get; set; }
        public decimal boqItemCustomPercentange2 { get; set; }
        public decimal boqItemCustomPercentange3 { get; set; }
        public decimal boqItemCustomPercentange4 { get; set; }
        public decimal boqItemCustomPercentange5 { get; set; }
        public decimal boqItemCustomPercentange6 { get; set; }
        public decimal boqItemCustomPercentange7 { get; set; }
        public decimal boqItemCustomPercentange8 { get; set; }
        public decimal boqItemCustomPercentange9 { get; set; }
        public decimal boqItemCustomPercentange10 { get; set; }
        public decimal boqItemCustomPercentange11 { get; set; }
        public decimal boqItemCustomPercentange12 { get; set; }
        public decimal boqItemCustomPercentange13 { get; set; }
        public decimal boqItemCustomPercentange14 { get; set; }
        public decimal boqItemCustomPercentange15 { get; set; }
        public decimal boqItemCustomPercentange16 { get; set; }
        public decimal boqItemCustomPercentange17 { get; set; }
        public decimal boqItemCustomPercentange18 { get; set; }
        public decimal boqItemCustomPercentange19 { get; set; }
        public decimal boqItemCustomPercentange20 { get; set; }

        public DateTime boqItemCustomDate1 { get; set; }
        public DateTime boqItemCustomDate2 { get; set; }
        public DateTime boqItemCustomDate3 { get; set; }
        public DateTime boqItemCustomDate4 { get; set; }
        public DateTime boqItemCustomDate5 { get; set; }

        public string boqItemPublishedItemCode { get; set; }
        public string boqItemPublishedRevisionCode { get; set; }
        public bool? boqItemScheduled { get; set; }
        public string boqItemWbsCode1 { get; set; }
        public string boqItemWbsCode1Level1Code { get; set; }
        public string boqItemWbsCode1Level2Code { get; set; }
        public string boqItemWbsCode1Level3Code { get; set; }
        public string boqItemWbsCode1Level4Code { get; set; }
        public string boqItemWbsCode1Level5Code { get; set; }
        public string boqItemWbsCode1Level6Code { get; set; }
        public string boqItemWbsCode1Level7Code { get; set; }
        public string boqItemWbsCode1Level8Code { get; set; }
        public string boqItemWbsCode1Level9Code { get; set; }

        public string boqItemWbsCode1Level1Title { get; set; }
        public string boqItemWbsCode1Level2Title { get; set; }
        public string boqItemWbsCode1Level3Title { get; set; }
        public string boqItemWbsCode1Level4Title { get; set; }
        public string boqItemWbsCode1Level5Title { get; set; }
        public string boqItemWbsCode1Level6Title { get; set; }
        public string boqItemWbsCode1Level7Title { get; set; }
        public string boqItemWbsCode1Level8Title { get; set; }
        public string boqItemWbsCode1Level9Title { get; set; }

        public string boqItemWbsCode1Level1Unit { get; set; }
        public string boqItemWbsCode1Level2Unit { get; set; }
        public string boqItemWbsCode1Level3Unit { get; set; }
        public string boqItemWbsCode1Level4Unit { get; set; }
        public string boqItemWbsCode1Level5Unit { get; set; }
        public string boqItemWbsCode1Level6Unit { get; set; }
        public string boqItemWbsCode1Level7Unit { get; set; }
        public string boqItemWbsCode1Level8Unit { get; set; }
        public string boqItemWbsCode1Level9Unit { get; set; }

        public string boqItemWbsCode1Level1Quantity { get; set; }
        public string boqItemWbsCode1Level2Quantity { get; set; }
        public string boqItemWbsCode1Level3Quantity { get; set; }
        public string boqItemWbsCode1Level4Quantity { get; set; }
        public string boqItemWbsCode1Level5Quantity { get; set; }
        public string boqItemWbsCode1Level6Quantity { get; set; }
        public string boqItemWbsCode1Level7Quantity { get; set; }
        public string boqItemWbsCode1Level8Quantity { get; set; }
        public string boqItemWbsCode1Level9Quantity { get; set; }

        public string boqItemWbsCode2 { get; set; }
        public string boqItemWbsCode2Level1Code { get; set; }
        public string boqItemWbsCode2Level2Code { get; set; }
        public string boqItemWbsCode2Level3Code { get; set; }
        public string boqItemWbsCode2Level4Code { get; set; }
        public string boqItemWbsCode2Level5Code { get; set; }
        public string boqItemWbsCode2Level6Code { get; set; }
        public string boqItemWbsCode2Level7Code { get; set; }
        public string boqItemWbsCode2Level8Code { get; set; }
        public string boqItemWbsCode2Level9Code { get; set; }

        public string boqItemWbsCode2Level1Unit { get; set; }
        public string boqItemWbsCode2Level2Unit { get; set; }
        public string boqItemWbsCode2Level3Unit { get; set; }
        public string boqItemWbsCode2Level4Unit { get; set; }
        public string boqItemWbsCode2Level5Unit { get; set; }
        public string boqItemWbsCode2Level6Unit { get; set; }
        public string boqItemWbsCode2Level7Unit { get; set; }
        public string boqItemWbsCode2Level8Unit { get; set; }
        public string boqItemWbsCode2Level9Unit { get; set; }

        public string boqItemWbsCode2Level1Quantity { get; set; }
        public string boqItemWbsCode2Level2Quantity { get; set; }
        public string boqItemWbsCode2Level3Quantity { get; set; }
        public string boqItemWbsCode2Level4Quantity { get; set; }
        public string boqItemWbsCode2Level5Quantity { get; set; }
        public string boqItemWbsCode2Level6Quantity { get; set; }
        public string boqItemWbsCode2Level7Quantity { get; set; }
        public string boqItemWbsCode2Level8Quantity { get; set; }
        public string boqItemWbsCode2Level9Quantity { get; set; }

        public string boqItemWbsCode2Level1Title { get; set; }
        public string boqItemWbsCode2Level2Title { get; set; }
        public string boqItemWbsCode2Level3Title { get; set; }
        public string boqItemWbsCode2Level4Title { get; set; }
        public string boqItemWbsCode2Level5Title { get; set; }
        public string boqItemWbsCode2Level6Title { get; set; }
        public string boqItemWbsCode2Level7Title { get; set; }
        public string boqItemWbsCode2Level8Title { get; set; }
        public string boqItemWbsCode2Level9Title { get; set; }

        public string boqItemLocation { get; set; }
        public string boqItemLocationLevel1Code { get; set; }
        public string boqItemLocationLevel2Code { get; set; }
        public string boqItemLocationLevel3Code { get; set; }
        public string boqItemLocationLevel4Code { get; set; }
        public string boqItemLocationLevel5Code { get; set; }
        public string boqItemLocationLevel6Code { get; set; }
        public string boqItemLocationLevel7Code { get; set; }
        public string boqItemLocationLevel8Code { get; set; }
        public string boqItemLocationLevel9Code { get; set; }

        public string boqItemLocationLevel1Title { get; set; }
        public string boqItemLocationLevel2Title { get; set; }
        public string boqItemLocationLevel3Title { get; set; }
        public string boqItemLocationLevel4Title { get; set; }
        public string boqItemLocationLevel5Title { get; set; }
        public string boqItemLocationLevel6Title { get; set; }
        public string boqItemLocationLevel7Title { get; set; }
        public string boqItemLocationLevel8Title { get; set; }
        public string boqItemLocationLevel9Title { get; set; }

        public string boqItemWbsCode1Level1ItemCode { get; set; }
        public string boqItemWbsCode1Level2ItemCode { get; set; }
        public string boqItemWbsCode1Level3ItemCode { get; set; }
        public string boqItemWbsCode1Level4ItemCode { get; set; }
        public string boqItemWbsCode1Level5ItemCode { get; set; }
        public string boqItemWbsCode1Level6ItemCode { get; set; }
        public string boqItemWbsCode1Level7ItemCode { get; set; }
        public string boqItemWbsCode1Level8ItemCode { get; set; }
        public string boqItemWbsCode1Level9ItemCode { get; set; }

        public string boqItemWbsCode2Level1ItemCode { get; set; }
        public string boqItemWbsCode2Level2ItemCode { get; set; }
        public string boqItemWbsCode2Level3ItemCode { get; set; }
        public string boqItemWbsCode2Level4ItemCode { get; set; }
        public string boqItemWbsCode2Level5ItemCode { get; set; }
        public string boqItemWbsCode2Level6ItemCode { get; set; }
        public string boqItemWbsCode2Level7ItemCode { get; set; }
        public string boqItemWbsCode2Level8ItemCode { get; set; }
        public string boqItemWbsCode2Level9ItemCode { get; set; }

        public string boqItemGroupCode1 { get; set; }
        public string boqItemGroupCode1Level1Code { get; set; }
        public string boqItemGroupCode1Level2Code { get; set; }
        public string boqItemGroupCode1Level3Code { get; set; }
        public string boqItemGroupCode1Level4Code { get; set; }
        public string boqItemGroupCode1Level5Code { get; set; }
        public string boqItemGroupCode1Level6Code { get; set; }
        public string boqItemGroupCode1Level7Code { get; set; }
        public string boqItemGroupCode1Level8Code { get; set; }
        public string boqItemGroupCode1Level9Code { get; set; }

        public string boqItemGroupCode1Level1Title { get; set; }
        public string boqItemGroupCode1Level2Title { get; set; }
        public string boqItemGroupCode1Level3Title { get; set; }
        public string boqItemGroupCode1Level4Title { get; set; }
        public string boqItemGroupCode1Level5Title { get; set; }
        public string boqItemGroupCode1Level6Title { get; set; }
        public string boqItemGroupCode1Level7Title { get; set; }
        public string boqItemGroupCode1Level8Title { get; set; }
        public string boqItemGroupCode1Level9Title { get; set; }

        public string boqItemGroupCode1Level1Description { get; set; }
        public string boqItemGroupCode1Level2Description { get; set; }
        public string boqItemGroupCode1Level3Description { get; set; }
        public string boqItemGroupCode1Level4Description { get; set; }
        public string boqItemGroupCode1Level5Description { get; set; }
        public string boqItemGroupCode1Level6Description { get; set; }
        public string boqItemGroupCode1Level7Description { get; set; }
        public string boqItemGroupCode1Level8Description { get; set; }
        public string boqItemGroupCode1Level9Description { get; set; }

        public string boqItemGroupCode1Level1Unit { get; set; }
        public string boqItemGroupCode1Level2Unit { get; set; }
        public string boqItemGroupCode1Level3Unit { get; set; }
        public string boqItemGroupCode1Level4Unit { get; set; }
        public string boqItemGroupCode1Level5Unit { get; set; }
        public string boqItemGroupCode1Level6Unit { get; set; }
        public string boqItemGroupCode1Level7Unit { get; set; }
        public string boqItemGroupCode1Level8Unit { get; set; }
        public string boqItemGroupCode1Level9Unit { get; set; }

        public decimal boqItemGroupCode1UnitFactor { get; set; }
        public decimal boqItemGroupCode2UnitFactor { get; set; }
        public decimal boqItemGroupCode3UnitFactor { get; set; }
        public decimal boqItemGroupCode4UnitFactor { get; set; }
        public decimal boqItemGroupCode5UnitFactor { get; set; }
        public decimal boqItemGroupCode6UnitFactor { get; set; }
        public decimal boqItemGroupCode7UnitFactor { get; set; }
        public decimal boqItemGroupCode8UnitFactor { get; set; }
        public decimal boqItemGroupCode9UnitFactor { get; set; }

        public decimal boqItemGroupCode1Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode1Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode1Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode1Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode1Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode1Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode1Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode1Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode1Level9UnitFactor { get; set; }

        public string boqItemGroupCode2 { get; set; }
        public string boqItemGroupCode2Level1Code { get; set; }
        public string boqItemGroupCode2Level2Code { get; set; }
        public string boqItemGroupCode2Level3Code { get; set; }
        public string boqItemGroupCode2Level4Code { get; set; }
        public string boqItemGroupCode2Level5Code { get; set; }
        public string boqItemGroupCode2Level6Code { get; set; }
        public string boqItemGroupCode2Level7Code { get; set; }
        public string boqItemGroupCode2Level8Code { get; set; }
        public string boqItemGroupCode2Level9Code { get; set; }

        public string boqItemGroupCode2Level1Title { get; set; }
        public string boqItemGroupCode2Level2Title { get; set; }
        public string boqItemGroupCode2Level3Title { get; set; }
        public string boqItemGroupCode2Level4Title { get; set; }
        public string boqItemGroupCode2Level5Title { get; set; }
        public string boqItemGroupCode2Level6Title { get; set; }
        public string boqItemGroupCode2Level7Title { get; set; }
        public string boqItemGroupCode2Level8Title { get; set; }
        public string boqItemGroupCode2Level9Title { get; set; }

        public string boqItemGroupCode2Level1Description { get; set; }
        public string boqItemGroupCode2Level2Description { get; set; }
        public string boqItemGroupCode2Level3Description { get; set; }
        public string boqItemGroupCode2Level4Description { get; set; }
        public string boqItemGroupCode2Level5Description { get; set; }
        public string boqItemGroupCode2Level6Description { get; set; }
        public string boqItemGroupCode2Level7Description { get; set; }
        public string boqItemGroupCode2Level8Description { get; set; }
        public string boqItemGroupCode2Level9Description { get; set; }

        public string boqItemGroupCode2Level1Unit { get; set; }
        public string boqItemGroupCode2Level2Unit { get; set; }
        public string boqItemGroupCode2Level3Unit { get; set; }
        public string boqItemGroupCode2Level4Unit { get; set; }
        public string boqItemGroupCode2Level5Unit { get; set; }
        public string boqItemGroupCode2Level6Unit { get; set; }
        public string boqItemGroupCode2Level7Unit { get; set; }
        public string boqItemGroupCode2Level8Unit { get; set; }
        public string boqItemGroupCode2Level9Unit { get; set; }

        public decimal boqItemGroupCode2Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode2Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode2Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode2Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode2Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode2Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode2Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode2Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode2Level9UnitFactor { get; set; }

        public string boqItemGroupCode3 { get; set; }
        public string boqItemGroupCode3Level1Code { get; set; }
        public string boqItemGroupCode3Level2Code { get; set; }
        public string boqItemGroupCode3Level3Code { get; set; }
        public string boqItemGroupCode3Level4Code { get; set; }
        public string boqItemGroupCode3Level5Code { get; set; }
        public string boqItemGroupCode3Level6Code { get; set; }
        public string boqItemGroupCode3Level7Code { get; set; }
        public string boqItemGroupCode3Level8Code { get; set; }
        public string boqItemGroupCode3Level9Code { get; set; }

        public string boqItemGroupCode3Level1Title { get; set; }
        public string boqItemGroupCode3Level2Title { get; set; }
        public string boqItemGroupCode3Level3Title { get; set; }
        public string boqItemGroupCode3Level4Title { get; set; }
        public string boqItemGroupCode3Level5Title { get; set; }
        public string boqItemGroupCode3Level6Title { get; set; }
        public string boqItemGroupCode3Level7Title { get; set; }
        public string boqItemGroupCode3Level8Title { get; set; }
        public string boqItemGroupCode3Level9Title { get; set; }

        public string boqItemGroupCode3Level1Description { get; set; }
        public string boqItemGroupCode3Level2Description { get; set; }
        public string boqItemGroupCode3Level3Description { get; set; }
        public string boqItemGroupCode3Level4Description { get; set; }
        public string boqItemGroupCode3Level5Description { get; set; }
        public string boqItemGroupCode3Level6Description { get; set; }
        public string boqItemGroupCode3Level7Description { get; set; }
        public string boqItemGroupCode3Level8Description { get; set; }
        public string boqItemGroupCode3Level9Description { get; set; }

        public string boqItemGroupCode3Level1Unit { get; set; }
        public string boqItemGroupCode3Level2Unit { get; set; }
        public string boqItemGroupCode3Level3Unit { get; set; }
        public string boqItemGroupCode3Level4Unit { get; set; }
        public string boqItemGroupCode3Level5Unit { get; set; }
        public string boqItemGroupCode3Level6Unit { get; set; }
        public string boqItemGroupCode3Level7Unit { get; set; }
        public string boqItemGroupCode3Level8Unit { get; set; }
        public string boqItemGroupCode3Level9Unit { get; set; }

        public decimal boqItemGroupCode3Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode3Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode3Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode3Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode3Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode3Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode3Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode3Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode3Level9UnitFactor { get; set; }

        public string boqItemGroupCode4 { get; set; }
        public string boqItemGroupCode4Level1Code { get; set; }
        public string boqItemGroupCode4Level2Code { get; set; }
        public string boqItemGroupCode4Level3Code { get; set; }
        public string boqItemGroupCode4Level4Code { get; set; }
        public string boqItemGroupCode4Level5Code { get; set; }
        public string boqItemGroupCode4Level6Code { get; set; }
        public string boqItemGroupCode4Level7Code { get; set; }
        public string boqItemGroupCode4Level8Code { get; set; }
        public string boqItemGroupCode4Level9Code { get; set; }

        public string boqItemGroupCode4Level1Title { get; set; }
        public string boqItemGroupCode4Level2Title { get; set; }
        public string boqItemGroupCode4Level3Title { get; set; }
        public string boqItemGroupCode4Level4Title { get; set; }
        public string boqItemGroupCode4Level5Title { get; set; }
        public string boqItemGroupCode4Level6Title { get; set; }
        public string boqItemGroupCode4Level7Title { get; set; }
        public string boqItemGroupCode4Level8Title { get; set; }
        public string boqItemGroupCode4Level9Title { get; set; }

        public string boqItemGroupCode4Level1Description { get; set; }
        public string boqItemGroupCode4Level2Description { get; set; }
        public string boqItemGroupCode4Level3Description { get; set; }
        public string boqItemGroupCode4Level4Description { get; set; }
        public string boqItemGroupCode4Level5Description { get; set; }
        public string boqItemGroupCode4Level6Description { get; set; }
        public string boqItemGroupCode4Level7Description { get; set; }
        public string boqItemGroupCode4Level8Description { get; set; }
        public string boqItemGroupCode4Level9Description { get; set; }

        public string boqItemGroupCode4Level1Unit { get; set; }
        public string boqItemGroupCode4Level2Unit { get; set; }
        public string boqItemGroupCode4Level3Unit { get; set; }
        public string boqItemGroupCode4Level4Unit { get; set; }
        public string boqItemGroupCode4Level5Unit { get; set; }
        public string boqItemGroupCode4Level6Unit { get; set; }
        public string boqItemGroupCode4Level7Unit { get; set; }
        public string boqItemGroupCode4Level8Unit { get; set; }
        public string boqItemGroupCode4Level9Unit { get; set; }

        public decimal boqItemGroupCode4Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode4Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode4Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode4Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode4Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode4Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode4Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode4Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode4Level9UnitFactor { get; set; }

        public string boqItemGroupCode5 { get; set; }
        public string boqItemGroupCode5Level1Code { get; set; }
        public string boqItemGroupCode5Level2Code { get; set; }
        public string boqItemGroupCode5Level3Code { get; set; }
        public string boqItemGroupCode5Level4Code { get; set; }
        public string boqItemGroupCode5Level5Code { get; set; }
        public string boqItemGroupCode5Level6Code { get; set; }
        public string boqItemGroupCode5Level7Code { get; set; }
        public string boqItemGroupCode5Level8Code { get; set; }
        public string boqItemGroupCode5Level9Code { get; set; }

        public string boqItemGroupCode5Level1Title { get; set; }
        public string boqItemGroupCode5Level2Title { get; set; }
        public string boqItemGroupCode5Level3Title { get; set; }
        public string boqItemGroupCode5Level4Title { get; set; }
        public string boqItemGroupCode5Level5Title { get; set; }
        public string boqItemGroupCode5Level6Title { get; set; }
        public string boqItemGroupCode5Level7Title { get; set; }
        public string boqItemGroupCode5Level8Title { get; set; }
        public string boqItemGroupCode5Level9Title { get; set; }

        public string boqItemGroupCode5Level1Description { get; set; }
        public string boqItemGroupCode5Level2Description { get; set; }
        public string boqItemGroupCode5Level3Description { get; set; }
        public string boqItemGroupCode5Level4Description { get; set; }
        public string boqItemGroupCode5Level5Description { get; set; }
        public string boqItemGroupCode5Level6Description { get; set; }
        public string boqItemGroupCode5Level7Description { get; set; }
        public string boqItemGroupCode5Level8Description { get; set; }
        public string boqItemGroupCode5Level9Description { get; set; }

        public string boqItemGroupCode5Level1Unit { get; set; }
        public string boqItemGroupCode5Level2Unit { get; set; }
        public string boqItemGroupCode5Level3Unit { get; set; }
        public string boqItemGroupCode5Level4Unit { get; set; }
        public string boqItemGroupCode5Level5Unit { get; set; }
        public string boqItemGroupCode5Level6Unit { get; set; }
        public string boqItemGroupCode5Level7Unit { get; set; }
        public string boqItemGroupCode5Level8Unit { get; set; }
        public string boqItemGroupCode5Level9Unit { get; set; }

        public decimal boqItemGroupCode5Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode5Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode5Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode5Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode5Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode5Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode5Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode5Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode5Level9UnitFactor { get; set; }

        public string boqItemGroupCode6 { get; set; }
        public string boqItemGroupCode6Level1Code { get; set; }
        public string boqItemGroupCode6Level2Code { get; set; }
        public string boqItemGroupCode6Level3Code { get; set; }
        public string boqItemGroupCode6Level4Code { get; set; }
        public string boqItemGroupCode6Level5Code { get; set; }
        public string boqItemGroupCode6Level6Code { get; set; }
        public string boqItemGroupCode6Level7Code { get; set; }
        public string boqItemGroupCode6Level8Code { get; set; }
        public string boqItemGroupCode6Level9Code { get; set; }

        public string boqItemGroupCode6Level1Title { get; set; }
        public string boqItemGroupCode6Level2Title { get; set; }
        public string boqItemGroupCode6Level3Title { get; set; }
        public string boqItemGroupCode6Level4Title { get; set; }
        public string boqItemGroupCode6Level5Title { get; set; }
        public string boqItemGroupCode6Level6Title { get; set; }
        public string boqItemGroupCode6Level7Title { get; set; }
        public string boqItemGroupCode6Level8Title { get; set; }
        public string boqItemGroupCode6Level9Title { get; set; }

        public string boqItemGroupCode6Level1Description { get; set; }
        public string boqItemGroupCode6Level2Description { get; set; }
        public string boqItemGroupCode6Level3Description { get; set; }
        public string boqItemGroupCode6Level4Description { get; set; }
        public string boqItemGroupCode6Level5Description { get; set; }
        public string boqItemGroupCode6Level6Description { get; set; }
        public string boqItemGroupCode6Level7Description { get; set; }
        public string boqItemGroupCode6Level8Description { get; set; }
        public string boqItemGroupCode6Level9Description { get; set; }

        public string boqItemGroupCode6Level1Unit { get; set; }
        public string boqItemGroupCode6Level2Unit { get; set; }
        public string boqItemGroupCode6Level3Unit { get; set; }
        public string boqItemGroupCode6Level4Unit { get; set; }
        public string boqItemGroupCode6Level5Unit { get; set; }
        public string boqItemGroupCode6Level6Unit { get; set; }
        public string boqItemGroupCode6Level7Unit { get; set; }
        public string boqItemGroupCode6Level8Unit { get; set; }
        public string boqItemGroupCode6Level9Unit { get; set; }

        public decimal boqItemGroupCode6Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode6Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode6Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode6Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode6Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode6Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode6Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode6Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode6Level9UnitFactor { get; set; }

        public string boqItemGroupCode7 { get; set; }
        public string boqItemGroupCode7Level1Code { get; set; }
        public string boqItemGroupCode7Level2Code { get; set; }
        public string boqItemGroupCode7Level3Code { get; set; }
        public string boqItemGroupCode7Level4Code { get; set; }
        public string boqItemGroupCode7Level5Code { get; set; }
        public string boqItemGroupCode7Level6Code { get; set; }
        public string boqItemGroupCode7Level7Code { get; set; }
        public string boqItemGroupCode7Level8Code { get; set; }
        public string boqItemGroupCode7Level9Code { get; set; }

        public string boqItemGroupCode7Level1Title { get; set; }
        public string boqItemGroupCode7Level2Title { get; set; }
        public string boqItemGroupCode7Level3Title { get; set; }
        public string boqItemGroupCode7Level4Title { get; set; }
        public string boqItemGroupCode7Level5Title { get; set; }
        public string boqItemGroupCode7Level6Title { get; set; }
        public string boqItemGroupCode7Level7Title { get; set; }
        public string boqItemGroupCode7Level8Title { get; set; }
        public string boqItemGroupCode7Level9Title { get; set; }

        public string boqItemGroupCode7Level1Description { get; set; }
        public string boqItemGroupCode7Level2Description { get; set; }
        public string boqItemGroupCode7Level3Description { get; set; }
        public string boqItemGroupCode7Level4Description { get; set; }
        public string boqItemGroupCode7Level5Description { get; set; }
        public string boqItemGroupCode7Level6Description { get; set; }
        public string boqItemGroupCode7Level7Description { get; set; }
        public string boqItemGroupCode7Level8Description { get; set; }
        public string boqItemGroupCode7Level9Description { get; set; }

        public string boqItemGroupCode7Level1Unit { get; set; }
        public string boqItemGroupCode7Level2Unit { get; set; }
        public string boqItemGroupCode7Level3Unit { get; set; }
        public string boqItemGroupCode7Level4Unit { get; set; }
        public string boqItemGroupCode7Level5Unit { get; set; }
        public string boqItemGroupCode7Level6Unit { get; set; }
        public string boqItemGroupCode7Level7Unit { get; set; }
        public string boqItemGroupCode7Level8Unit { get; set; }
        public string boqItemGroupCode7Level9Unit { get; set; }

        public decimal boqItemGroupCode7Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode7Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode7Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode7Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode7Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode7Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode7Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode7Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode7Level9UnitFactor { get; set; }

        public string boqItemGroupCode8 { get; set; }
        public string boqItemGroupCode8Level1Code { get; set; }
        public string boqItemGroupCode8Level2Code { get; set; }
        public string boqItemGroupCode8Level3Code { get; set; }
        public string boqItemGroupCode8Level4Code { get; set; }
        public string boqItemGroupCode8Level5Code { get; set; }
        public string boqItemGroupCode8Level6Code { get; set; }
        public string boqItemGroupCode8Level7Code { get; set; }
        public string boqItemGroupCode8Level8Code { get; set; }
        public string boqItemGroupCode8Level9Code { get; set; }

        public string boqItemGroupCode8Level1Title { get; set; }
        public string boqItemGroupCode8Level2Title { get; set; }
        public string boqItemGroupCode8Level3Title { get; set; }
        public string boqItemGroupCode8Level4Title { get; set; }
        public string boqItemGroupCode8Level5Title { get; set; }
        public string boqItemGroupCode8Level6Title { get; set; }
        public string boqItemGroupCode8Level7Title { get; set; }
        public string boqItemGroupCode8Level8Title { get; set; }
        public string boqItemGroupCode8Level9Title { get; set; }


        public string boqItemGroupCode8Level1Description { get; set; }
        public string boqItemGroupCode8Level2Description { get; set; }
        public string boqItemGroupCode8Level3Description { get; set; }
        public string boqItemGroupCode8Level4Description { get; set; }
        public string boqItemGroupCode8Level5Description { get; set; }
        public string boqItemGroupCode8Level6Description { get; set; }
        public string boqItemGroupCode8Level7Description { get; set; }
        public string boqItemGroupCode8Level8Description { get; set; }
        public string boqItemGroupCode8Level9Description { get; set; }

        public string boqItemGroupCode8Level1Unit { get; set; }
        public string boqItemGroupCode8Level2Unit { get; set; }
        public string boqItemGroupCode8Level3Unit { get; set; }
        public string boqItemGroupCode8Level4Unit { get; set; }
        public string boqItemGroupCode8Level5Unit { get; set; }
        public string boqItemGroupCode8Level6Unit { get; set; }
        public string boqItemGroupCode8Level7Unit { get; set; }
        public string boqItemGroupCode8Level8Unit { get; set; }
        public string boqItemGroupCode8Level9Unit { get; set; }

        public decimal boqItemGroupCode8Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode8Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode8Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode8Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode8Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode8Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode8Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode8Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode8Level9UnitFactor { get; set; }

        public string boqItemGroupCode9 { get; set; }
        public string boqItemGroupCode9Level1Code { get; set; }
        public string boqItemGroupCode9Level2Code { get; set; }
        public string boqItemGroupCode9Level3Code { get; set; }
        public string boqItemGroupCode9Level4Code { get; set; }
        public string boqItemGroupCode9Level5Code { get; set; }
        public string boqItemGroupCode9Level6Code { get; set; }
        public string boqItemGroupCode9Level7Code { get; set; }
        public string boqItemGroupCode9Level8Code { get; set; }
        public string boqItemGroupCode9Level9Code { get; set; }

        public string boqItemGroupCode9Level1Title { get; set; }
        public string boqItemGroupCode9Level2Title { get; set; }
        public string boqItemGroupCode9Level3Title { get; set; }
        public string boqItemGroupCode9Level4Title { get; set; }
        public string boqItemGroupCode9Level5Title { get; set; }
        public string boqItemGroupCode9Level6Title { get; set; }
        public string boqItemGroupCode9Level7Title { get; set; }
        public string boqItemGroupCode9Level8Title { get; set; }
        public string boqItemGroupCode9Level9Title { get; set; }

        public string boqItemGroupCode9Level1Description { get; set; }
        public string boqItemGroupCode9Level2Description { get; set; }
        public string boqItemGroupCode9Level3Description { get; set; }
        public string boqItemGroupCode9Level4Description { get; set; }
        public string boqItemGroupCode9Level5Description { get; set; }
        public string boqItemGroupCode9Level6Description { get; set; }
        public string boqItemGroupCode9Level7Description { get; set; }
        public string boqItemGroupCode9Level8Description { get; set; }
        public string boqItemGroupCode9Level9Description { get; set; }

        public string boqItemGroupCode9Level1Unit { get; set; }
        public string boqItemGroupCode9Level2Unit { get; set; }
        public string boqItemGroupCode9Level3Unit { get; set; }
        public string boqItemGroupCode9Level4Unit { get; set; }
        public string boqItemGroupCode9Level5Unit { get; set; }
        public string boqItemGroupCode9Level6Unit { get; set; }
        public string boqItemGroupCode9Level7Unit { get; set; }
        public string boqItemGroupCode9Level8Unit { get; set; }
        public string boqItemGroupCode9Level9Unit { get; set; }

        public decimal boqItemGroupCode9Level1UnitFactor { get; set; }
        public decimal boqItemGroupCode9Level2UnitFactor { get; set; }
        public decimal boqItemGroupCode9Level3UnitFactor { get; set; }
        public decimal boqItemGroupCode9Level4UnitFactor { get; set; }
        public decimal boqItemGroupCode9Level5UnitFactor { get; set; }
        public decimal boqItemGroupCode9Level6UnitFactor { get; set; }
        public decimal boqItemGroupCode9Level7UnitFactor { get; set; }
        public decimal boqItemGroupCode9Level8UnitFactor { get; set; }
        public decimal boqItemGroupCode9Level9UnitFactor { get; set; }

        public string boqItemDescription { get; set; }
        public string boqItemNotes { get; set; }
        public sbyte? boqItemEquipmentRateType { get; set; }
        public sbyte? boqItemAssemblyRateType { get; set; }
        public sbyte? boqItemSubcontractorRateType { get; set; }
        public sbyte? boqItemLaborRateType { get; set; }
        public sbyte? boqItemMaterialRateType { get; set; }
        public sbyte? boqItemConsumableRateType { get; set; }
        public sbyte? boqItemTakeoffQuantityType { get; set; }

        public BoqItemView()
        { }
    }
}