CREATE TABLE [dbo].[ASSEMBLY_LABOR] (
    [ASSEMBLYLABORID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [LASTUPDATE]      DATETIME2 (7)    NULL,
    [FRATE]           NUMERIC (30, 10) NULL,
    [FIKARATE]        NUMERIC (30, 10) NULL,
    [FACTOR1]         NUMERIC (30, 10) NULL,
    [FACTOR2]         NUMERIC (30, 10) NULL,
    [FACTOR3]         NUMERIC (30, 10) NULL,
    [QTYPUNIT]        NUMERIC (30, 10) NULL,
    [QTYPUNITFORM]    NVARCHAR (MAX)   NULL,
    [QTYPUFORMSTATE]  TINYINT          NULL,
    [LOCALFACTOR]     NUMERIC (30, 10) NULL,
    [LOCALCOUNTRY]    NVARCHAR (255)   NULL,
    [LOCALSTATE]      NVARCHAR (255)   NULL,
    [EXCHANGERATE]    NUMERIC (30, 10) NULL,
    [FIXEDCOST]       NUMERIC (30, 10) NULL,
    [FINALFIXEDCOST]  NUMERIC (30, 10) NULL,
    [UNITHOURS]       NUMERIC (30, 10) NULL,
    [PV_VARS]         NVARCHAR (MAX)   NULL,
    [LABORID]         BIGINT           NULL,
    [ASSEMBLYID]      BIGINT           NULL,
    [PRJID]           BIGINT           NULL,
    [REF__ID]         BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([ASSEMBLYLABORID] ASC),
    CONSTRAINT [FKE311947714030E1E] FOREIGN KEY ([ASSEMBLYID]) REFERENCES [dbo].[ASSEMBLY] ([ASSEMBLYID]),
    CONSTRAINT [FKE31194775C7E33D4] FOREIGN KEY ([LABORID]) REFERENCES [dbo].[LABOR] ([LABORID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSEMBLY]
    ON [dbo].[ASSEMBLY_LABOR]([ASSEMBLYID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_LABOR]
    ON [dbo].[ASSEMBLY_LABOR]([LABORID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[ASSEMBLY_LABOR]([PRJID] ASC);

