CREATE TABLE [dbo].[ASSEMBLY_CHILD] (
    [ASSEMBLYCHILDID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [LASTUPDATE]      DATETIME2 (7)    NULL,
    [FRATE]           NUMERIC (30, 10) NULL,
    [FACTOR1]         NUMERIC (30, 10) NULL,
    [FACTOR2]         NUMERIC (30, 10) NULL,
    [DIVIDER]         NUMERIC (30, 10) NULL,
    [QTYPUNIT]        NUMERIC (30, 10) NULL,
    [QTYPUNITFORM]    NVARCHAR (MAX)   NULL,
    [QTYPUFORMSTATE]  TINYINT          NULL,
    [LOCALFACTOR]     NUMERIC (30, 10) NULL,
    [LOCALCOUNTRY]    NVARCHAR (255)   NULL,
    [LOCALSTATE]      NVARCHAR (255)   NULL,
    [EXCHANGERATE]    NUMERIC (30, 10) NULL,
    [FIXEDCOST]       NUMERIC (30, 10) NULL,
    [FINALFIXEDCOST]  NUMERIC (30, 10) NULL,
    [PV_VARS]         NVARCHAR (MAX)   NULL,
    [CHILDID]         BIGINT           NULL,
    [ASSEMBLYID]      BIGINT           NULL,
    [PRJID]           BIGINT           NULL,
    [REF__ID]         BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([ASSEMBLYCHILDID] ASC),
    CONSTRAINT [FKE296096314030E1E] FOREIGN KEY ([ASSEMBLYID]) REFERENCES [dbo].[ASSEMBLY] ([ASSEMBLYID]),
    CONSTRAINT [FKE2960963CD57CFD4] FOREIGN KEY ([CHILDID]) REFERENCES [dbo].[ASSEMBLY] ([ASSEMBLYID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSEMBLY]
    ON [dbo].[ASSEMBLY_CHILD]([ASSEMBLYID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSEMBLY_CHILD]
    ON [dbo].[ASSEMBLY_CHILD]([CHILDID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[ASSEMBLY_CHILD]([PRJID] ASC);

