CREATE TABLE [dbo].[ASSHISTORY] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [ASSEMLBYID]  BIGINT         NULL,
    [BASETABLEID] NVARCHAR (255) NULL,
    [RSRC]        NVARCHAR (MAX) NULL,
    [PREDDATE]    DATETIME2 (7)  NULL,
    [PRJID]       BIGINT         NULL,
    [ASSEMBLYID]  BIGINT         NULL,
    [REF__ID]     BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK28E2B2F314030E1E] FOREIGN KEY ([ASSEMBLYID]) REFERENCES [dbo].[ASSEMBLY] ([ASSEMBLYID]),
    CONSTRAINT [FK28E2B2F3148B6D72] FOREIGN KEY ([ASSEMLBYID]) REFERENCES [dbo].[ASSEMBLY] ([ASSEMBLYID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSEMBLY]
    ON [dbo].[ASSHISTORY]([ASSEMLBYID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[ASSHISTORY]([PRJID] ASC);

