CREATE TABLE [dbo].[BOQITEM_CONSUMABLE] (
    [BOQITEMCONSUMABLEID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [FRATE]               NUMERIC (30, 10) NULL,
    [TOTALCOST]           NUMERIC (30, 10) NULL,
    [PARAMITEMID]         BIGINT           NULL,
    [FACTOR1]             NUMERIC (30, 10) NULL,
    [FACTOR2]             NUMERIC (30, 10) NULL,
    [DIVIDER]             NUMERIC (30, 10) NULL,
    [QTYPUNIT]            NUMERIC (30, 10) NULL,
    [QTYPUNITFORM]        NVARCHAR (MAX)   NULL,
    [QTYPUFORMSTATE]      TINYINT          NULL,
    [TOTALUNITS]          NUMERIC (30, 10) NULL,
    [USERTOTALUNITS]      BIT              NULL,
    [COSTCENTER]          NUMERIC (30, 10) NULL,
    [LOCALFACTOR]         NUMERIC (30, 10) NULL,
    [LOCALCOUNTRY]        NVARCHAR (255)   NULL,
    [LOCALSTATE]          NVARCHAR (255)   NULL,
    [LAST_UPDATE]         DATETIME2 (7)    NULL,
    [FIXEDCOST]           NUMERIC (30, 10) NULL,
    [FINALFIXEDCOST]      NUMERIC (30, 10) NULL,
    [VARIABLECOST]        NUMERIC (30, 10) NULL,
    [PV_VARS]             NVARCHAR (MAX)   NULL,
    [CONSUMABLEID]        BIGINT           NULL,
    [BOQITEMID]           BIGINT           NULL,
    [PRJID]               BIGINT           NULL,
    [REF__ID]             BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([BOQITEMCONSUMABLEID] ASC),
    CONSTRAINT [FK9B2394EB89F3BCA6] FOREIGN KEY ([BOQITEMID]) REFERENCES [dbo].[BOQITEM] ([BOQITEMID]),
    CONSTRAINT [FK9B2394EBB8FEF034] FOREIGN KEY ([PARAMITEMID]) REFERENCES [dbo].[PARAMITEM] ([PARAMITEMID]),
    CONSTRAINT [FK9B2394EBFFA537BE] FOREIGN KEY ([CONSUMABLEID]) REFERENCES [dbo].[CONSUMABLE] ([CONSUMABLEID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_BOQITEM]
    ON [dbo].[BOQITEM_CONSUMABLE]([BOQITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_CONSUMABLE]
    ON [dbo].[BOQITEM_CONSUMABLE]([CONSUMABLEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PARAMITEM]
    ON [dbo].[BOQITEM_CONSUMABLE]([PARAMITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[BOQITEM_CONSUMABLE]([PRJID] ASC);

