CREATE TABLE [dbo].[BOQITEM_EQUIPMENT] (
    [BOQITEMEQUIPMENTID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [FRATE]              NUMERIC (30, 10) NULL,
    [FDEPRATE]           NUMERIC (30, 10) NULL,
    [TOTALCOST]          NUMERIC (30, 10) NULL,
    [PARAMITEMID]        BIGINT           NULL,
    [FACTOR1]            NUMERIC (30, 10) NULL,
    [FACTOR2]            NUMERIC (30, 10) NULL,
    [FACTOR3]            NUMERIC (30, 10) NULL,
    [QTYPUNIT]           NUMERIC (30, 10) NULL,
    [QTYPUNITFORM]       NVARCHAR (MAX)   NULL,
    [QTYPUFORMSTATE]     TINYINT          NULL,
    [COSTCENTER]         NUMERIC (30, 10) NULL,
    [LOCALFACTOR]        NUMERIC (30, 10) NULL,
    [LOCALCOUNTRY]       NVARCHAR (255)   NULL,
    [LOCALSTATE]         NVARCHAR (255)   NULL,
    [TOTALUNITS]         NUMERIC (30, 10) NULL,
    [USERTOTALUNITS]     BIT              NULL,
    [ENERGYPRICE]        NUMERIC (30, 10) NULL,
    [FUELRATE]           NUMERIC (30, 10) NULL,
    [FIXEDCOST]          NUMERIC (30, 10) NULL,
    [FINALFIXEDCOST]     NUMERIC (30, 10) NULL,
    [VARIABLECOST]       NUMERIC (30, 10) NULL,
    [UNITHOURS]          NUMERIC (30, 10) NULL,
    [PV_VARS]            NVARCHAR (MAX)   NULL,
    [LAST_UPDATE]        DATETIME2 (7)    NULL,
    [EQUIPMENTID]        BIGINT           NULL,
    [BOQITEMID]          BIGINT           NULL,
    [PRJID]              BIGINT           NULL,
    [REF__ID]            BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([BOQITEMEQUIPMENTID] ASC),
    CONSTRAINT [FKEAA439E689F3BCA6] FOREIGN KEY ([BOQITEMID]) REFERENCES [dbo].[BOQITEM] ([BOQITEMID]),
    CONSTRAINT [FKEAA439E6B2878194] FOREIGN KEY ([EQUIPMENTID]) REFERENCES [dbo].[EQUIPMENT] ([EQUIPMENTID]),
    CONSTRAINT [FKEAA439E6B8FEF034] FOREIGN KEY ([PARAMITEMID]) REFERENCES [dbo].[PARAMITEM] ([PARAMITEMID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_BOQITEM]
    ON [dbo].[BOQITEM_EQUIPMENT]([BOQITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_EQUIPMENT]
    ON [dbo].[BOQITEM_EQUIPMENT]([EQUIPMENTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PARAMITEM]
    ON [dbo].[BOQITEM_EQUIPMENT]([PARAMITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[BOQITEM_EQUIPMENT]([PRJID] ASC);

