CREATE TABLE [dbo].[BOQITEM_CONDITION] (
    [BOQITEMCONDITIONID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [FUNIT]              NVARCHAR (255)   NULL,
    [SELQTYNAME]         NVARCHAR (255)   NULL,
    [SELQTY]             NUMERIC (30, 10) NULL,
    [OVERUNIT]           NVARCHAR (255)   NULL,
    [OVERQTY]            NUMERIC (30, 10) NULL,
    [FQTY]               NUMERIC (30, 10) NULL,
    [PARAMITEMID]        BIGINT           NULL,
    [FACTOR1]            NUMERIC (30, 10) NULL,
    [FACTOR2]            NUMERIC (30, 10) NULL,
    [SUMUP]              NUMERIC (30, 10) NULL,
    [SELUNIT]            NVARCHAR (255)   NULL,
    [LAST_UPDATE]        DATETIME2 (7)    NULL,
    [CONDITIONID]        BIGINT           NULL,
    [BOQITEMID]          BIGINT           NULL,
    [PRJID]              BIGINT           NULL,
    [REF__ID]            BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([BOQITEMCONDITIONID] ASC),
    CONSTRAINT [FK7725C1733A120306] FOREIGN KEY ([CONDITIONID]) REFERENCES [dbo].[CNDON] ([CONDITIONID]),
    CONSTRAINT [FK7725C17389F3BCA6] FOREIGN KEY ([BOQITEMID]) REFERENCES [dbo].[BOQITEM] ([BOQITEMID]),
    CONSTRAINT [FK7725C173B8FEF034] FOREIGN KEY ([PARAMITEMID]) REFERENCES [dbo].[PARAMITEM] ([PARAMITEMID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_BOQITEM]
    ON [dbo].[BOQITEM_CONDITION]([BOQITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_CONDITION]
    ON [dbo].[BOQITEM_CONDITION]([CONDITIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PARAMITEM]
    ON [dbo].[BOQITEM_CONDITION]([PARAMITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[BOQITEM_CONDITION]([PRJID] ASC);

