CREATE TABLE [dbo].[CNMHISTORY] (
    [ID]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [CONSUMABLEID] BIGINT         NULL,
    [BASETABLEID]  NVARCHAR (255) NULL,
    [RSRC]         NVARCHAR (MAX) NULL,
    [PREDDATE]     DATETIME2 (7)  NULL,
    [PRJID]        BIGINT         NULL,
    [REF__ID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FKBCD85CF2FFA537BE] FOREIGN KEY ([CONSUMABLEID]) REFERENCES [dbo].[CONSUMABLE] ([CONSUMABLEID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_CONSUMABLE]
    ON [dbo].[CNMHISTORY]([CONSUMABLEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[CNMHISTORY]([PRJID] ASC);

