CREATE TABLE [dbo].[EQUIPMENT] (
    [EQUIPMENTID]                BIGINT           IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION]                NVARCHAR (MAX)   NULL,
    [MAKE]                       NVARCHAR (255)   NULL,
    [MODEL]                      NVARCHAR (255)   NULL,
    [UNIT]                       NVARCHAR (255)   NULL,
    [GROUPCODE]                  NVARCHAR (255)   NULL,
    [GEKCODE]                    NVARCHAR (255)   NULL,
    [FUELTYPE]                   NVARCHAR (255)   NULL,
    [RESERVATIONRATE]            NUMERIC (30, 10) NULL,
    [SPAREPARTSRATE]             NUMERIC (30, 10) NULL,
    [TIRESRATE]                  NUMERIC (30, 10) NULL,
    [FUELRATE]                   NUMERIC (30, 10) NULL,
    [LUBRICATESRATE]             NUMERIC (30, 10) NULL,
    [DEPRECIATIONRATE]           NUMERIC (30, 10) NULL,
    [FUELCONSUMPTION]            NUMERIC (30, 10) NULL,
    [CURRENCY]                   NVARCHAR (255)   NULL,
    [COUNTRY]                    NVARCHAR (255)   NULL,
    [STATE]                      NVARCHAR (255)   NULL,
    [DATABASEID]                 BIGINT           NULL,
    [DATABASECREATIONDATE]       BIGINT           NULL,
    [TOTALRATE]                  NUMERIC (30, 10) NULL,
    [NOTES]                      NVARCHAR (255)   NULL,
    [EDITORID]                   NVARCHAR (255)   NULL,
    [CREATEUSER]                 NVARCHAR (255)   NULL,
    [CREATEDATE]                 DATETIME2 (7)    NULL,
    [RESCODE]                    NVARCHAR (255)   NULL,
    [LASTUPDATE]                 DATETIME2 (7)    NULL,
    [ACCRIGHTS]                  NVARCHAR (255)   NULL,
    [KEYW]                       NVARCHAR (MAX)   NULL,
    [TITLE]                      NVARCHAR (MAX)   NULL,
    [DEPRECATION_CALC_METHOD]    INT              NULL,
    [INIT_AQUASITION_PRICE]      NUMERIC (30, 10) NULL,
    [SALVAGE_VALUE]              NUMERIC (30, 10) NULL,
    [INTEREST_RATE]              NUMERIC (30, 10) NULL,
    [DEPRECIATION_YEARS]         NUMERIC (30, 10) NULL,
    [OCCUPATION_HOURS_PER_MONTH] NUMERIC (30, 10) NULL,
    [OCCUPATIONAL_FACTOR]        NUMERIC (30, 10) NULL,
    [VIRTUAL]                    BIT              NULL,
    [PREDICTED]                  BIT              NULL,
    [CONCEPTUAL]                 BIT              NULL,
    [TCHTYPE]                    INT              NULL,
    [TVAL]                       NUMERIC (30, 10) NULL,
    [TUNIT]                      NVARCHAR (255)   NULL,
    [TCOLOR]                     INT              NULL,
    [TREGTYPE]                   INT              NULL,
    [TRIDS]                      NVARCHAR (MAX)   NULL,
    [TRDATE]                     DATETIME2 (7)    NULL,
    [EXTRACODE1]                 NVARCHAR (255)   NULL,
    [EXTRACODE2]                 NVARCHAR (255)   NULL,
    [EXTRACODE3]                 NVARCHAR (255)   NULL,
    [EXTRACODE4]                 NVARCHAR (255)   NULL,
    [EXTRACODE5]                 NVARCHAR (255)   NULL,
    [EXTRACODE6]                 NVARCHAR (255)   NULL,
    [EXTRACODE7]                 NVARCHAR (255)   NULL,
    [EXTRACODE8]                 NVARCHAR (255)   NULL,
    [EXTRACODE9]                 NVARCHAR (255)   NULL,
    [EXTRACODE10]                NVARCHAR (255)   NULL,
    [BURATE]                     NUMERIC (30, 10) NULL,
    [OVERTYPE]                   INT              NULL,
    [PRJID]                      BIGINT           NULL,
    [REF__ID]                    BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([EQUIPMENTID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_MDBID]
    ON [dbo].[EQUIPMENT]([DATABASEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[EQUIPMENT]([PRJID] ASC);

