CREATE TABLE [dbo].[FNCTON] (
    [FUNCTIONID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [LASTUPDATE]   DATETIME2 (7)  NULL,
    [TAKEOFF]      BIT            NULL,
    [CREATEUSERID] NVARCHAR (255) NULL,
    [EDITORID]     NVARCHAR (255) NULL,
    [CREATEDATE]   DATETIME2 (7)  NULL,
    [NAME]         NVARCHAR (255) NULL,
    [UNIT]         NVARCHAR (255) NULL,
    [GROUPING]     NVARCHAR (255) NULL,
    [DESCRIPTION]  NVARCHAR (MAX) NULL,
    [LANG]         NVARCHAR (255) NULL,
    [PSWD]         NVARCHAR (255) NULL,
    [SNUM]         NVARCHAR (MAX) NULL,
    [PRTTYPE]      NVARCHAR (255) NULL,
    [IMPL]         NVARCHAR (MAX) NULL,
    [RESTYPE]      NVARCHAR (255) NULL,
    [PRJID]        BIGINT         NULL,
    [REF__ID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([FUNCTIONID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_FNAME]
    ON [dbo].[FNCTON]([NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[FNCTON]([PRJID] ASC);

