CREATE TABLE [dbo].[IFCELEMENT] (
    [ELEMID]          BIGINT           IDENTITY (1, 1) NOT NULL,
    [CNDID]           INT              NULL,
    [IFCID]           NVARCHAR (255)   NULL,
    [IFCFNAME]        NVARCHAR (255)   NULL,
    [IFCFILE]         NVARCHAR (MAX)   NULL,
    [IFCLABEL]        NVARCHAR (255)   NULL,
    [IFCLOCATION]     NVARCHAR (MAX)   NULL,
    [IFCTYPE]         NVARCHAR (255)   NULL,
    [IFCMATERIAL]     NVARCHAR (255)   NULL,
    [IFCLAYER]        NVARCHAR (255)   NULL,
    [IFCBUILDING]     NVARCHAR (255)   NULL,
    [IFCSTOREY]       NVARCHAR (255)   NULL,
    [IFCMODEL]        NVARCHAR (255)   NULL,
    [IFCZONE]         NVARCHAR (255)   NULL,
    [IFCDATE]         DATE             NULL,
    [IFCNAME]         NVARCHAR (255)   NULL,
    [IFCOBJECTTYPE]   NVARCHAR (255)   NULL,
    [IFCCOLOR]        NVARCHAR (255)   NULL,
    [IFCTRANSPARENCY] FLOAT (53)       NULL,
    [IFCQTY1]         NUMERIC (30, 10) NULL,
    [IFCUOM1]         NVARCHAR (255)   NULL,
    [IFCQTYNAME1]     NVARCHAR (255)   NULL,
    [IFCQTY2]         NUMERIC (30, 10) NULL,
    [IFCUOM2]         NVARCHAR (255)   NULL,
    [IFCQTYNAME2]     NVARCHAR (255)   NULL,
    [IFCQTY3]         NUMERIC (30, 10) NULL,
    [IFCUOM3]         NVARCHAR (255)   NULL,
    [IFCQTYNAME3]     NVARCHAR (255)   NULL,
    [IFCTITLE]        NVARCHAR (MAX)   NULL,
    [IFCDESCRIPTION]  NVARCHAR (MAX)   NULL,
    [IFCAPPNAME]      NVARCHAR (MAX)   NULL,
    [TOPELEV]         NUMERIC (30, 10) NULL,
    [BOTTOMELEV]      NUMERIC (30, 10) NULL,
    [PARENTID]        NVARCHAR (255)   NULL,
    [DECOMPOSES]      BIT              NULL,
    [PARENTSPACEID]   NVARCHAR (255)   NULL,
    [PRJID]           BIGINT           NULL,
    [REF__ID]         BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([ELEMID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_IGID]
    ON [dbo].[IFCELEMENT]([IFCID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_IMODEL]
    ON [dbo].[IFCELEMENT]([IFCMODEL] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[IFCELEMENT]([PRJID] ASC);

