CREATE TABLE [dbo].[LABHISTORY] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [LABORID]     BIGINT         NULL,
    [BASETABLEID] NVARCHAR (255) NULL,
    [RSRC]        NVARCHAR (MAX) NULL,
    [PREDDATE]    DATETIME2 (7)  NULL,
    [PRJID]       BIGINT         NULL,
    [REF__ID]     BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK5546C6675C7E33D4] FOREIGN KEY ([LABORID]) REFERENCES [dbo].[LABOR] ([LABORID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_LABOR]
    ON [dbo].[LABHISTORY]([LABORID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[LABHISTORY]([PRJID] ASC);

