CREATE TABLE [dbo].[MATHISTORY] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [MATERIALID]  BIGINT         NULL,
    [BASETABLEID] NVARCHAR (255) NULL,
    [RSRC]        NVARCHAR (MAX) NULL,
    [PREDDATE]    DATETIME2 (7)  NULL,
    [PRJID]       BIGINT         NULL,
    [REF__ID]     BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK97655F342461A27E] FOREIGN KEY ([MATERIALID]) REFERENCES [dbo].[MATERIAL] ([MATERIALID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_MATERIAL]
    ON [dbo].[MATHISTORY]([MATERIALID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[MATHISTORY]([PRJID] ASC);

