CREATE TABLE [dbo].[OSTDBCON] (
    [OSTCONID]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [HOST]         NVARCHAR (255) NULL,
    [USERNAME]     NVARCHAR (255) NULL,
    [PASSWORD]     NVARCHAR (255) NULL,
    [DATABASENAME] NVARCHAR (255) NULL,
    [PRJID]        BIGINT         NULL,
    [REF__ID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([OSTCONID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[OSTDBCON]([PRJID] ASC);

