CREATE TABLE [dbo].[PRJUSERPROP] (
    [ID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [PKEY]     NVARCHAR (255) NULL,
    [PVAL]     NVARCHAR (MAX) NULL,
    [PROPUSER] NVARCHAR (255) NULL,
    [PRJID]    BIGINT         NULL,
    [REF__ID]  BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[PRJUSERPROP]([PRJID] ASC);

