CREATE TABLE [dbo].[PROJECTWBS] (
    [PROJECTWBSID] BIGINT           IDENTITY (1, 1) NOT NULL,
    [LASTUPDATE]   DATETIME2 (7)    NULL,
    [DESCRIPTION]  NVARCHAR (MAX)   NULL,
    [CODE]         NVARCHAR (255)   NULL,
    [ITEMCODE]     NVARCHAR (255)   NULL,
    [TITLE]        NVARCHAR (MAX)   NULL,
    [EDITORID]     NVARCHAR (255)   NULL,
    [UFACT]        NUMERIC (30, 10) NULL,
    [UNIT]         NVARCHAR (255)   NULL,
    [QUANTITY]     NUMERIC (30, 10) NULL,
    [PRJID]        BIGINT           NULL,
    [REF__ID]      BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([PROJECTWBSID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_GROUPCODE]
    ON [dbo].[PROJECTWBS]([CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[PROJECTWBS]([PRJID] ASC);

