CREATE TABLE [dbo].[QUOTEITEM] (
    [QUOTEITEMID]  BIGINT           IDENTITY (1, 1) NOT NULL,
    [TITLE]        NVARCHAR (MAX)   NULL,
    [UNIT]         NVARCHAR (255)   NULL,
    [QUANTITY]     NUMERIC (30, 10) NULL,
    [PARQRTY]      NUMERIC (30, 10) NULL,
    [FACTOR1]      NUMERIC (30, 10) NULL,
    [MANHOURS]     NUMERIC (30, 10) NULL,
    [MATRATE]      NUMERIC (30, 10) NULL,
    [INDIRECT]     NUMERIC (30, 10) NULL,
    [FACTOR2]      NUMERIC (30, 10) NULL,
    [RSRC]         BIT              NULL,
    [STATUS]       NVARCHAR (255)   NULL,
    [QUOTATIONID]  BIGINT           NULL,
    [BOQITEMID]    BIGINT           NULL,
    [INSURANCE]    NUMERIC (30, 10) NULL,
    [RATE]         NUMERIC (30, 10) NULL,
    [SHIPMENTCOST] NUMERIC (30, 10) NULL,
    [FINALRATE]    NUMERIC (30, 10) NULL,
    [DATABASEID]   BIGINT           NULL,
    [SUPDBID]      BIGINT           NULL,
    [DBCREATEDATE] BIGINT           NULL,
    [PRJID]        BIGINT           NULL,
    [REF__ID]      BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([QUOTEITEMID] ASC),
    CONSTRAINT [FK4DBD2B6F28564966] FOREIGN KEY ([QUOTATIONID]) REFERENCES [dbo].[QUOTE] ([EXPENSEID]),
    CONSTRAINT [FK4DBD2B6F89F3BCA6] FOREIGN KEY ([BOQITEMID]) REFERENCES [dbo].[BOQITEM] ([BOQITEMID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_BOQITEM]
    ON [dbo].[QUOTEITEM]([BOQITEMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_MDBID]
    ON [dbo].[QUOTEITEM]([DATABASEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[QUOTEITEM]([PRJID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_QUOTATION]
    ON [dbo].[QUOTEITEM]([QUOTATIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_STATUS]
    ON [dbo].[QUOTEITEM]([STATUS] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_SUPPLIER]
    ON [dbo].[QUOTEITEM]([SUPDBID] ASC);

