CREATE TABLE [dbo].[QUOTE] (
    [EXPENSEID]    BIGINT         IDENTITY (1, 1) NOT NULL,
    [PERFORMANCE]  INT            NULL,
    [SUBJECT]      NVARCHAR (255) NULL,
    [FAX]          NVARCHAR (255) NULL,
    [CURRENCY]     NVARCHAR (255) NULL,
    [DELIVERY]     BIT            NULL,
    [HASMATRATE]   BIT            NULL,
    [DESCRIPTION]  NVARCHAR (MAX) NULL,
    [NOTES]        NVARCHAR (MAX) NULL,
    [TITLE]        NVARCHAR (255) NULL,
    [COMPANY]      NVARCHAR (255) NULL,
    [GEOPOS]       NVARCHAR (255) NULL,
    [QUOTETEMPID]  BIGINT         NULL,
    [CONTACT]      NVARCHAR (255) NULL,
    [EMAIL]        NVARCHAR (255) NULL,
    [PHONE]        NVARCHAR (255) NULL,
    [MOBILE]       NVARCHAR (255) NULL,
    [CITY]         NVARCHAR (255) NULL,
    [COUNTRY]      NVARCHAR (255) NULL,
    [STATEPRO]     NVARCHAR (255) NULL,
    [ADDRESS]      NVARCHAR (255) NULL,
    [URL]          NVARCHAR (255) NULL,
    [TOMAIL]       NVARCHAR (255) NULL,
    [CCMAIL]       NVARCHAR (255) NULL,
    [BCCMAIL]      NVARCHAR (255) NULL,
    [QUOTETYPE]    NVARCHAR (255) NULL,
    [EDITORID]     NVARCHAR (255) NULL,
    [STATUS]       NVARCHAR (255) NULL,
    [GUID]         NVARCHAR (255) NULL,
    [CREATEDATE]   DATETIME2 (7)  NULL,
    [SENTDATE]     DATETIME2 (7)  NULL,
    [RECEIVEDDATE] DATETIME2 (7)  NULL,
    [PRJID]        BIGINT         NULL,
    [REF__ID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([EXPENSEID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[QUOTE]([PRJID] ASC);

