CREATE TABLE [dbo].[SUBHISTORY] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [SUBCONTRACTORID] BIGINT         NULL,
    [BASETABLEID]     NVARCHAR (255) NULL,
    [RSRC]            NVARCHAR (MAX) NULL,
    [PREDDATE]        DATETIME2 (7)  NULL,
    [PRJID]           BIGINT         NULL,
    [REF__ID]         BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK98A18A547C0276B4] FOREIGN KEY ([SUBCONTRACTORID]) REFERENCES [dbo].[SUBCONTRACTOR] ([SUBCONTRACTORID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[SUBHISTORY]([PRJID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_SUBCONTRACTOR]
    ON [dbo].[SUBHISTORY]([SUBCONTRACTORID] ASC);

