CREATE TABLE [dbo].[WSREVISION] (
    [ID]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [TITLE]        NVARCHAR (255) NULL,
    [CODE]         NVARCHAR (255) NULL,
    [CREATEDATE]   DATETIME2 (7)  NULL,
    [LASTUPDATE]   DATETIME2 (7)  NULL,
    [CREATEUSERID] NVARCHAR (255) NULL,
    [EDITORID]     NVARCHAR (255) NULL,
    [SELECTED]     BIT            NULL,
    [MAPPINGID]    BIGINT         NULL,
    [PRJID]        BIGINT         NULL,
    [REF__ID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK364016B7BCB673A4] FOREIGN KEY ([MAPPINGID]) REFERENCES [dbo].[WSDATAMAPPING] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_PRJID]
    ON [dbo].[WSREVISION]([PRJID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_WSDATAMAPPING]
    ON [dbo].[WSREVISION]([MAPPINGID] ASC);

