using System;
//using System.Collections.Generic;

namespace Models.local.Interfaces
{
	public interface IProjectinfo
	{
		long Projectinfoid { get; set; }
		DateTime? Lastupdate { get; set; }
		string Epscode { get; set; }
		string Description { get; set; }
		string Currency { get; set; }
		bool? Primavera { get; set; }
		bool? Locfac { get; set; }
		string Locprof { get; set; }
		string Selfac { get; set; }
		bool? Bimtakeoff { get; set; }
		bool? Ostakeoff { get; set; }
		string Storagetype { get; set; }
		string Codestyle { get; set; }
		string Code { get; set; }
		string Title { get; set; }
		string Editorid { get; set; }
		decimal? Totalcost { get; set; }
		decimal? Offeredprice { get; set; }
		string Status { get; set; }
		string Location { get; set; }
		string Unit { get; set; }
		string Country { get; set; }
		string Client { get; set; }
		decimal? Basement { get; set; }
		decimal? Mainsite { get; set; }
		decimal? Unitcost { get; set; }
		string State { get; set; }
		string Prjtype { get; set; }
		string Prjsubcat { get; set; }
		string Contractor { get; set; }
		string Geoloc { get; set; }
		int? Floors { get; set; }
		int? Duration { get; set; }
		decimal? Clientbudget { get; set; }
		DateTime? Subdate { get; set; }
		string Defrev { get; set; }
		decimal? Cusepsrate1 { get; set; }
		decimal? Cusepsrate2 { get; set; }
		decimal? Cusepsrate3 { get; set; }
		decimal? Cusepsrate4 { get; set; }
		decimal? Cusepsrate5 { get; set; }
		decimal? Cusepsrate6 { get; set; }
		decimal? Cusepsrate7 { get; set; }
		decimal? Cusepsrate8 { get; set; }
		decimal? Cusepsrate9 { get; set; }
		decimal? Cusepsrate10 { get; set; }
		string Cusepstext1 { get; set; }
		string Cusepstext2 { get; set; }
		string Cusepstext3 { get; set; }
		string Cusepstext4 { get; set; }
		string Cusepstext5 { get; set; }
		string Cusepstext6 { get; set; }
		string Cusepstext7 { get; set; }
		string Cusepstext8 { get; set; }
		string Cusepstext9 { get; set; }
		string Cusepstext10 { get; set; }
		string Cusepstext11 { get; set; }
		string Cusepstext12 { get; set; }
		string Cusepstext13 { get; set; }
		string Cusepstext14 { get; set; }
		string Cusepstext15 { get; set; }
		string Cusepstext16 { get; set; }
		string Cusepstext17 { get; set; }
		string Cusepstext18 { get; set; }
		string Cusepstext19 { get; set; }
		string Cusepstext20 { get; set; }
		decimal? Cuscumrate1 { get; set; }
		decimal? Cuscumrate2 { get; set; }
		decimal? Cuscumrate3 { get; set; }
		decimal? Cuscumrate4 { get; set; }
		decimal? Cuscumrate5 { get; set; }
		decimal? Cuscumrate6 { get; set; }
		decimal? Cuscumrate7 { get; set; }
		decimal? Cuscumrate8 { get; set; }
		decimal? Cuscumrate9 { get; set; }
		decimal? Cuscumrate10 { get; set; }
		decimal? Cuscumrate11 { get; set; }
		decimal? Cuscumrate12 { get; set; }
		decimal? Cuscumrate13 { get; set; }
		decimal? Cuscumrate14 { get; set; }
		decimal? Cuscumrate15 { get; set; }
		decimal? Cuscumrate16 { get; set; }
		decimal? Cuscumrate17 { get; set; }
		decimal? Cuscumrate18 { get; set; }
		decimal? Cuscumrate19 { get; set; }
		decimal? Cuscumrate20 { get; set; }
		DateTime? Cusepsdate1 { get; set; }
		DateTime? Cusepsdate2 { get; set; }
		DateTime? Cusepsdate3 { get; set; }
		DateTime? Cusepsdate4 { get; set; }
		DateTime? Cusepsdate5 { get; set; }
		DateTime? Cusepsdate6 { get; set; }
		DateTime? Cusepsdate7 { get; set; }
		DateTime? Cusepsdate8 { get; set; }
		DateTime? Cusepsdate9 { get; set; }
		DateTime? Cusepsdate10 { get; set; }
		decimal? Equcost { get; set; }
		decimal? Subcost { get; set; }
		decimal? Labcost { get; set; }
		decimal? Matcost { get; set; }
		decimal? Concost { get; set; }
		decimal? Manhours { get; set; }
		decimal? Equhours { get; set; }
		long? Projectepsid { get; set; }
		string Creatorid { get; set; }
		DateTime? Createdate { get; set; }
		BaseClass.Projecteps Projecteps { get; set; }
		//ICollection<Projecturl> Projecturl { get; set; }
		//ICollection<Projectuser> Projectuser { get; set; }
		//ICollection<Takeoffcon> Takeoffcon { get; set; }
		
		Projectinfo Clone();
	}
}
