CREATE TABLE [dbo].[BC_ELEMENT] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [GLOBALID]       NVARCHAR (256) NULL,
    [HASGEOM]        BIT            NULL,
    [LAYER]          NVARCHAR (256) NULL,
    [NAME]           NVARCHAR (256) NULL,
    [SPATIAL]        BIT            NULL,
    [TAGID]          NVARCHAR (256) NULL,
    [TYPE]           INT            NULL,
    [TYPEDESC]       NVARCHAR (256) NULL,
    [CONTAINEDBY_ID] BIGINT         NULL,
    [MODEL_ID]       BIGINT         NULL,
    [PARENT_ID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK1D1688DE4160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FK1D1688DE4CA532E0] FOREIGN KEY ([CONTAINEDBY_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID]),
    CONSTRAINT [FK1D1688DEACC2EE40] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

