CREATE TABLE [dbo].[BC_ELEMCONNECTION] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [GLOBALID]        NVARCHAR (256) NULL,
    [NAME]            NVARCHAR (256) NULL,
    [RELATEDTYPE]     INT            NULL,
    [RELATINGTYPE]    INT            NULL,
    [MODEL_ID]        BIGINT         NULL,
    [RELATEDELEM_ID]  BIGINT         NULL,
    [RELATINGELEM_ID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FKA76BC36B4160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FKA76BC36BA2CCAEA5] FOREIGN KEY ([RELATINGELEM_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID]),
    CONSTRAINT [FKA76BC36BEA8AB2B0] FOREIGN KEY ([RELATEDELEM_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

