CREATE TABLE [dbo].[BC_ELEMCOVERING] (
    [ID]              BIGINT IDENTITY (1, 1) NOT NULL,
    [TYPE]            INT    NULL,
    [COVERELEM_ID]    BIGINT NULL,
    [MODEL_ID]        BIGINT NULL,
    [RELATINGELEM_ID] BIGINT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK9B129C984160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FK9B129C98A2CCAEA5] FOREIGN KEY ([RELATINGELEM_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID]),
    CONSTRAINT [FK9B129C98B23BA5A4] FOREIGN KEY ([COVERELEM_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

