CREATE TABLE [dbo].[BC_GEOMETRY] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [GLOBALID]    NVARCHAR (256) NULL,
    [TYPE]        INT            NULL,
    [ELEMENT_ID]  BIGINT         NULL,
    [GEOMFILE_ID] BIGINT         NULL,
    [MODEL_ID]    BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FKF441DAB03E18A2E4] FOREIGN KEY ([GEOMFILE_ID]) REFERENCES [dbo].[BC_GEOMFILE] ([ID]),
    CONSTRAINT [FKF441DAB04160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FKF441DAB053B05EAE] FOREIGN KEY ([ELEMENT_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

