CREATE TABLE [dbo].[BC_QUANTITY] (
    [ID]         BIGINT           IDENTITY (1, 1) NOT NULL,
    [GRPNAME]    NVARCHAR (256)   NULL,
    [NAME]       NVARCHAR (256)   NULL,
    [NAMEID]     INT              NULL,
    [QTYPE]      INT              NULL,
    [VAL]        NUMERIC (30, 10) NULL,
    [ELEMENT_ID] BIGINT           NULL,
    [MODEL_ID]   BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK39A236C94160E6D4] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[BC_MODEL] ([ID]),
    CONSTRAINT [FK39A236C953B05EAE] FOREIGN KEY ([ELEMENT_ID]) REFERENCES [dbo].[BC_ELEMENT] ([ID])
);

