CREATE TABLE [dbo].[EXTDATASOURCE] (
    [DATASOURCEID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [DSTITLE]      NVARCHAR (255) NULL,
    [DSTYPE]       TINYINT        NULL,
    [JDBCTYPE]     TINYINT        NULL,
    [JDBCDRIVER]   NVARCHAR (MAX) NULL,
    [JDBCURL]      NVARCHAR (MAX) NULL,
    [JDBCUSER]     NVARCHAR (255) NULL,
    [JDBCPSW]      NVARCHAR (255) NULL,
    [CREATEUSER]   NVARCHAR (255) NULL,
    [CREATEDATE]   DATETIME2 (7)  NULL,
    [EDITORID]     NVARCHAR (255) NULL,
    [LASTUPDATE]   DATETIME2 (7)  NULL,
    PRIMARY KEY CLUSTERED ([DATASOURCEID] ASC)
);

