CREATE TABLE [dbo].[LAYOUTCPANEL] (
    [LAYOUTCPANELID]    BIGINT         IDENTITY (1, 1) NOT NULL,
    [LAYOUTCID]         BIGINT         NULL,
    [PREFCOLS]          NVARCHAR (MAX) NULL,
    [LOCKEDCOLS]        NVARCHAR (MAX) NULL,
    [SORTEDCOLS]        NVARCHAR (MAX) NULL,
    [FILTERCOLS]        NVARCHAR (MAX) NULL,
    [ASSMENT]           BIT            NULL,
    [VIZER]             BIT            NULL,
    [SELVIZER]          NVARCHAR (255) NULL,
    [SIDE]              BIT            NULL,
    [GRPN]              BIT            NULL,
    [DSGRP]             BIT            NULL,
    [GRPCOLS]           NVARCHAR (MAX) NULL,
    [GRPORDS]           NVARCHAR (MAX) NULL,
    [VSBLE]             BIT            NULL,
    [COLUMNS]           NVARCHAR (255) NULL,
    [COLUMNWIDTHS]      NVARCHAR (255) NULL,
    [SORTTYPEUP]        BIT            NULL,
    [SORTINDEX]         INT            NULL,
    [AUTORESIZE]        BIT            NULL,
    [ROWHEIGHT]         INT            NULL,
    [FILTERS]           BIT            NULL,
    [XTRALVL]           BIT            NULL,
    [LAYOUTCPANELCOUNT] INT            NULL,
    PRIMARY KEY CLUSTERED ([LAYOUTCPANELID] ASC),
    CONSTRAINT [FK159F2B2B74F88FBC] FOREIGN KEY ([LAYOUTCID]) REFERENCES [dbo].[LAYOUTC] ([LAYOUTCID])
);

