CREATE TABLE [dbo].[LAYOUTC] (
    [LAYOUTCID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [NAME]        NVARCHAR (255) NULL,
    [LASTUPDATE]  DATETIME2 (7)  NULL,
    [CREATORID]   NVARCHAR (255) NULL,
    [EDITORID]    NVARCHAR (255) NULL,
    [SELECTEDGK]  NVARCHAR (255) NULL,
    [PBLK]        BIT            NULL,
    [DFLT]        BIT            NULL,
    [TYPE]        NVARCHAR (255) NULL,
    [VISIBTABS]   NVARCHAR (MAX) NULL,
    [SHOWTREE]    BIT            NULL,
    [SPANGRP]     BIT            NULL,
    [ROWSTRP]     BIT            NULL,
    [GRPNAME]     NVARCHAR (255) NULL,
    [F1NAME]      NVARCHAR (255) NULL,
    [F1SIZE]      INT            NULL,
    [F1STYLE]     INT            NULL,
    [F2NAME]      NVARCHAR (255) NULL,
    [F2SIZE]      INT            NULL,
    [F2STYLE]     INT            NULL,
    [F3NAME]      NVARCHAR (255) NULL,
    [F3SIZE]      INT            NULL,
    [F3STYLE]     INT            NULL,
    [F4NAME]      NVARCHAR (255) NULL,
    [F4SIZE]      INT            NULL,
    [FNNAME]      NVARCHAR (255) NULL,
    [FNSIZE]      INT            NULL,
    [FNSTYLE]     INT            NULL,
    [FNCLR]       NVARCHAR (255) NULL,
    [FUNAME]      NVARCHAR (255) NULL,
    [FUSIZE]      INT            NULL,
    [FUSTYLE]     INT            NULL,
    [FUCLR]       NVARCHAR (255) NULL,
    [F4STYLE]     INT            NULL,
    [F5NAME]      NVARCHAR (255) NULL,
    [F5SIZE]      INT            NULL,
    [F5STYLE]     INT            NULL,
    [LFNAME]      NVARCHAR (255) NULL,
    [LFSIZE]      INT            NULL,
    [LFSTYLE]     INT            NULL,
    [F1CLR]       NVARCHAR (255) NULL,
    [F2CLR]       NVARCHAR (255) NULL,
    [F3CLR]       NVARCHAR (255) NULL,
    [F4CLR]       NVARCHAR (255) NULL,
    [F5CLR]       NVARCHAR (255) NULL,
    [LFCLR]       NVARCHAR (255) NULL,
    [RS1CLR]      NVARCHAR (255) NULL,
    [RS2CLR]      NVARCHAR (255) NULL,
    [MLTLN]       BIT            NULL,
    [ZOOM]        INT            NULL,
    [GRIDON]      BIT            NULL,
    [HGRIDON]     BIT            NULL,
    [F1UNDL]      BIT            NULL,
    [F2UNDL]      BIT            NULL,
    [F3UNDL]      BIT            NULL,
    [F4UNDL]      BIT            NULL,
    [F5UNDL]      BIT            NULL,
    [FNUNDL]      BIT            NULL,
    [FUUNDL]      BIT            NULL,
    [FLUNDL]      BIT            NULL,
    [L1BCLR]      NVARCHAR (255) NULL,
    [L2BCLR]      NVARCHAR (255) NULL,
    [L3BCLR]      NVARCHAR (255) NULL,
    [L4BCLR]      NVARCHAR (255) NULL,
    [L5BCLR]      NVARCHAR (255) NULL,
    [LNBCLR]      NVARCHAR (255) NULL,
    [UNBCLR]      NVARCHAR (255) NULL,
    [LFBCLR]      NVARCHAR (255) NULL,
    [ROWHEAD]     BIT            NULL,
    [CSEP]        BIT            NULL,
    [CSEPCLR]     NVARCHAR (255) NULL,
    [GRIDCLR]     NVARCHAR (255) NULL,
    [LAYOUTROLES] NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([LAYOUTCID] ASC)
);

