CREATE TABLE [dbo].[PRJPROP] (
    [ID]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [PKEY]         NVARCHAR (255) NULL,
    [PVAL]         NVARCHAR (MAX) NULL,
    [PROJECTURLID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK18184DEB7C786EFE] FOREIGN KEY ([PROJECTURLID]) REFERENCES [dbo].[PROJECTURL] ([PROJECTURLID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_PROPKEY]
    ON [dbo].[PRJPROP]([PKEY] ASC);

