CREATE TABLE [dbo].[PROJECTACCESS] (
    [PAID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [TITLE]  NVARCHAR (255) NULL,
    [ACCCON] NVARCHAR (MAX) NULL,
    [ALADD]  BIT            NULL,
    [ALUPD]  BIT            NULL,
    [ALREM]  BIT            NULL,
    [PUID]   BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([PAID] ASC),
    CONSTRAINT [FK844DA19D4D514A55] FOREIGN KEY ([PUID]) REFERENCES [dbo].[PROJECTUSER] ([PUID])
);

