CREATE TABLE [dbo].[PROJECTURL] (
    [PROJECTURLID]  BIGINT           IDENTITY (1, 1) NOT NULL,
    [URL]           NVARCHAR (255)   NULL,
    [DBUSR]         NVARCHAR (255)   NULL,
    [DBPSWD]        NVARCHAR (255)   NULL,
    [DBHOST]        NVARCHAR (255)   NULL,
    [DBPORT]        NVARCHAR (255)   NULL,
    [DBPREFIX]      NVARCHAR (255)   NULL,
    [DBSINGLE]      BIT              NULL,
    [DBNAME]        NVARCHAR (255)   NULL,
    [DBSRV]         INT              NULL,
    [DBSRVNAME]     NVARCHAR (255)   NULL,
    [QSENT]         INT              NULL,
    [QRECV]         INT              NULL,
    [DEFREV]        BIT              NULL,
    [EDITORID]      NVARCHAR (255)   NULL,
    [TYPE]          NVARCHAR (255)   NULL,
    [NAME]          NVARCHAR (255)   NULL,
    [RVSON]         NVARCHAR (255)   NULL,
    [CREUSERID]     NVARCHAR (255)   NULL,
    [CREATEDATE]    DATETIME2 (7)    NULL,
    [LASTUPDATE]    DATETIME2 (7)    NULL,
    [UNDERREVIEW]   INT              NULL,
    [PENDING]       INT              NULL,
    [APPROVED]      INT              NULL,
    [COMPLETED]     INT              NULL,
    [ESTTOTAL]      NUMERIC (30, 10) NULL,
    [QUOTEDTOTAL]   NUMERIC (30, 10) NULL,
    [MARKUPTOTAL]   NUMERIC (30, 10) NULL,
    [MUSTRECALC]    BIT              NULL,
    [FROZEN]        BIT              NULL,
    [BENCHMARKID]   BIGINT           NULL,
    [DESCRIPTION]   NVARCHAR (MAX)   NULL,
    [PROJECTINFOID] BIGINT           NULL,
    [PROJECTDBMSID] BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([PROJECTURLID] ASC),
    CONSTRAINT [FKA77EE3B65B1C0C14] FOREIGN KEY ([PROJECTINFOID]) REFERENCES [dbo].[PROJECTINFO] ([PROJECTINFOID]),
    CONSTRAINT [FKA77EE3B6728B054] FOREIGN KEY ([PROJECTDBMSID]) REFERENCES [dbo].[PRJDBMS] ([ID])
);

