CREATE TABLE [dbo].[QUERYROW] (
    [QROWID]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [FNAME]      NVARCHAR (255) NULL,
    [RNAME]      NVARCHAR (255) NULL,
    [CNDN]       NVARCHAR (MAX) NULL,
    [CTYPE]      NVARCHAR (255) NULL,
    [QRESID]     BIGINT         NULL,
    [QROWSCOUNT] INT            NULL,
    PRIMARY KEY CLUSTERED ([QROWID] ASC),
    CONSTRAINT [FKE91C7C12AB986C17] FOREIGN KEY ([QRESID]) REFERENCES [dbo].[QUERYRESOURCE] ([QRESID])
);

