CREATE TABLE [dbo].[RPDFN] (
    [RPDFNID]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [RNAME]       NVARCHAR (255) NULL,
    [RICN]        NVARCHAR (255) NULL,
    [RDSGN]       NVARCHAR (255) NULL,
    [RDESC]       NVARCHAR (MAX) NULL,
    [REDTID]      NVARCHAR (255) NULL,
    [RCREUSER]    NVARCHAR (255) NULL,
    [RLASTUPD]    DATETIME2 (7)  NULL,
    [RCREDATE]    DATETIME2 (7)  NULL,
    [RGRP]        NVARCHAR (255) NULL,
    [RPBLK]       BIT            NULL,
    [RUSRREP]     BIT            NULL,
    [MLTUSRRPT]   BIT            NULL,
    [REPORTTYPE]  NVARCHAR (255) NULL,
    [RJSURL]      NVARCHAR (255) NULL,
    [REPORTROLES] NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([RPDFNID] ASC)
);

