CREATE TABLE [dbo].[UNITALIAS] (
    [ID]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [FRUNIT] NVARCHAR (255) NULL,
    [TOUNIT] NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_FROMUNIT]
    ON [dbo].[UNITALIAS]([FRUNIT] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_TOUNIT]
    ON [dbo].[UNITALIAS]([TOUNIT] ASC);

